Coding-Test-Study-Group/Coding-Test-Study

- byeongjoo/백준 5430 AC.py
- [백준 5430번 AC](https://www.acmicpc.net/problem/5430)
---
데크
---
전체 테스트 케이스 p의 길이의 합과 n의 길의 합이 70만이 넘지 않으므로 브루트포스로는 풀 수 없는 문제다.
따라서 현 문제는 반복문을 사용할 경우 1회를 이용하여 풀어야 한다.( O(n) )
파이썬을 이용한다면 R의 경우 reverse() 메소드를 이용할 수 있겠다 생각할 수 있지만, reverse() 메소드는 시간복잡도가 O(n)에 해당한다. 그러므로 reverse()를 사용할 경우 시간 초과가 날 수 밖에 없는 환경이 만들어지므로 다른 방안을 생각해야 한다.
본인의 경우는 스위치처럼 R이 1이면 뒤집기, R이 0이면 원상태라는 것을 생각하여 R을 초기값을 0으로 주고, R = 1 - R 을 하여, 1과 0만 나오게 만들어 뒤집어야될 것과 뒤집지 않아도 될 것을 나누었다. (Kick Point)
따라서 뒤집지 않았다면 앞 요소를 pop (파이썬에선 popleft) , 뒤집었다면 pop (파이썬에선 pop) 을 사용하면 된다.
또한 deque(input()~ ) 을 사용한다해도 input() 안에 데이터가 없을 경우 deque는 ' ' 을 반환하여 우리가 원하는 null 데이터를 얻을 수 없다. (이게 생각보다 Kick Point?)
본인이 이 문제를 풀 때 가장 많이 틀린 부분이 print("["+ ",".join(dq)+ "]") 이다. 본인 같은 경우는 '+'가 아닌 ' ,'를 사용했는데 무슨 문제인지 모르겠지만 계속 틀리다고 나온다. 이건 아는 …
> 백준 5430번 AC

- hyeonwoo/백준 5430 AC.py
- [백준 5430 AC](https://www.acmicpc.net/problem/5430)
---
- 구현
- 배열
- 문자열
---
- R 연산을 있는 그대로 수행해서 배열을 뒤집으면 시간 초과가 발생
수행 목록 중 R이 짝수 개수이면 R이 없는 것과 같고, 홀수 개수이면 R을 한 번만 수행하면 된다.
- D 연산은 R 수행 여부에 따라 첫 번째 원소를 삭제하거나 마지막 원소를 삭제하는 경우로 나뉜다.
R 수행 여부를 체크하기 위해 `1`이 담긴 변수를 하나 만들고, R이 나오면 `-1`을 곱하여 수행 여부를 양수와 음수로 토글하여 구분
따라서 D 연산을 할 때, 체크용 변수가 양수면 첫 번째 원소를 삭제하고, 음수면 마지막 원소를 삭제
- 모든 연산을 수행한 뒤, R이 짝수 개수이면 그대로 출력하고, 홀수 개수이면 배열을 한 번 뒤집는다.
```
1
D
0
[]
```
```
error
```
```
1
D
1
[0]
```
```
[]
```
```
1
R
0
[]
```
```
[]
```
```
1
RDR
3
[1,2,3]
```
```
[1,2]
```
```
1
DRD
3
[1,2,3]
```
```
[2]
```
```
1
DRD
1
[1]
```
```
error
```
---
> 백준 5430 AC

- taehyeong/pg 나누어 떨어지는 숫자 배열.js
https://school.programmers.co.kr/learn/courses/30/lessons/12910
---
- 여기에 작성해 주세요.
sort() - 배열을 요소를 정렬하는 메서드입니다.
---
- 여기에 작성해 주세요.
arr배열의 요소들을 divisor로 나눴을때 나오는 값이 0이면 해당 배열 요소들을 빈 배열 answer에 푸시해줍니다.
마지막에 오름차순 처리만 해주면 간단하게 해결할 수 있습니다. 그리고 answer에 배열의 요소가 없다면 -1을 푸시해줍니다.
---
> ✨프로그래머스 나누어 떨어지는 숫자 배열

- .gitignore
- sollyj/week1/treasure.java
- sollyj/week1/triangle.java
- sollyj/week2/fingers.java
- [백준 1614번 영식이의손가락](https://www.acmicpc.net/problem/1614)
---
- 
---
- 손가락1~5의 경우밖에 없으므로 각 경우의수의 규칙을 찾는것이 관건
---
> 백준 1614 영식이의손가락

- Cobluesky/Programmers - 기사단원의 무기.js
Programmers 기사단원의 무기 : https://school.programmers.co.kr/learn/courses/30/lessons/136798
---
약수의 개수를 구해야합니다.
이 과정에서 시간복잡도가 높으면 기준에서 벗어나게 되므로, 시간 복잡도를 줄일 방법이 필요합니다.
약수의 성질을 이용해 시간복잡도를 줄였습니다.
---
- 주석을 참조해주세요
---
> 2022-11-23 Programmers - 기사단원의 무기 (JS)

- jiWoo/백준_10868번_최솟값.java
- [백준 10868번 최솟값](https://www.acmicpc.net/problem/10868)
---
-  주어진 데이터들의 구간의 값과 업데이트를  수행하기 위해 세그먼트 트리 자료구조를 사용! 
---
-1.  세그먼트 트리 자료구조에 맞추어 트리에 데이터들을 넣어준다.
2. setMinTree 메소드를 사용하여 트리 min 값을 세팅하고
3.  findMin을 사용하여 a~b값의 최솟값을 구한다.
4.  findMin ->  a가 b보다 커질 때까지 반복( 1. a가 오른쪽 노드이면 최솟값과 비교 후 저장 2. b가 왼쪽 노드이면 최솟값과 비교 후 저장,  a와 b 부모노드로 이동)
---
> 백준 10868번 최솟값

- hyeonwoo/백준 2164 카드2.py
- [백준 2164 카드2](https://www.acmicpc.net/problem/2164)
---
- 자료구조
- 큐
- 덱
---
- 문제가 요구하는 연산은 FIFO(first In First Out) 기반이기 때문에 `queue`를 이용
- 파이썬에서 `list`로 `queue`를 구현하게 되면, `pop(0)` 연산을 할 때 `O(N)`의 시간복잡도를 가진다.
- 문제의 제약 조건(`N(1 ≤ N ≤ 500,000)`)을 보면 데어터의 개수가 많으므로, `O(N)`의 시간복잡도로 연산을 하게 되면 시간 초과가 발생한다.
- 따라서,  `collections` 모듈의 `deque`를 사용했다.
- `deque`는 파이썬에서 스택과 큐를 구현할 수 있는 자료구조이다.
- `deque`의 `popleft()`는 `O(1)`의 시간복잡도를 가지기 때문에 `list`보다 훨씬 빠른 속도를 갖는다.
---
> 백준 2164 카드2

- byeongjoo/백준 3986 좋은 단어.py
[백준 3986번 좋은 단어](https://www.acmicpc.net/problem/3986)
스택
정석적인 스택을 이용한 괄호쌍과 비슷한 문제.
리스트를 이용하여 한 스택을 만들어두고, 문자열로 만들어진 데이터를 받아와서 하나의 문자마다 잘라서 비교하였다.
if stack 을 이용하여 stack 이 있다면 stack의 pop과 push 연산을 처리하고, 만약 stack이 비어있다면 현재 문자열의 한 문자를 stack에 삽입하게 만들었다.
현재 문자와 스택의 top 이 같은 문자라면 스택은 pop 연산을 가능케 했으며, 만약 같지 않다면 현재 문자를 stack에 삽입하도록 하였다.
반복문 연산이 끝나고나서 만약 스택이 비어있다면 count 값을 1 더해주었으며, 만약 스택이 비어있지 않다면 이것은 정상적으로 글자끼리 짝이 맞지 않다는 것이므로 count 값의 변화를 주지 않았다.
---
> 백준 3986번 좋은 단어

- Cobluesky/Programmers - 정수 내림차순으로 배치하기.js
https://school.programmers.co.kr/learn/courses/30/lessons/12933
---
Tim Sort를 사용하였습니다.
(JS의 sort()는 기본적으로 Tim Sort입니다.)
https://d2.naver.com/helloworld/0315536 -- Tim Sort
---
- 주석을 참조해주세요.
---
> 2022-11-24 Programmers - 정수 내림차순으로 배치하기 (JS)

- sollyj/prefixSum.java
-  [백준 11659번 구간합](https://www.acmicpc.net/problem/11659)
---
- 누적 합
---
- N개의 정수들 중 i번째까지의 누적 합을 저장한 sum_arr배열
- 이를 이용해 구간 합을 구한다.
---
> 백준 11659 구간합

- hyeonwoo/백준 10866 덱.py
- [백준 10866 덱](https://www.acmicpc.net/problem/10866)
---
- 자료구조
- 덱
---
- 파이썬에 내장된 `collections` 모듈의 `deque`을 이용하여 구현
---
> 백준 10866 덱

- hyeonwoo/백준 10816 숫자 카드 2.py
- [백준 10816 숫자 카드 2](https://www.acmicpc.net/problem/10816)
---
- 자료구조
- 해시
- 딕셔너리
---
- 이 문제를 푸는 방법은 크게 두 가지로, 해시와 더불어 이진 탐색을 이용해서 풀 수도 있다.
- 저는 파이썬에서 해시 구조로 이루어진 딕셔너리 자료구조를 이용해 풀었습니다.
- 딕셔너리의 시간복잡도는 대부분 `O(1)`을 갖기 때문에 제약 조건(`N(1 ≤ N ≤ 500,000)`, `M(1 ≤ M ≤ 500,000)`) 속에서 시간초과를 피할 수 있다.
- 상근이가 가지고 있는 숫자 카드를 딕셔너리로 `{"가지고 있는 카드": 가지고 있는 카드 개수}`의 형태로 저장하여 비교 대상 카드가 딕셔너리 안에 들어있는지 비교하였다.
---
> 백준 10816 숫자 카드 2

- jiWoo/프로그래머스_기사단원의무기.java
[프로그래머스 기사단원의 무기](https://school.programmers.co.kr/learn/courses/30/lessons/136798?language=java)
---
- 약수
---
- 숫자 num의 약수를 구할 때 반복문을 1~ num/2(num의 반까지)로 약수를 구하였다. (1 제외)
-  어차피 숫자 2에서 반으로 줄기 때문에 전부 확인해줄 필요 없어서..? 
---
> 프로그래머스 기사단원의무기(java)

- sollyj/prefixSum_2.java
-  [백준 11660번 구간합5](https://www.acmicpc.net/problem/11660)
---
- 누적합
---
- 주석 참고
---
> 백준 11660 구간합5

- taehyeong/programmers-음양 더하기.js
- [음양 더하기](https://school.programmers.co.kr/learn/courses/30/lessons/76501)
- 정수
정수 배열과 불리언 배열이 주어집니다.
불리언 배열과 정수배열은 길이가 같습니다. ( 정수배열.length = 불리언배열.length )
불리언 배열의 각 요소의 값(true,false)에 따라 정수 배열의 요소 값(양수,음수)로 나눠지게 됩니다. 
불리언 배열의 값에 따라 조건식을 만들어 주어 정수배열의 요소의 값을 판별 뒤 더해주면 됩니다.
> ✨프로그래머스 음양 더하기

- sollyj/Baekjoon_1614_영식이의손가락.java
- [백준 1614 영식이의손가락](https://www.acmicpc.net/problem/1614)
---
- 여기에 작성해 주세요.
---
- 여기에 작성해 주세요.
---
> Baekjoon_1614_영식이의손가락

- sollyj/Baekjoon_1026_보물.java
- sollyj/Baekjoon_1614_영식이의손가락.java
- [백준 1026번 보물](https://www.acmicpc.net/problem/1026)
---
- 
---
---
> Baekjoon_1026_보물

- sollyj/Baekjoon_1026_보물.java
- sollyj/Baekjoon_1614_영식이의손가락.java
- sollyj/baekjoon_1448_삼각형만들기.java
- [백준 1448번 삼각형만들기](https://www.acmicpc.net/problem/1448)
---
- 
---
- 
---
> Baekjoon_1448_삼각형만들기

- sollyj/Baekjoon_1026_보물.java
- sollyj/Baekjoon_1614_영식이의손가락.java
- sollyj/Baekjoon_2018_수들의합5.java
- sollyj/baekjoon_1448_삼각형만들기.java
[백준 2018번 수들의합5](https://www.acmicpc.net/problem/2018)
---
- 투포인터
- 2개의 포인터로 시간 복잡도를 최적화한다.
---
- 연속된 자연수들의 처음과 끝값을 start와 end라고 한다.
- sum과 N을 크기비교 하면서 end가 N일때까지 반복한다.
- sum과 N이 같아지면 answer++ 하면서 최종 결과를 출력한다.
---
> Baekjoon_2018_수들의합5

- sollyj/Baekjoon_1026_보물.java
- sollyj/Baekjoon_1614_영식이의손가락.java
- sollyj/Baekjoon_1940_주몽.java
- sollyj/Baekjoon_2018_수들의합5.java
- sollyj/baekjoon_1448_삼각형만들기.java
- [백준 1940번 주몽](https://www.acmicpc.net/problem/1940)
---
- 투포인터
---
- 두 재료를 one, two라고 한다.
- 배열을 순회하면서 two = M - one라고 하여 one + two = M이 되는 two가 배열안에 있는지 확인한다.
---
> Baekjoon_1940_주몽

- taehyeong/programmers-가운데 글자 가져오기.js
- taehyeong/programmers-나누어 떨어지는 숫자 배열.js
- taehyeong/programmers-수박수박수박수박수박수?.js
- taehyeong/programmers-음양 더하기.js
- taehyeong/programmers-평균 구하기.js
[수박수박수박수박수박수?](https://school.programmers.co.kr/learn/courses/30/lessons/12922)
문자열
String.repeat 메서드를 사용하지 않고 for문안에 조건식을 이용하여 풀이하였습니다.
> ✨프로그래머스-수박수박수박수박수박수?

- hyeonwoo/백준 11050 이항 계수 1.py
- [백준 11050 이항 계수 1](https://www.acmicpc.net/problem/11050)
---
- 수학
- 구현
---
- `math` 모듈을 이용해 조합을 계산했다.
---
> 백준 11050 이항 계수 1

- sollyj/Baekjoon_1253_좋은수.java
- [백준 1253번 좋은수](https://www.acmicpc.net/problem/1253)
---
- 투포인터
---
- N개의 수를 배열(arr)에 넣고 배열의 값들을 순회하면서 좋은수(find)를 찾는다.
- 배열의 양끝을 포인터1(i), 포인터2(j)로 두고 temp_sum = arr[i] + arr[j]와 find를 비교하며 i과 j를 조절한다.
- temp_sum == find일때 자기자신은 좋은 수에 포함하면 안되므로 예외처리를 해줘야한다.
---
> Baekjoon_1253_좋은수

- byeongjoo/백준 10816 숫자 카드 2.py
[백준 10816번 숫자 카드 2] (https://www.acmicpc.net/problem/10816)
이분탐색
숫자 카드에 적혀있는 수들의 갯수만 세면 되는 문제이지만, 시간을 조금 주기에 브루트포스로는 풀 수 없을 것 같아 이분탐색을 이용하였다.
투포인터를 사용하기 위해선 일단 정렬된 수열이 필요하므로 card 를 sort() 를 이용해 정렬해 주었다.
그 후 파이썬 이분탐색 모듈인 bisect를 이용하여 타겟이 되는 수의 첫 인덱스값을 left로 찾고, 마지막 인덱스값이 되는 것을 right로 찾아 right - left를 이용하여 수의 갯수를 세었다.
그 후 targetList 원소에 맞춰 값을 출력하면 되는 문제였다.
---
> 백준 10816번 숫자 카드 2

- jiWoo/백준_11505번_구간곱구하기.java
- [백준 11505번  구간 곱 구하기](https://www.acmicpc.net/problem/11505)
---
- 세그먼트 트리
---
-  * 주의: 0일 때 곱을 주의, 초기값을 1로 초기화, Mod 연산 수행 잘하기
- 값을 변경하고 구간 곱을 다시 구해줄 함수 changeTree()에서 부모노드로 이동하여 자식 노드의 값을 더해주었다. 세그먼트 트리 알고리즘을 사용하여 구간 더하기, 최소, 곱셈을 구할 때 각각 로직이 다르므로 충분한 이해 필요
- findMulti 그냥 올라가며 곱해줌 
- 순서: 트리 값 1로 초기화 -> 트리에 수 넣기 -> 트리를 곱셈으로 정렬(setMultiTree) -> a값이 1일 때는  changeTree, a 값이 2일 때는 findMulti 
---
> 백준11505번구간곱구하기(세그먼트트리)

- jiWoo/백준_11505번_구간곱구하기.java
- jiWoo/백준_14226번_이모티콘.java
- [백준 14226번 이모티콘](https://www.acmicpc.net/problem/14226)
---
- BFS
- 걸리는 최소를 찾을 땐 BFS 사용
- BFS를 사용하고, check로 확인하여 방문 안했을 때 큐에 넣어준다
- now[3]-> now[0]: 화면, now[1]: 클립보드, now[2]: 시간
- 1) 삭제: 화면이  >2 일 때
- 2) 복사: 화면의 값과 클립보드의 값이 다를 때
- 3) 붙여넣기: 화면의 값+ 클립보드의 값 <= 1000일 때 정답은 1000이하이므로  -------> 생각해보니 화면의 값+ 클립보드 값 어차피 방문해서 조건에 안넣어줘도 됨!!!!!!!
---
> 백준14226이모티콘(bfs)

- taehyeong/programmers-제일 작은 수 제거하기.js
[제일 작은 수 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12935)
---
배열
---
배열안에 최솟값을 제거하고 리턴합니다.
단, 빈 배열일 경우는 -1을 리턴합니다.
풀이 방법)
1. 가장 큰 수를 변수에 지정하고 반복문으로 배열 안의 최솟값을 구합니다.
2. 해당하는 배열의 최솟값의 인덱스를 구하여 제거해줍니다.
3. 빈 배열인지 아닌지 조건식을 만들어 빈 배열일 경우는 -1을 푸시해주고 빈 배열이 아닐 경우는 해당 배열을 그대로 푸시해줍니다.
> ✨프로그래머스 제일 작은 수 제거하기

- hyeonwoo/백준 1764 듣보잡.py
- [백준 1764 듣보잡](https://www.acmicpc.net/problem/1764)
---
- 자료 구조
- 문자열
- 정렬
---
- 듣도 못한 사람과 보도 못한 사람을 각각 `set` 자료형에 담은 후, 두 집합의 교집합을 통해 듣보잡을 구했다.
- 듣보잡을 구한 후, 정렬 메서드를 통해 사전순으로 정렬하였다.
---
> 백준 1764 듣보잡

- Cobluesky/Programmers - 최댓값과 최솟값
https://school.programmers.co.kr/learn/courses/30/lessons/12939?language=javascript
Programmers - 최댓값과 최솟값
---
JS에서는 문자열에서 min, max를 사용할 수 없기 때문에 우선 배열로 바꿨습니다.
그 후에 구조 분해 할당을 이용해 min과 max를 구했습니다.
---
- 주석을 참조해주세요.
---
> 2022-11-28 Programmers - 최댓값과 최솟값 (JS)

- taehyeong/programmers-부족한 금액 계산하기.js
[부족한 금액 계산하기](https://school.programmers.co.kr/learn/courses/30/lessons/82612)
---
정수
---
1) 놀이기구 이용 금액을 반복문을 이용하여 구해줍니다.
2) 내가 갖고 있는 금액과 이용금액에 따라 결과값을 도출하기 위해 조건식을 만들어줍니다.
---
> ✨프로그래머스 부족한 금액 계산하기

- byeongjoo/백준 1926 그림.py
- [백준 1926번 그림] (https://www.acmicpc.net/problem/1926)
---
BFS
---
BFS 구현 문제.
조건 - 그림 개수 세기, 그림 넓이 중 제일 넓은 것을 출력.
그림 수를 세기 위해 조건식으로 현재 보드 위치가 0이거나 이미 방문처리된 것은 continue 로 넘기고, 보드 위치가 1이면서 방문처리가 되지 않을 것을 시작점으로 잡았다. <- 여기서 그림 개수를 셀 수 있었다.
bfs queue 방문처리하기 전에 그림 넓이(area)를 0으로 매번 초기화를 하고, while 이 도는 동안 방문을 하게 되므로 여기서 area를 1씩 가산해주었다.
최대 그림 넓이를 출력하는 것이 조건이기에 while을 다 돌아 queue가 다 빈 후, maxDraw = max(maxDraw, area)를 통해 계속해서 maxDraw를 계산해주었다.
---
> 백준 1926번 그림

- hyeonwoo/백준 11866 요세푸스 문제 0.py
- [백준 11866 요세푸스 문제 0](https://www.acmicpc.net/problem/11866)
---
- 자료 구조
- 큐
---
- 반복문 안에서 `queue` 자료 구조를 이용하여 `popleft()`한 숫자를 `queue`의 맨 뒤에 다시 추가시키고, `k의 배수`번째에는 `popleft()`만 하여 `queue`가 다 비워질때까지 반복문을 수행한다. 
---
> 백준 11866 요세푸스 문제 0

- sollyj/Baekjoon_1874_스택수열.java
- [백준 1874번 스택수열](https://www.acmicpc.net/problem/1874)
---
- 스택
---
- 스택의 push, pop을 이용한 문제다.
- 수열값들을 넣은 배열(arr)을 만들고
- 현재 수열값과 push할 값(p)의 비교를 통해 푼다.
---
> Baekjoon_1874_스택수열

- Cobluesky/Programmers - Jaden Case 문자열 만들기.js
https://school.programmers.co.kr/learn/courses/30/lessons/12951
Programmers - Jaden Case 문자열 만들기
---
정규표현식을 사용했습니다.
---
- 주석을 참조해주세요.
---
> 2022-11-29 Programmers - Jaden Case 문자열 만들기 (JS)

- taehyeong/programmers-내적.js
[내적](https://school.programmers.co.kr/learn/courses/30/lessons/70128)
---
배열
---
방법1) for 반복문을 이용하여 내적을 구하였습니다.
방법2) reduce 배열 메서드를 이용하여 내적을 구하였습니다.
[reduce 사용방법](https://velog.io/@spdhsrnvl123/JavaScript-Method-reduce-%EC%82%AC%EC%9A%A9%EB%B0%A9%EB%B2%95)
---
> 📝 프로그래머스 내적

- jiWoo/백준_1141번_접두사.java
- [백준_1141번_접두사](https://www.acmicpc.net/problem/1141)
---
- 우선순위큐
--- 
- 단어의 길이가 짧은 순으로 우선순위큐를 사용하여 정렬해줘서 접두어가 아닌 것들 더해줬는데 솔직히 이해안됨 바보임
---
> 백준_1141번_접두사

- kkkwp/프로그래머스 짝지어 제거하기.py
- [프로그래머스 짝지어 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12973)
---
- 스택
---
- 스택으로 사용하기 위한 빈 list를 만든다.
- 문자열 s를 순회하면서 스택의 top과 이번 문자 ch를 비교한다.
-  1. 빈 스택인 경우 → 일단 문자열 넣기
-  2. 이번 문자 ch와 스택의 top이 같은 경우 → 스택의 top을 pop하고 지나가기
-  3. 이번 문자 ch와 스택의 top이 다른 경우 → 문자열 넣기
- 스택이 비어있으면 1, 아니면 0 반환하기
---
> 프로그래머스 짝지어 제거하기

- sollyj/Baekjoon_17298_오큰수.java
- [백준 17298번 오큰수](https://www.acmicpc.net/problem/17298)
---
- 스택
---
- 스택에 현재 오큰수를 찾고자 하는 값의 인덱스를 넣어주고 for문으로 오른쪽 값들을 비교하면서 오큰수를 찾는것이 포인트
- 오큰수를 만족하는 수를 찾으면 ans[pop한 인덱스] = arr[i]를 하고
- 다음 값으로 넘어가기위해 push해준다.
---
> Baekjoon_17298_오큰수

- hyeonwoo/백준 10773 제로.py
- hyeonwoo/백준 1259 팰린드롬수.py
- [백준 10773 제로](https://www.acmicpc.net/problem/10773)
---
- 자료 구조
- 스택
---
- 문제가 LIFO 연산을 요구하기 때문에 스택을 이용해 구현하였다.
---
> 백준 10773 제로

- sollyj/Baekjoon_11899_괄호.java
- sollyj/Baekjoon_17298_오큰수.java
- [백준 11899번 괄호](https://www.acmicpc.net/problem/11899)
---
- 스택
---
- 주석참고
---
> Baekjoon_11899_괄호

- Cobluesky/Programmers - 최솟값 구하기
https://school.programmers.co.kr/learn/courses/30/lessons/12941?language=javascript
Programmers - 최솟값 구하기 (JS)
---
어떻게 해야 최솟값을 구할 수 있을지 생각해보면 됩니다.
차근차근 계산해보면, 둘 중 하나가 내림차순이고 나머지가 오름차순일 때 같은 인덱스끼리 곱하고 더하면 항상 최소가 나온다는 것을 알 수 있습니다.
---
- 주석을 참조해주세요.
---
> 2022-11-30 Programmers - 최솟값 구하기 (JS)

- kkkwp/프로그래머스 N개의 최소공배수.py
- [프로그래머스 N개의 최소공배수](https://school.programmers.co.kr/learn/courses/30/lessons/12953)
---
- 유클리드 호제법, 재귀
---
- 최소공배수를 구하기 위해 유클리드 호제법을 구현한다!
- 1. 최대공약수 gcd → 재귀를 이용해서 유클리드 호제법 구현
- 2. 최소공배수 lcm → gcd를 이용해서 최소공배수를 구한다.
- 유클리드 호제법은 a >b에서 성립하기 때문에 내림차순으로 sort 하고 시작
- 다른 사람의 풀이를 보니...  <code>from fractions import gcd</code>로 바로 gcd를 구할 수 있었다 🙄
---
> 프로그래머스 N개의 최소공배수

- soojik/문자열_밀기/Main.java
- [프로그래머스 문자열 밀기](https://school.programmers.co.kr/learn/courses/30/lessons/120921)
---
- 문자열
---
- 주어진 A 문자열이 hello라면, hello -> ohell -> lohel 과 같이 돌면서 B와 같은 문자열이 되면 얼만큼 돌았는지, 끝까지 같아지지 않으면 -1을 출력하는 문제
1. 먼저 A와 B가 같을 수 있으므로, 같은지 먼저 비교
2. A에 A의 마지막 문자 + A의 처음부터, 마지막 문자 전까지를 합친 문자열 삽입
3. 검사는 A 길이만큼만 돌려보면 되므로 A.length() 만큼 반복문 돌며 cnt 변수에 몇번 돌았는지 저장
4. 반복문 돌던 중 A와 B가 같다면 반복문 중단
5. 만약 반복문 끝까지 돌아 A의 문자열 길이만큼 돌았다면 못찾은것이므로 -1, 아니라면 cnt을 answer 에 넣어준다.
---
> 프로그래머스 문자열 밀기

- sollyj/Baekjoon_11286_절댓값힙.java
- [백준 11286번 절댓값힙](https://www.acmicpc.net/problem/11286)
---
- 우선순위 큐
- 들어간 순서와 상관없이 정해진 조건에 따라 우선순위가 더 높은 데이터가 먼저 나오는 자료구조
---
- 우선순위 큐의 우선순위를 주어진 조건에 따라 정해줘야 한다.
- 만약 둘의 절댓값이 같으면 더 작은값 즉 음수를 return하고
- 둘이 다르다면 절댓값이 더 작은 값을 return한다.
- 우선순위 큐만 잘 구현했다면 입력받은값이 0이나 아니냐에 따라 add 또는 poll해주면 된다.
---
> Baekjoon_11286_절댓값힙

- hyeonwoo/백준 1874 스택 수열.py
- [백준 1874 스택 수열](https://www.acmicpc.net/problem/1874)
---
- 자료 구조
- 스택
- 큐
---
- 수열의 처음과 `스택`의 마지막이 같으면 `스택`에 `pop` 연산을 수행
이 때, `스택`에 마지막을 `pop`하면서 수열의 처음도 `pop` 연산을 수행해서 수열의 다음 수를 계속 비교할 수 있게 구현했다. 이를 위해, 입력 받을 수열은 `큐` 자료 구조 형태로 저장했다.
- 수열의 처음과 스택의 마지막이 다르면 스택에 `i`를 `push`하도록 했다.
---
> 백준 1874 스택 수열

- taehyeong/programmers-문자열 내림차순으로 배치하기.js
[문자열 내림차순으로 배치하기](https://school.programmers.co.kr/learn/courses/30/lessons/12917)
---
문자열
---
문자열을 split메소드를 사용하여 배열로 쪼갠다.
예: ['Z', 'b', 'c', 'd', 'e', 'f', 'g']
sort메소드로 순차적으로 나열해준다.
예: ["Z", "b", "c", "d", "e", "f", "g"]
reverse메소드로 반전시켜준다.
예: ["g", "f", "e", "d", "c", "b", "Z"]
join메소드로 문자열로 바꿔줘서 반환한다.
예: "gfedcbZ"
---
> 📝프로그래머스 문자열 내림차순으로 배치하기

- Cobluesky/Programmers - x개 만큼 간격이 있는 n개의 문자.js
- Cobluesky/Programmers - 올바른 괄호.js
https://school.programmers.co.kr/learn/courses/30/lessons/12909?language=javascript#
Programmers - 올바른 괄호 (JS)
---
Stack을 이용해서 해결했습니다.
시간복잡도 문제 해결을 위해 조건을 추가해 조건을 걸러냈습니다.
---
- 주석을 참조해주세요.
---
> 2022-12-01 Programmers - 올바른 괄호 (JS)

- taehyeong/programmers-문자열 다루기 기본.js
- taehyeong/programmers-직사각형 별찍기.js
[문자열 다루기 기본](https://school.programmers.co.kr/learn/courses/30/lessons/12918)
---
문자열
---
문제에서 문자열 s의 길이가 4혹은 6이라는걸 명시해주었지만 4~6 사이로 생각하여 테스트케이스에서 계속 오류가 발생하였습니다. 
먼저 문자열 s길이가 조건식 안에 논리연산자를 활용하여 4 또는 6이 아니면 바로 함수를 종료시키는 코드를 작성합니다.
그리고 반복문 내에서 isNaN 메서드를 활용하여 해결하였습니다.
> isNaN()
매개변수가 숫자가 아닐 경우 true를 리턴하고,
콤마 안에 숫자가 있어도 숫자일 경우 false를 리턴합니다.
---
> 📝프로그래머스 문자열 다루기 기본

- kkkwp/프로그래머스 점프와 순간 이동.py
- [프로그래머스 점프와 순간 이동](https://school.programmers.co.kr/learn/courses/30/lessons/12980)
---
- 구현
---
-  n칸을 2로 나누는 것을 반복한다!
- 1. 짝수라면 그대로 2로 나눈다.
- 2. 홀수라면 건전지 사용량 + 1을 하고, n을 2로 나눈 몫만 취해서 짝수로 만들어준다.
- n = 0이 될 때까지 이 과정을 반복하면 끝
<br>
- 다른 사람의 풀이를 보니, 이진법을 이용하는 방법도 있었다. n을 이진법으로 바꿔서 1의 개수를 구하면 끝~
- 짝수와 홀수를 이용하는 문제는 이진법을 떠올려보기...!
---
> 프로그래머스 점프와 순간 이동

- soojik/programmers/.vscode/settings.json
- soojik/programmers/README.md
- soojik/programmers/src/문자열_밀기/Main.java
- soojik/programmers/src/숫자짝꿍/Main.java
- soojik/programmers/src/피자나눠먹기_3/Main.java
- [피자 나눠 먹기 (3)](https://school.programmers.co.kr/learn/courses/30/lessons/120816)
- [숫자 짝꿍](https://school.programmers.co.kr/learn/courses/30/lessons/131128)
---
- 문자열
---
- 주석 참고
---
> 프로그래머스 피자나눠먹기3, 숫자짝꿍

- hyeonwoo/백준 2805 나무 자르기.py
- [백준 2805 나무 자르기](https://www.acmicpc.net/problem/2805)
---
- 이진 탐색
- 매개변수 탐색
---
- 조건을 만족하는 최대값을 구하기 위해 **매개변수 탐색**을 이용했다. 매개변수 탐색은 내부적으로 이진 탐색을 사용한다.
- 문제는 최소 `m`미터의 나무를 가져가야 하는 조건을 만족하는 절단기의 최대 높이를 요구하고 있다.
- ***나무를 무조건 가져갈 수 있는*** 절단기의 최소 높이는 0이다.
- ***나무를 무조건 가져갈 수 없는*** 절단기의 최대 높이는 주어진 나무들 중 최대 높이를 가진 나무이다.
- ***나무를 무조건 가져갈 수 있는 값***을 `start` 변수에 대입하고, ***나무를 무조건 가져갈 수 없는 값***을 `end` 변수에 대입한다.
- 여기서 **이진 탐색** 알고리즘을 이용하여 `start`와 `end`의 범위를 절반씩 좁혀가며, `mid`값(*절단기의 높이*)이 나무를 가져갈 수 있는지 확인한다.
- 절단기의 높이가 나무를 가져갈 수 있으면, `start` 변수에 절단기의 높이를 대입하여 범위를 줄이고, 절단기의 높이가 나무를 가져갈 수 없으면,  `end` 변수에 절단기의 높이를 대입하고, 반복문 조건(`start + 1 < end`)에 따라 반복문이 종료된다.
- 나무를 가져갈 수 있는지 없는지 여부는 `def check_tree(cutter_height)` 함수로 확인하였다.
- `check_tree` 함수에 절단기의 높이(`mid`)를 대입하면, 입력 받은 나무들에서 절단기 높이를 뺀 값들 중 양수인 값들의 합이 …
> 백준 2805 나무 자르기

- sollyj/Baekjoon_1026_보물.java
- sollyj/Baekjoon_1614_영식이의손가락.java
- sollyj/Baekjoon_2164_카드2.java
- [백준 2164번 카드2](https://www.acmicpc.net/problem/2164)
---
- 큐
---
- 큐 사이즈가 2이상이면 poll과 poll&add를 반복해주면된다.
- 큐 사이즈가 1이면 그 값이 결과값
---
> Baekjoon_2164_카드2

- sollyj/Baekjoon_10989_수정렬3.java
- [백준 10989번 수정렬3](https://www.acmicpc.net/problem/10989)
---
- 정렬
---
- 자바 내장함수인 sort를 이용해도 되지만 카운팅정렬 알고리즘을 써보았다.
- 배열cnt 인덱스에 정렬할 값들을 넣는 것이다. 그리고 카운트를 센다.
- cnt의 값이 1이상인 원소의 인덱스를 출력하면 자동으로 오름차순 정렬이 된다. 
---
> Baekjoon_10989_수정렬3

- sollyj/Baekjoon_2750_수정렬.java
- [백준 2750번 수정렬](https://www.acmicpc.net/problem/2750)
---
- 정렬(버블정렬)
---
- 버블 정렬은 인접한 숫자와 비교하면서 순차적으로 swap하며 정렬을 해나간다.
- 정렬 되지 않은 숫자들을 순회하는 반복문, swap하는 반복문 총 2중 반복문
- 만약 swap을 한번도 안했다면 정렬이 다 됐단 뜻이므로 반복문을 끝낸다.
---
> Baekjoon_2750_수정렬

- soojik/programmers/src/영어가_싫어요/Main.java
- [프로그래머스 영어가 싫어요](https://school.programmers.co.kr/learn/courses/30/lessons/120894)
---
- 문자열
---
- eng 라는 크기가 10인 String 배열을 만들어, 각 0~9자리에 zero 부터 nine, 숫자 영문을 넣어준다.
static String[] eng = {"zero", ..., "nine"};
- 주이진 numbers 문자열이 크기가 최대 50이라고 했으니, 총 50자리가 들어갈 수 있는 크기가 0~50인 record_num_index[i] 를 만들어 -1로 초기화해주었다.
recored_num_index 배열에는 eng 배열을 돌며 numbers에서 indexOf로 찾은, eng[i]가 있는 위치, 그 위치에 i 값을 넣어줄 것이다.
- 0부터 9 까지의 숫자 (i) 를, 매번 numbers 처음부터 끝까지 indexOf(eng[i], 탐색 시작 위치) 함수를 이용해 i가 있는 모든 시작 위치를 record_num_index에 넣어준다.
찾았다면 다음 탐색 시작 위치 idx를 찾아놓은 위치 바로 뒤, idx_of_num + 1 로 설정해준 후, 반복문 수행
- 문자열 탐색이 끝나면 찾은 숫자가 순서대로 들어가있을 record_num_index 배열을 돌며 i가 0 이상이라면 StringBuilder 에 append해주고, long 타입으로 리턴해야하므로 Long.parseLong() 메서드 이용해 답을 반환해준다.
---
> 프로그래머스 영어가 싫어요

- kkkwp/프로그래머스 [1차] 캐시.py
- [프로그래머스 [1차] 캐시](https://school.programmers.co.kr/learn/courses/30/lessons/17680)
---
- 구현
---
문제에 있는 캐시 교체 알고리즘 LRU(Least Recently Used)를 구현하면 되는 문제다.
우선 도시의 대소문자를 구분하지 않으므로 lower()를 이용헤사 모두 소문자로 만들어줬다.
1.  cache 사이즈가 0인 경우
* 항상 cache miss이므로 (배열 cities의 길이) * (miss일 때의 실행시간)
<br>
2.  city가 cache에 없는 경우
* cache miss이므로 miss 횟수를 +1 한다.
* city를 cache 맨 뒤에 넣는다.
* 넣으려고 봤는데 cache가 이미 꽉 차있는 경우, cache의 맨 앞을 pop하고 나서 맨 뒤에 넣어준다.
* cache가 비어 있는 경우도 포함한다.
<br>
3. city가 cache에 있는 경우
* cache hit이므로 hit 횟수를 +1 한다.
* city를 cache에서 제거하고, 맨 뒤로 넣어준다.
<br>
(miss 횟수) * (miss일 때의 실행시간) + (hit 횟수) * (hit일 때의 실행시간)을 구해서 리턴하면 끝
---
> 프로그래머스 [1차] 캐시

- jiWoo/백준_15989번_123더하기4.java
- [백준 15989번 1, 2, 3 더하기 4](https://www.acmicpc.net/problem/15989)
---
- 다이나믹 알고리즘
---
- 다이나믹 알고리즘을 사용하여
- 1로 모든 수를 만들 수 있으므로 처음에 D[] 배열에 모두 1로 초기화
- 2는 D[2]~D[10000]까지  D[i]=D[i-2]+D[i] 2를 하나 추가했을 때와 안 했을 때를 더해줌
- 3도 2와 마찬가지로 D[i]=D[i-3]+D[i] 
---
> 백준_123더하기4(다이나믹알고리즘)

- kkkwp/프로그래머스 옹알이 (2).py
- [프로그래머스 옹알이 (2)](https://school.programmers.co.kr/learn/courses/30/lessons/133499)
---
- 구현(문자열 처리)
---
- 배열 babbling을 돌면서, 원소 babble 하나하나를 처리한다.
- babble에 조카가 발음 가능한 단어 중 하나(word)가 있으면 replace를 이용하여 처리한다. 이때 연속해서 같은 발음을 하는 것은 어려워하므로 word * 2가 babble에 있으면 안 된다!
- babble에서 모든 word를 처리하고 나서 babble의 길이가 0, 즉 남는 알파벳이 없으면 성공적으로 발음을 잘 한 것이므로 answer +1을 한다.
-  strip() 함수는 문자열 앞/뒤의 공백을 제거해주는 함수이다.
---
> 프로그래머스 옹알이 (2)

- taehyeong/programmers-최대값과 최솟값.js
[최대값과 최솟값](https://school.programmers.co.kr/learn/courses/30/lessons/12939)
---
배열
---
문자열을 split()메서드로 배열로 변형시켜 준 다음에 Math객체를 이용하면 간단하게 해결할 수 있습니다.
---
> 📝프로그래머스 최대값과 최솟값

- Cobluesky/Programmers - 나머지가 1이 되는 수 찾기.js
//https://school.programmers.co.kr/learn/courses/30/lessons/87389
Programmers - 나머지가 1이 되는 수 찾기 (JS)
---
뭐 별다를 게 없네요.
최악의 경우에도 시간복잡도는 통과합니다.
---
---
> 2022-12-03 Programmers - 나머지가 1이 되는 수 찾기 (JS)

- hyeonwoo/백준 1269 대칭 차집합.py
- [백준 1269 대칭 차집합](https://www.acmicpc.net/problem/1269)
---
- 자료 구조
---
- 대칭 차집합은 XOR 연산과 같다.
- ***XOR : 서로 같으면 거짓, 서로 다르면 참***
- 파이썬의 XOR 연산자인 `^` 를 사용하거나 `set.symmetric_difference` 메서드를 사용해 대칭 차집합을 구할 수 있다.
---
> 백준 1269 대칭 차집합

- kkkwp/프로그래머스 명예의 전당 (1).py
- [프로그래머스 명예의 전당 (1)](https://school.programmers.co.kr/learn/courses/30/lessons/138477)
---
- 배열
---
- 명예의 전당 리스트(hall)를 하나 만들고, score를 돌면서 점수를 비교하여 명예의 전당에 넣거나 뺀다.
- hall의 길이를 k와 비교하여 hall의 크기가 최대 k를 유지할 수 있도록 한다.
- 1. 일단 점수 s를 hall에 넣기
- 2. hall의 길이가 k보다 작거나 같은 경우 : hall의 최솟값을 answer에 넣기
- 3. hall의 길이가 k보다 큰 경우 : hall의 최솟값을 제거하여 길이를 k개로 맞춘 후, hall의 최솟값을 answer에 넣기
---
> 프로그래머스 명예의 전당 (1)

- byeongjoo/백준 18870 좌표 압축.py
[백준 18870번 좌표 압축] (https://www.acmicpc.net/problem/18870)
---
이분탐색.
(브루트포스로도 가능하다고 생각함.)
---
좌표 압축 및 이분탐색을 사용하기 위해 set()을 통해 리스트 내에서 같은 데이터들을 압축을 시켜주었으며, sorted()를 사용하여 원본데이터 xList의 리스트들은 살려놓고, targetList 는 xList의 값들을 정렬한 상태로 받아왔다.
파이썬의 이분탐색 모듈인 bisect_left를 이용하여 xList의 i 값을 targetList 에 좌측에서 몇 번째에 위치해있는지 찾아주었다.
그 후 정답을 출력할 배열인 ans에 값을 추가해주어, 마지막에 출력을 통해 뽑아주었다.
---
> 백준 18870 좌표 압축

- taehyeong/programmers-최대값과 최솟값.js
[최대값과 최솟값](https://school.programmers.co.kr/learn/courses/30/lessons/12939)
---
문자열,배열
---
문제에서 주어진 해당 문자열을 split()메서드를 이용하여 배열로 변형시켜 준 다음에 Math객체를 이용하여 해결하였습니다.
[split()메서드 사용법](https://velog.io/@spdhsrnvl123/JavaScript-Method-split-%EC%82%AC%EC%9A%A9%EB%B0%A9%EB%B2%95)
배열에서 Math객체 사용방법
```js
const array = [1,2,3];
console.log(Math.max(...array)); //3
//spread oprator를 활용하면 됩니다.
```
---
> 🚑프로그래머스 최대값과 최솟값 수정

- sollyj/Baekjoon_1427_소트인사이드.java
- [백준 1427번 소트인사이드](https://www.acmicpc.net/problem/1427)
---
- 정렬(선택정렬)
- 최솟값 또는 최댓값을 찾고 남은 정렬 부분의 가장 앞에 있는 데이터와 swap
---
- 여기서는 내림차순을 해야하므로 최댓값을 찾고 남은 정렬 부분에서 제일 앞 값과 최댓값을 swap한다.
---
> Baekjoon_1427_소트인사이드

- sollyj/Baekjoon_11399_ATM.java
- [백준 11399번 ATM](https://www.acmicpc.net/problem/11399)
---
- 정렬 (삽입정렬)
- 선택 데이터를 정렬된 데이터 범위 내에서 적절한 위치에 삽입
---
- insert_value가 P[i]일때 i-1까지의 정렬된 데이터 범위내에서 insert_point를 찾는다.
- insert_point를 찾았으면
- insert_point전까지 데이터들을 밀고 P[j] = P[j-1];
- P[insert_point] = insert_value
---
> Baekjoon_11399_ATM

- jiWoo/백준_12865번_평범한배낭.java
- [백준 12865번 평범한 배낭](https://www.acmicpc.net/problem/12865)
---
- 다이나믹 프로그래밍
---
- 다이나믹 프로그래밍 알고리즘을 사용한다.
- D[i][K] : K 무게까지 가능한 i 물건을 넣었을 때 최대 가치
- 1) 현재 물건의 무게가 j보다 크면 D[i][j]=D[i-1][j] // 현재 물건을 넣기 전에 최대 가치
- 2) 현재 물건의 무게가 j 이상이면 D[i][j]= Math.max(D[i-1][j], D[i-1][j-W]+V) // 현재 물건을 넣기 전의 값과 현재 물건을 넣었을 때(현재 물건의 무게를 뺀 전 값)+ 현재 가치를 더한 값 중 큰 값
---
> 백준_평범한배낭_다이나믹프로그래밍

- sollyj/Baekjoon_11004_K번째수.java
- [백준 11004번 K번째수](https://www.acmicpc.net/problem/11004)
---
- 정렬 (퀵정렬)
---
- 퀵정렬은 기준값(pivot)을 기준으로 작은값과 큰값으로 분류하는 것을 반복해 정렬하는 알고리즘이다.
- 총 3개의 함수를 만들었다.
1. 최종적으로 구하려는 k에 따라 퀵정렬을 수행하는 함수 quick
2. 기준값을 기준으로 작은값과 큰값을 분류하는 함수 partition
3. swap하는 함수 swap
- 
---
> Baekjoon_11004_K번째수

- kkkwp/백준 1439번 뒤집기.py
- [백준 1439번 뒤집기](https://www.acmicpc.net/problem/1439)
---
- 문자열, 그리디
---
- 0000111000은 010과 같다.
- cnt는 문자열을 돌면서 바뀌는 지점을 만날 때의 횟수이다. 
- 0에서 1로 바뀌는 횟수와 1에서 0으로 바뀌는 횟수의 차이는 무조건 1이다. 따라서 cnt + 1을 구하고 이를 2로 나눈 몫이 답이 된다.
---
> 백준 1439번 뒤집기

- soojik/programmers/src/푸드파이트_대회/Main.java
- [프로그래머스 푸드 파이트 대회](https://school.programmers.co.kr/learn/courses/30/lessons/134240)
---
- 문자열
---
- 주석 참고
---
> 프로그래머스 푸드 파이트 대회

- hyeonwoo/백준 10026 적록색약.py
- [백준 10026 적록색약](https://www.acmicpc.net/problem/10026)
---
- BFS
---
- 적록색약이 아닌 경우를 먼저 구하고, `R`을 `G`로 바꾸어 적록색약인 경우를 추가로 구한다.
- BFS를 이용하여 입력받은 색 좌표 각각에 대해 상화좌우를 탐색하여 같은 색상이면 방문 처리하여 영역의 개수를 구한다.
- 적록색약이 아닌 경우를 BFS를 이용하여 구한 뒤, 방문했던 좌표를 초기화 해준 뒤에 적록색약인 경우를 구한다.
---
> 백준 10026 적록색약

- sollyj/Baekjoon_2751_수정렬2.java
- [백준 2751번 수정렬2](https://www.acmicpc.net/problem/2751)
---
- 정렬(병합 정렬)
(..를 썼는데 시간 초과가 나서 내장 함수이용함)
- 병합 정렬(Merge Sort)
- 데이터를 분할 하고 분할한 집합을 정렬하며 합치는 알고리즘
---
- 집합을 나누는 함수 mergeSort()와
- 분할한 집합을 가지고 정렬하며 합치는 함수 merge()
- merge함수를 보면, mid를 기준으로 분할한 두집합의 원소를 순회하며 더 작은 값을 temp(임시 배열)에 넣었다.
- 정렬이 끝난 후 temp에 넣었던 것을 원래 배열인 array에 넣었다.
- **혹시 병합정렬 써서 시간 초과 안나게 푸는 방법 아는분...?**
---
> Baekjoon_2751_수정렬2

- sollyj/Baekjoon_1377_버블소트.java
- [백준 1377번 버블소트](https://www.acmicpc.net/problem/1377)
---
- 정렬 (버블정렬)
---
- 일반적인 버블소트 알고리즘으로 풀면 시간초과
- 궁극적으로 구해야하는 값은 **정렬이 완료 되기 까지 안쪽 for문 돌린 횟수**이다.
- 버블소트의 원리를 보면 안쪽 for문(인접한 원소끼리 비교하는 for문)을 통해 swap을 하게되는데 이 때 swap은 왼쪽으로 한번만 한다.
- 즉, **for문을 한번 돌릴 때** 마다 **왼쪽으로 swap 한번** 한다는 뜻
- 따라서 정렬이 완료 되었을때 (정렬 전 인덱스 - 정렬 후 인덱스)의 최댓값을 찾는 것이 이 문제의 포인트
---
> Baekjoon_1377_버블소트

- kkkwp/백준 7568번 덩치.py
- [백준 7568번 덩치](https://www.acmicpc.net/problem/7568)
---
- 완전탐색
---
- 사람들의 몸무게 x, 키 y를 입력 받아 배열 people에 저장한다.
- 배열 people을 돌면서, 몸무게와 키 모두 큰 사람을 찾으면 rank가 밀려난다.
---
> 백준 7568번 덩치

- dongkiid/백준 10869 사칙연산.java
- [백준 10869 사칙연산](https://www.acmicpc.net/problem/10869)
---
> 백준 10869 사칙연산

- soojik/programmers/src/컨트롤제트/Main.java
- [프로그래머스 컨트롤 제트](https://school.programmers.co.kr/learn/courses/30/lessons/120853)
---
- 문자열, 배열
---
- 주석 참고
---
> 프로그래머스 컨트롤제트

- soojik/programmers/src/과일장수/Main.java
- [프로그래머스 과일 장수](https://school.programmers.co.kr/learn/courses/30/lessons/135808)
---
- 정렬
---
- 주석 참고
---
> 프로그래머스 과일 장수

- hyeonwoo/백준 4949 균형잡힌 세상.py
- [백준 4949 균형잡힌 세상](https://www.acmicpc.net/problem/4949)
---
- 자료 구조
- 문자열
- 스택
---
- 입력받은 문자열의 길이만큼 반복문을 돌려 소괄호와 대괄호인 경우만 `target` 배열에 추가한다.
- `target` 배열을 순회하며 요소가 여는 괄호(`"[", "("`)이면 스택에 추가한다.
- 요소가 닫는 괄호(`"]", ")"`)일 때, 스택의 마지막과 짝을 이룰 경우 `pop()` 연산을 통해 짝을 지워준다.
- 이때, 짝을 이루지 못한다면 스택에 요소를 추가한다.
- `target` 배열의 순회를 마치고 난 후
- 스택이 비어있으면 균형 잡힌 문자열로 간주
- 스택이 비어있지 않다면 불균형한 문자열로 간주
- ***괄호가 하나도 없는 경우는 균형 잡힌 문자열로 간주***
---
- **Q1**
- 입력받은 문자열을 정규표현식 등을 이용해 괄호만 남길 수 있는 방법이 있을까요?
> 백준 4949 균형잡힌 세상

- Cobluesky/Programmers - 숫자의 표현.js
- Cobluesky/Programmers - 콜라츠 추측.js
//https://school.programmers.co.kr/learn/courses/30/lessons/12924
Programmers - 숫자의 표현
---
- 약수의 성질입니다.
특정 수의 연속 수의 합의 가짓수는 해당 수의 약수 중 홀수의 개수와 같습니다.
---
- 주석을 참조해주세요.
수학적 풀이를 알고있다면 쉬운문제지만, 아닐경우 굉장히 먼 길을 돌아가야합니다.
---
> 2022-12-06 Programmers - 숫자의 표현 (JS)

- taehyeong/programmers-외계행성의 나이.js
[외계행성의 나이](https://school.programmers.co.kr/learn/courses/30/lessons/120834)
---
배열
---
주어진 숫자값을 스트링 형태의 배열로 생성합니다. 
그리고 반복문으로 알파벳 배열의 인덱스 값으로 접근하여 해결하면 됩니다.
---
> 📝프로그래머스 외계행성의 나이

- dongkiid/프로그래머스) 피자 나눠먹기(1)
- [프로그래머스 피자나눠먹기][(https://www.acmicpc.net/problem/2493)](https://school.programmers.co.kr/learn/courses/30/lessons/120814?language=python3)
---
처음에는 7로 나누는 것에 집중해 if문을 통해 나머지가 0이면 n, 나머지가 0이 아니면 n+1을 출력하는 코드를 작성하다가
파이썬의 math 모듈에 ceil(올림) 기능을 발견하여 사용해 다시 코드를 작성했다.
(ceil기능을 쓰려면 모듈이라 import를 해주어야 한다.)
> 프로그래머스) 피자나눠먹기(1)

- kkkwp/백준 11047번 동전 0.py
- [백준 11047번 동전 0](https://www.acmicpc.net/problem/11047)
---
- 그리디
---
- 가치가 큰 동전이 가치가 작은 동전의 배수이기 때문에 그리디로 해결할 수 있는 문제다!
- 가치가 큰 금액의 동전부터 최대한 많~~이 바꿔주면 그게 바로 필요한 동전 개수의 최솟값이다.
- 따라서 입력 받은 coin을 내림차순으로 정렬한 뒤 큰 금액의 동전부터 바꿔나가면 된다. 
---
> 백준 11047번 동전 0

- kkkwp/백준 1931번 회의실 배정.py
- [백준 1931번 회의실 배정](https://www.acmicpc.net/problem/1931)
---
- 그리디
---
- 끝나는 시각이 _빠른_ 순서대로 회의를 진행하면 가장 많은 회의를 할 수 있다. 따라서 끝나는 시각(end)을 기준으로 정렬하기
- 주의할 점은 [5, 6]과 [6, 6]이 있을 때 [5, 6]을 선택해야 [5, 6], [6, 6]으로 2개의 회의를 할 수 있다는 것이다. 따라서 시작하는 시각(start)을 기준으로도 정렬했어야 한다!
- 따라서 정렬 기준 1순위가 end, 2순위가 start
- 정렬된 배열 arr를 돌면서, 현재 하고 있는 회의가 끝나는 시각(last)보다 늦게 시작하는 회의를 만날 때 그 회의를 진행하는 방식
- 참고 : python에서 sort 기준은 한번에 여러 개를 줄 수 있다~ 우선 순위 순서대로
```
arr.sort(key=lambda x: (x[1], x[0]))
```
---
> 백준 1931번 회의실 배정

- soojik/programmers/src/삼총사/Main.java
- soojik/programmers/src/콜라문제/Main.java
- [프로그래머스 삼총사](https://school.programmers.co.kr/learn/courses/30/lessons/131705)
- [프로그래머스 콜라 문제](https://school.programmers.co.kr/learn/courses/30/lessons/132267)
---
- 삼총사 : 완전탐색
- 콜라 문제 : 단순 구현
---
- 주석 참고
---
> 프로그래머스 삼총사, 콜라문제

- Cobluesky/Programmers - 문자열 나누기.js
// https://school.programmers.co.kr/learn/courses/30/lessons/140108
Programmers - 문자열 나누기 (JS)
---
- 뭐 딱히 없습니다.
---
- 주석을 참조해주세요.
---
> Programmers - 문자열 나누기 (JS)

- jiWoo/백준_5427번_불.java
- [백준 5427번 불](https://www.acmicpc.net/problem/5427)
---
- BFS(너비 우선 탐색) 알고리즘
---
- 상근이를 먼저 큐에 넣고 그 다음 불의 위치를 큐에 넣는다. 
- 큐에는 int[3] 배열을 넣는데 [0]에는 x의 위치, [1]에는 y의 위치 [2]에는 상근이는 상근이가 움직인 거리, 불은  상근이와 비교해주기위해 -1
- BFS를 사용하여 큐에서 poll 했을 때 
- ( 불인데 [2]가 -1이 아니라면 상근이가 이후에 불이 된 것이므로 다음으로 넘어간다continue)
- 상근이라면 
- 1) 4방향을 탐색했을 때 빈칸이라면 빈칸으로 옮겨준다 
- 2) 밖이었을 때 성공이므로 [2] 상근이가 움직인 거리에 +1을 하여 추력
- 불이라면
- 1) 4방향을 탐색하여 map안에 존재하고 불과 벽이 아니라면 불로 바꿔준다. 
---
> 백준_5427번_불(BFS)

- soojik/programmers/src/가장_가까운_같은_글자/Main.java
- soojik/programmers/src/문자열_나누기/Main.java
- [프로그래머스 가장 가까운 같은 글자](https://school.programmers.co.kr/learn/courses/30/lessons/142086)
- [프로그래머스 문자열 나누기](https://school.programmers.co.kr/learn/courses/30/lessons/140108)
---
- 단순 구현, 문자열, 배열
---
- 주석 참고
---
> 프로그래머스 가장 가까운 같은 글자, 문자열 나누기

- taehyeong/programmers-시저암호.js
[시저암호](https://school.programmers.co.kr/learn/courses/30/lessons/12926)
---
문자열,배열
---
해당 문제는 알파벳 문자열에서 주어진 n(0~25)값에 따라 이동시키는 문제입니다. 예를들어 알파벳 A가 주어지고 n값이 1이 주어지면 답은 B가 나와야 됩니다. 그리고 알바벳 z가 주어지고 n값이 1이 주어지면 답은 a가 나와야 됩니다.
<해결방법>
1.문자열을 charCodeAt() 메서드를 활용하여 ASCII 코드로 변환해 줍니다.
2.변환해준 ASCII코드는 다시 문자로 변환했을 때를 고려해야 하기 때문에 대문자,소문자,공백의 조건식을 만듭니다.
3.각 조건식의 만족하는 값은 새로 만든 배열에 푸시해줍니다.
4.최종적으로 완성된 배열은 fromCharCode()메서드를 활용하여 다시 문자로 변환시켜 줍니다.
---
> 📝프로그래머스 시저암호

- taehyeong/programmers-머쓱이보다 키 큰 사람.js
[머쓱이보다 키 큰 사람](https://school.programmers.co.kr/learn/courses/30/lessons/120585)
---
배열
---
filter() 메서드를 활용하여 새로운 배열을 생성한 다음 length속성을 이용해 쉽게 해결하였습니다.
---
> 📝프로그래머스 머쓱이보다 키 큰 사람

- jiWoo/백준_2775번_부녀회장이될테야.java
- [백준 2775번 부녀회장이 될테야](https://www.acmicpc.net/problem/2775)
---
- 다이나믹 프로그래밍
---
- 점화식 사용
- D[0][i] : 0층은 i명이 살고있어서 D[0][i]=i 로 설정
- k층에 n호는 k-1층의 n호까지의 누적 합이 산다.
- k층 n호 D[k][n]=D[k-1][n]+ D[k][n-1] //  D[k-1][n] 내 윗집의 수와 D[k][n-1]  k층의 n-1호에는 k-1층의 n-1호까지의 누적이 살고있으므로
---
> 백준2775_부녀회장이될테야(DP)

- kkkwp/백준 11399번 ATM.py
- kkkwp/백준 1541번 잃어버린 괄호.py
- [백준 11399번 ATM](https://www.acmicpc.net/problem/11399)
- [백준 1541번 잃어버린 괄호](https://www.acmicpc.net/problem/1541)
---
- 그리디
---
- 앞사람의 시간은 뒤로 가면서 계속 더해진다는 점을 생각해보면, 오름차순으로 정렬하는 것이 최소 시간이 나오는 방법이다.
- 따라서 시간 배열을 오름차순으로 정렬한 뒤, 합을 구하면 끝
- '-' 다음 '+'들을 괄호로 묶어야 빼는 값이 커져서 최솟값이 나온다.
- 따라서 '-' 기준으로 문자열을 자른 뒤,  '+'를 기준으로 잘라서 나온 숫자들을 빼주면 된다.
- 이때 '-'를 기준으로 문자열을 자르면 첫번째 숫자는 양수일 수도, 음수일 수도 있어서 따로 처리해주었다.
---
> 백준 11399번 ATM, 백준 1541번 잃어버린 괄호

- sollyj/Baekjoon_2023_신기한소수.java
- [백준 2023번 신기한소수](https://www.acmicpc.net/problem/2023)
---
- 탐색(DFS)
---
- 한자리부터 시작하여 소수이면 두자리, 세자리... N자리 까지 가서 소수인 수를 출력하므로 깊이우선탐색(DFS)을 하였다.
- 하나의 DFS를 마친 후에는 다시 한자리로 돌아와야하므로 재귀함수로 구현하였다.
---
> Baekjoon_2023_신기한소수

- hyeonwoo/백준 2587 대표값2.py
- [백준 2587 대표값2](https://www.acmicpc.net/problem/2587)
---
- 수학
---
- 평균과 중앙값을 구하는 문제
---
> 백준 2587 대표값2

- kkkwp/백준 13305번 주유소.py
- [백준 13305번 주유소](https://www.acmicpc.net/problem/13305)
---
- 그리디
---
- 주유 비용이 최소일 경우에 넉넉하게 채워놓고 가는 것이 제일 이득이다!
- 따라서 길을 따라 가면서 들린 마을의 주유 비용이 최솟값인지 확인하여 값을 저장하고, 앞으로 가야 할 거리를 곱해주면 최소 비용으로 여행할 수 있다~~ 
---
> 백준 13305번 주유소

- jiWoo/백준_12026번_BOJ거리.java
- [백준 12026번 BOJ 거리](https://www.acmicpc.net/problem/12026)
---
- 다이나믹 프로그래밍(DP)
---
- B, O, J의 위치를 각각 리스트에 저장하고
- 블록을 0~n-1을 확인하며
- 1) 공통으로 
- 예를들어 B일 때 J리스트의 값 전부를 확인하는데 J의 위치가 현재 B의 값보다 뒤에 있고 현재의 값이 Int의 최대값이 아닐 때(최대값으로 처음에 저장해놔서 최대값이면 현재 전에 노드를 방문한 적이 없는 것이기 때문에- 근데 이걸 각각 확인해줬는데 한 번에 위에서 체크해주면 되겠당..ㅋㅋ) D[j의 위치]값에 D[j의위치]와 D[현재B의 위치]+ (j의 위치- B의 위치)의 제곱값 중 작은 값을 저장한다.! 
- 2) 끝에 값이 int의 최대값이면 끝까지 방문을 못했으므로 -1을 출력하고 -1이 아니라면 D[n-1]값 출력
---
> 백준_12026_BOJ거리(DP)

- kkkwp/백준 2108번 통계학.py
- [백준 2108번 통계학](https://www.acmicpc.net/problem/2108)
---
- 정렬
---
산술평균, 중앙값, 범위는 구현하기 쉬웠으나 최빈값이 까다로웠던 문제였다....😢
1. 산술평균
- 반올림은 round 함수를 이용하면 된다.
2. 중앙값
- 정렬한 뒤 딱 중앙에 있는 인덱스를 이용하면 된다.
3. 최빈값
- 개수를 세려면 Counter를 이용하면 된다! 최빈값을 구하는 문제니까 most_comon()을 이용
```
from collections import Counter
Counter(배열).most_common() # 결과는 딕셔너리
```
- 최빈값이 여러개 있을 때에는 최빈값 중 두번째로 작은 값을 출력해야 하므로 이에 대한 조건을 처리한다. 
4. 범위
- 정렬 되어 있는 배열 arr의 맨 끝이 최댓값, 맨 처음이 최솟값이므로  빼주면 된다.
---
> 백준 2108번 통계학

- sollyj/Baekjoon_1260_DFSBFS.java
- [백준 1260번 DFS와 BFS](https://www.acmicpc.net/problem/1260)
---
- 탐색 (깊이우선탐색, 너비우선탐색)
---
- DFS
깊이 우선 탐색이므로 인접 노드 중 방문 하지 않은 노드를 탐색하여(깊이 우선) 다시 DFS호출하는 재귀형태로 구현
- BFS
너비 우선 탐색이므로 인접 노드를 방문하고 가장 인접한 노드의 인접한 노드를 탐색한다.(너비 우선)
선입선출 방식이므로 queue로 구현
---
> Baekjoon_1260_DFSBFS

- dongkiid/프로그래머스) 각도기.py
- dongkiid/프로그래머스) 두 수의 나눗셈.py
- dongkiid/프로그래머스) 배열 두배 만들기.py
- [프로그래머스) 각도기]
(https://school.programmers.co.kr/learn/courses/30/lessons/120829)
- [프로그래머스) 배열 두배 만들기]
(https://school.programmers.co.kr/learn/courses/30/lessons/120809)
- [프로그래머스) 두수의 나눗셈]
(https://school.programmers.co.kr/learn/courses/30/lessons/120806)
---
> 프로그래머스) 각도기, 배열두배만들기, 두 수의 나눗셈

- Cobluesky/Programmers - 가장 가까운 수.js
//https://school.programmers.co.kr/learn/courses/30/lessons/142086
Programmers - 가장 가까운 수 (JS)
---
stack을 사용해 풀었습니다.
---
- 주석을 참조해주세요.
---
> 2022-12-12 Programmers - 가장 가까운 수 (JS)

- soojik/programmers/src/햄버거만들기/Main.java
- [프로그래머스](https://school.programmers.co.kr/learn/courses/30/lessons/133502)
---
- 스택, 리스트
---
- 주석 참고
---
> 프로그래머스 햄버거 만들기

- Cobluesky/Programmers - 다음 큰 숫자.js
- [[Programmers - 다음 큰 숫자 (JS)](https://school.programmers.co.kr/learn/challenges?order=acceptance_desc&page=3&levels=2%2C1&languages=javascript)]
---
- 정규식을 사용했습니다.
---
- 주석을 참조해주세요.
---
> 2022-12-13 Programmers - 다음 큰 숫자 (JS)

- hyeonwoo/백준 18111 마인크래프트.py
- [백준 18111 마인크래프트](https://www.acmicpc.net/problem/18111)
---
- 구현
- 브루트포스
---
- 컄
---
> 백준 18111 마인크래프트

- hyeonwoo/백준 18111 마인크래프트.py
- hyeonwoo/백준 2566 최댓값.py
- [백준 2566 최댓값](https://www.acmicpc.net/problem/2566)
---
- 구현
---
- 주어진 행렬을 2차원 배열로 입력받고, 반복문을 돌 때, `enumerate()` 함수를 이용하여 인덱스와 해당 행의 배열을 차례대로 접근한다.
- 해당 행의 배열에서 최댓값을 `max_matrix` 변수에 담는다.
- 행의 위치는 `enumerate()`를 통해 넘겨받은 인덱스 값에 `+1` 더한 만큼 `x` 변수에 담는다.
- 열의 위치는 해당 행의 배열의 `index()` 함수를 이용하여 `+1` 더한 만큼 `y` 변수에 담는다.
- 위에서 구한 최댓값과 행과 열의 위치를 `results` 딕셔너리에 담는다.
- 최댓값은 `key`에 저장, 행과 열의 위치는 튜플 형태로 `value`에 저장
- 마지막으로 `results` 딕셔너리의 `key` 값을 기준으로 최댓값을 출력하고,  해당 `key` 값을 이용해 행과 열의 위치가 저장된 `value`를 출력한다. 
---
> 백준 2566 최댓값

- jiWoo/백준_1780번_종이의개수.java
- [백준 1780번 종이의 개수](https://www.acmicpc.net/problem/1780)
---
- 재귀
---
- 1) 현재 종이가 같은 수로 이루어져 있으면 종이 사용
- 2) 현재 종이가 같은 수로 이루어져있지 않으면 종이 자른다(CutPaper 메서드 사용)
- CutPaper메서드: 전체를 9분할하여(현재 길이의 3으로 나눠서 r과 c를 구분)
- : 9분할 했을 때 사이즈가 1이라면 그냥 값에 넣어줌
- : 아니라면 sameNumPaper메서드를 사용하여 현재 같은 값으로 이루어져 있는지 확인하여 같은 값이면 결과값에 1을 더해주고 아니라면 또 종이를 자른다(재귀, CutPaper)
- result[3] 결과값은 3개인데 int num=-1, 0, 1로 이루어진 종이 찾기이다. 구별해주는걸 간편하게 result[num+1]++;하여 바로 값을 넣어주었다.( 값에 +1을 해주면 0, 1, 2)이므로
---
> 백준_1780번_종이의개수(재귀)

- taehyeong/programmers-하샤드 수.js
[하샤드 수](https://school.programmers.co.kr/learn/courses/30/lessons/12947)
---
정수,배열
---
정수를 문자 배열로 변환 후 배열을 반복하였습니다. 그리고 조건식을 작성하여 최종 결과값을 만들어 주었습니다.
---
> ✨프로그래머스 하샤드 수

- Cobluesky/Programmers - 시저 암호.js
- `[Programmers - 시저 암호](https://school.programmers.co.kr/learn/courses/30/lessons/12926)`
---
- indexOf를 사용했습니다.
---
- 주석을 참조해주세요.
---
> 2022-12-14 Programmers - 시저 암호 (JS)

- hyeonwoo/백준 이항 계수 2.py
- [백준 11051 이항 계수 2](https://www.acmicpc.net/problem/11051)
---
- 수학
---
- 파이썬은 정수 제한이 없어 `math` 모듈을 통해 조합을 쉽게 구해냈다.
---
> 백준 11051 이항 계수 2

- taehyeong/programmers-정수 내림차순으로 배치하기.js
[정수 내림차순으로 배치하기](https://school.programmers.co.kr/learn/courses/30/lessons/12933)
---
정수
---
parseInt(),toString(),split(),sort(),join() 메서드를 활용하여 간단하게 해결하였습니다.
---
> 📝프로그래머스 정수 내림차순으로 배치하기

- byeongjoo/백준 2630 색종이 만들기.py
[백준 2630번 색종이 만들기] (https://www.acmicpc.net/problem/2630)
---
분할정복
---
백준 [종이의 개수](https://www.acmicpc.net/problem/1780) 와 같은 풀이를 갖는 문제.
일단 2^n * 2^n이 어떤 모습을 갖는지 생각해 봐야 한다.
|||
|:---:|:---:|
|(x,y)|(x,y+offset)|
|(x+offset,y)|(x+offset, y+offset)|
하얀 종이와 파란 종이를 구해야 하며, 분할정복을 해야하기에 지수가 되는 n을 문제의 조건처럼 2로 나누면서 진행해야 된다.
재귀함수 내에 타겟과 flag 변수를 설정한다.
타겟은 재귀가 되는 보드의 첫번째 인자를 타겟으로 설정하면 되며, flag는 base condition으로 가기 위한 변수이다.
저번처럼 보드의 모든 요소를 돌며 target과 값이 달라진다면 flag를 false로 만들고, 반복문을 이중 break로 탈출한다.
flag가 true라면 보드의 모든 요소가 같은 값이기에 같은 종이라고 취급할 수 있으며, 만약 분할을 통해 한 조각이 된다해도 true이기에 하얀색은 하얀색으로 파란색은 파란색으로 종이를 가산해준다. 그 후 base condition 이므로 return을 통해 재귀를 call back 해준다.
위 테이블처럼 재귀를 하기 위해 offset을  n을 2로 나누어준다.
그 후 본인은 이중 for문을 이용해 위 테이블처럼 파라미터값을 생성하여 재귀의 인자로 넣어줬다.
---
> 백준 2630 색종이 만들기

- soojik/programmers/src/중복된_문자_제거.kt
- [프로그래머스 중복된 문자 제거](https://school.programmers.co.kr/learn/courses/30/lessons/120888)
---
- 문자열
---
- 주석 참고
---
> 프로그래머스 중복된 문자 제거

- hyeonwoo/백준 13985 Equality.py
- hyeonwoo/백준 18398 HOMWRK.py
- [백준 18398 HOMWRK](https://www.acmicpc.net/problem/18398)
---
- 수학
---
- $A_i$, $B_i$의 합과 곱을 나란히 출력한다.
---
> 백준 18398 HOMWRK

- hyeonwoo/백준 13985 Equality.py
- [백준 13985 Equality](https://www.acmicpc.net/problem/13985)
---
- 수학
- 문자열
---
- 주어진 입력값을 공백을 기준으로 나눠 배열에 저장 후 숫자가 있는 인덱스를 골라 수식이 맞는지 확인한다.
- 문제에서 주어진 수는 일의 자리라고 했으므로 인덱스가 달라질 일은 없다.
---
> 백준 13985 Equality

- sollyj/Baekjoon_1920_수찾기.java
- sollyj/Baekjoon_2178_미로.java
- [백준 1920번 수찾기](https://www.acmicpc.net/problem/1920)
---
- 탐색(이분탐색)
---
binarySearch함수정의
1.  데이터 배열의 중앙값을 선택
2. if(중앙값 > 찾을값)  중앙값 기준으로 왼쪽을 탐색
3. else if(중앙값 < 찾을값)  중앙값 기준으로 오른쪽을 탐색
4. else if(중앙값 == 찾을값)  탐색 종료
---
> Baekjoon_1920_수찾기

- taehyeong/programmers-콜라츠 추측.js
[콜라츠 추측](https://school.programmers.co.kr/learn/courses/30/lessons/12943)
---
정수
---
반복문과 조건식으로 간단하게 해결하였습니다.
---
> 📝프로그래머스 콜라츠 추측

- soojik/programmers/src/시저암호/시저암호.kt
- soojik/programmers/src/중복된_문자_제거/중복된_문자_제거.kt
- [프로그래머스 시저암호](https://school.programmers.co.kr/learn/courses/30/lessons/12926?language=kotlin)
---
- 문자열
---
- 주석 참고
---
> 프로그래머스 시저암호

- hyeonwoo/백준 11944 NN.py
- [백준 11944 NN](https://www.acmicpc.net/problem/11944)
---
- 구현
- 문자열
---
- N이 M보다 작으면 N을 N번 출력
- N이 M보다 크거나 같으면 답의 앞 M자리를 출력
---
> 백준 11944 NN

- Cobluesky/Programmers - 영어 끝말잇기.js
- `[Programmers - 영어 끝말잇기 (JS)](https://school.programmers.co.kr/learn/courses/30/lessons/12981)`
---
---
- 주석을 참조해주세요.
---
> 2022-12-19 Programmers - 영어 끝말잇기 (JS)

- Cobluesky/Programmers - 제일 작은 수 제거.js
- `[Programmers - 제일 작은 수 제거](https://school.programmers.co.kr/learn/courses/30/lessons/12935)`
---
- 전개연산자와 indexOf를 사용했습니다.
---
- 주석을 참조해주세요.
---
> 2022-12-21 Programmers - 제일 작은 수 제거 (JS)

- sollyj/Baekjoon_10815_숫자카드.java
- [백준 10815번 숫자카드](https://www.acmicpc.net/problem/10815)
---
- 탐색(이진탐색)
---
- 매 원소마다 순차적으로 탐색하는건 시간이 오래걸리기 때문에 이진탐색 방법을 선택했다.
- binSearch(찾을값, 배열)
배열의 중앙값과 찾을값의 크기 비교를 통해 탐색한다.
중앙값 == 찾을값 ➡️ 찾음 true반환
중앙값 > 찾을값 ➡️ 중앙값 왼쪽 배열에서 다시 이진탐색
중앙값 < 찾을값 ➡️ 중앙값 오른쪽 배열에서 다시 이진탐색
---
> Baekjoon_10815_숫자카드

- yunhwan/백준 1780 종이의개수.py
- [백준 1780 종이의 개수](https://www.acmicpc.net/problem/1780)
---
- DFS 알고리즘 사용
---
- dfs : 종이가 같은 수면 증가, 같지 않으면 종이 9개로 자르는 함수
check: 종이가 같은 수인지 확인하는 함수
1. dfs를 실행하여 check를 통해 종이가 같은 수인지 확인
2. 종이가 같은 수라면 해당 종이 개수를 증가 후 종료
3. 종이가 같지 않다면 9개로 나눠진 종이에 대하여 1. 반복
---
> 백준 1780 종이의 개수

- yunhwan/백준 1697 숨바꼭질.py
- [백준 1697 숨바꼭질](https://www.acmicpc.net/problem/1697)
---
- bfs
---
- 너비 우선 탐색을 이용하면, 중복 방지 및 k위치에 도달하는 최소 시간을 구할 수 있음
bfs: 이동 가능한 위치를 탐색하는 함수
1. 현재 위치를 bfs에 넣고 실행
2. 현재 위치에서 1초 동안 이동 할 수 있고, 방문한 적 없는 위치에 +1초, 큐에 추가
3. k위치에 도달할 때까지 반복
---
> 백준 1697 숨바꼭질

- Cobluesky/Programmers - 나누어 떨어지는 숫자.js
- Cobluesky/Programmers - 짝지어 제거하기.js
- [Programmers - 나누어 떨어지는 숫자 배열](https://school.programmers.co.kr/learn/courses/30/lessons/12910)
---
---
- 주석을 참조해주세요.
---
> 2022-12-22 Programmers - 나누어 떨어지는 숫자 배열 (JS)

- sollyj/Baekjoon_1388_바닥장식.java
-  [백준 1388번 바닥장식](https://www.acmicpc.net/problem/1388)
---
- 탐색
---
1. -개수 구하기
가로방향으로 탐색한다.
여기서 tmp는 -와 |를 구분해주는 임시변수라고 생각하면된다.
| 아니면 - 경우의 수 밖에 없으므로 |가 아니라면 ++tmp해주고 tmp가 1인동안은 한개의 장식이므로 count는 한번만 해준다.
2. | 개수 구하기
세로방향으로 탐색한다.
-개수 구하는 것과 알고리즘은 같다.
---
> Baekjoon_1388_바닥장식

- yunhwan/백준 8911 거북이.py
- [백준 8911 거북이](https://www.acmicpc.net/problem/8911)
---
- 구현
- 시뮬레이션
---
- 1. R or L 입력 경우:  90도 or -90도로 방향이동
2. F or B 입력 시 거리+1 or -1 , 현재 위치 갱신 후 배열에 추가
3. 모두 입력 받은 후 배열을 통해 직사각형 넓이 구하기
= x 이동거리(max(x)-min(x)) * y이동거리(max(y) *min(y))
---
> 백준 8911 거북이

- yunhwan/백준 1074번 Z.py
- [백준 1074번 Z](https://www.acmicpc.net/problem/1074)
---
- 재귀, dfs
---
- dfs : 순서를 찾는 함수,  박스가 4칸 인지 확인
1. dfs를 실행하여 박스가 4칸 인지 확인
2. 박스가 4칸 이라면  몇 번째 칸인지 파악 후, 해당 칸 + s
3. 박스가 4칸이 아니면,  박스를 4 등분 한 뒤 r,c 가 해당하는 박스 찾고 1 반복
---
> 백준 1074번 Z

- yunhwan/백준 12026 BOJ거리.py
- [백준 12026 BOJ거리](https://www.acmicpc.net/problem/12026)
---
- 다이나믹 프로그래밍
---
- 
1. dp(= 최소 에너지양) 배열 생성, B,O,J 해당하는 배열에 주소 넣기
2. 현재 문자(B or O or J) 다음에 올 문자의 dp값 갱신( O  or J or B)
3.  마지막 값이 갱신 되지 않으면 불가능
---
> 백준 12026 BOJ거리

- sollyj/Baekjoon_2606_바이러스.java
- [백준 2606번 바이러스](https://www.acmicpc.net/problem/2606)
---
- 탐색(DFS)
---
- 일반적인 깊이우선탐색 알고리즘과 똑같다.
- 인접리스트를 만들고 1번 컴퓨터와 인접해있는 컴퓨터를 탐색하여 찾는다.
- 너비우선탐색으로 풀어봐도 좋을 듯 하다.
---
> Baekjoon_2606_바이러스

- yunhwan/백준 12865 평범한배낭.py
- [백준 12865 평범한배낭](https://www.acmicpc.net/problem/12865)
---
- 다이나믹 프로그래밍
---
- 1. 2차원 dp 생성
2. 무게가 가방에 들어갈 수 있는 지 비교
3. 없으면 기존 무게 유지, 있으면 가방에 들어갈 때, 들어가지 않을 때 중 큰 값 선정
4. 물건의 개수만큼 n번 반복
---
> 백준 12865 평범한배낭

- yunhwan/백준 15989 1,2,3 더하기 4.py
- [백준 15989 1,2,3 더하기 4](https://www.acmicpc.net/problem/15989)
---
- 다이나믹 프로그래밍
---
- 1. 10000 크기의 dp 생성
2. 기존 값에서 2로 나타낼 수 있는 합을 추가
3. 기존 값에서 3으로 나타낼 수 있는 합을 추가
---
> 백준 15989 1,2,3 더하기 4

- yunhwan/백준 3085 사탕 게임.py
- [백준 3085 사탕 게임](https://www.acmicpc.net/problem/3085)
---
- 시뮬레이션
- 브루드포스
---
findCandy(x,y)
x,y 좌표의 행, 열을 기준 가장 길게 연결된 사탕 찾기 함수
1. 입력 값을 토대로 그래프 생성
2. 그래프 전체에 대한 findCandy 실행
3. 인접 사탕과 교환 가능한 두 좌표를 모은 배열 생성
4.  값 교환, 해당 배열 원소에 대하여 findCandy() 실행, 원위치
5. 반복하며 가장 큰 값을 정답으로 설정
---
> 백준 3085 사탕 게임

- yunhwan/백준 11051 이항계수2.py
- [백준 11051 이항계수2](https://www.acmicpc.net/problem/11051)
---
- 조합론
---
- nCk 의 조합 식을 이용
n! // (r!(n-r)!)
---
> 백준 11051 이항계수2

- yunhwan/백준 14719 빗물.py
- [백준 14719 빗물](https://www.acmicpc.net/problem/14719)
---
- 시뮬레이션
---
- 맨 밑의 행부터 빗물이 들어갈 수 있는 칸을 세는 방식
빗물 칸이 아닌 경우, 벽으로 여김
flag: 빗물 칸을 셀 수 있는지 여부 구분
첫 번째 열, 마지막 열, 중간 열에 따라서 조건 설정
1. 첫 번째 열이 벽인 경우, flag=1 (빗물 세기 가능)
2. 마지막 열이 벽인 경우, 모은 빗물을 result에 더하기
3. 중간 열인 경우   
벽일 때, 모은 빗물 더해주고 초기화   
벽이 아닐 때, row에 빗물 모으기
---
> 백준 14719 빗물

- yunhwan/백준 1010번 다리 놓기.py
- [백준 1010번 다리 놓기](https://www.acmicpc.net/problem/1010)
---
- 조합론
---
- m개의 자리중에서 n개의 다리를 선택하는 것과 같은 문제이므로
mCn의 수학공식을 사용하여 정답 구함
---
> 백준 1010번 다리 놓기

- yunhwan/백준 16953 A→B.py
- [백준 16953 A→B](https://www.acmicpc.net/problem/16953)
---
- dfs
---
- b에서 부터 a를 거꾸로 탐색해주기
맨 뒤 자리가  1이면 10을 나눈 값을 dfs
짝수일 경우 2를 나눈 값을 dfs
---
> 백준 16953 A→B

- Cobluesky/Programmers - 구명보트.js
- [Programmers - 구명보트](https://school.programmers.co.kr/learn/courses/30/lessons/42885)
---
- 탐욕법 (Greedy) 사용했습니다.
---
- 주석을 참조해주세요!
---
새해복 많이받으세요.
> 2023-01-03 Programmers - 구명보트 (JS)

- yunhwan/백준 12869 뮤탈리스크.py
- [백준 12869 뮤탈리스크](https://www.acmicpc.net/problem/12869)
---
- dfs
---
- dfs 탐색을 통한 풀이
첫번 째 공격 대상은 가장 체력이 많은 scv
상황에 따라서 2번째 3번째 공격 해야 하는 scv 고려
---
> 백준 12869 뮤탈리스크

- Cobluesky/Programmers - 폰켓몬.js
- [Programmers - 폰켓몬 (JS)](https://school.programmers.co.kr/learn/courses/30/lessons/1845)
---
- SET를 사용했습니다.
---
- 주석을 참조해주세요.
- 다소 엉망인 코드입니다.
---
> 2023-01-05 Programmers - 폰켓몬 (JS)

- yunhwan/백준 2290 LCD Test.py
- [백준 2290 LCD Test](https://www.acmicpc.net/problem/2290)
---
- 시뮬레이션
---
- LCD 안의 숫자는 3가지의 가로 선, 4가지의 세로 선으로 나타낼 수 있음
1. 그래프 초기화 시켜주기
2. lineRow,lineCol 함수를 생성해서 상황에 맞게 줄 그을 수 있게 설정
3. 0-9에 맞게 그래프에 줄 긋기
4. 그래프를 읽고 그에 맞는 출력
---
> 백준 2290 LCD Test

- yunhwan/백준 17070번 파이프 옮기기1.py
- [백준 17070번 파이프 옮기기1](https://www.acmicpc.net/problem/17070)
---
- 다이나믹 프로그래밍
---
- 각 칸마다 3가지 방향에 대한 저장소를 생성
**3가지 방향**
아래 상황일 때만 가능
가로: 가로→가로, 가로→대각선
대각선:  대각선→가로, 대각선→대각선, 대각선→세로
세로: 세로→대각선, 세로→세로
해당되는 상황일 때만 이전 위치의 값을 새로운 위치에 더해줌
---
> 백준 17070번 파이프 옮기기1

- sollyj/Baekjoon_1015_수열정렬.java
- [백준 1015번 탑](https://www.acmicpc.net/problem/1015)
---
- 정렬
---
- P의 인덱스는 **A를 오름차순한 후 해당 원소가 오름차순 정렬 하기 전 인덱스**이고,
- P의 값은 0, 1, 2, ..., N-1 이다.
- A는 오름차순 하기 전 인덱스를 알아야 하므로 mData라는 객체형으로 배열선언을 해주었다. (mData는 값과 인덱스를 저장해논다.)
- 이를 이해하면 단순히 정렬 후 P배열에 값을 넣어주기만 하면 되는 문제다.
---
> Baekjoon_1015_수열정렬

- yunhwan/프로그래머스 숫자 문자열과 영단어.py
- [프로그래머스 숫자 문자열과 영단어](https://school.programmers.co.kr/learn/courses/30/lessons/81301)
---
- 문자열
---
- dic 생성
해당되는 문자가 있을 경우 replace 해줌
---
> 프로그래머스 숫자 문자열과 영단어

- yunhwan/백준 16197 두 동전.py
- [백준 16197 두 동전](https://www.acmicpc.net/problem/16197)
---
- bfs
---
- 방문한 좌표를 확인하기 위한 visited 집합 생성
bfs를 이용하여 두 동전의 위치로 부터 4방향으로 탐색
1. 동전의 위치 저장
1. 동전이 범위 안에 있고 빈 칸일 경우 이동한 값을 temp에 추가
2. 동전이 범위 안에 있고 벽일 경우 이동 전의 값을 temp에 추가
2. 동전의 위치 확인
1. 동전 0개가 범위 밖에 있다면 방문 좌표를 visited에 추가, q에 추가 
2. 동전 1개가 범위 밖에 있다면 cnt+1 반환
3. 동전 2개가 범위 밖에 있다면 continue
---
> 백준 16197 두 동전

- yunhwan/프로그래머스  타켓 넘버.py
- [프로그래머스  타켓 넘버](https://school.programmers.co.kr/learn/courses/30/lessons/43165)
---
- dfs
---
- dfs를 이용한 풀이
v 위치에 있는 값의 부호를 +, - 로 설정해주고 dfs 반복
---
> 프로그래머스  타켓 넘버

- Cobluesky/Programmers -가장 큰 수.js
- [Programmers - 가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746/)
---
-  map과 sort를 사용했습니다.
---
- 주석을 참조해주세요.
---
> 2023-01-10 Programmers - 가장 큰 수 (JS)

- yunhwan/백준 1062 가르침.py
- [백준 1062 가르침](https://www.acmicpc.net/problem/1062)
---
- dfs
---
- dfs 탐색을 통한 풀이
anta tica에 포함되는 알파벳은 cur 배열
cur에 해당되지 않는 알파벳은 alphabet
---
> 백준 1062 가르침

- yunhwan/프로그래머스 신고 결과 받기.py
- [프로그래머스 신고 결과 받기](https://school.programmers.co.kr/learn/courses/30/lessons/92334)
---
- 딕셔너리
---
- 
1. boolean[][] check이차원 배열을 만들어 신고를 한 사람을 체크하여 중복을 막아줌
2. 신고를 당한 사람이 과거에 같은 사람에게 안 받았을 경우에 횟수 ++
3. check를 확인하며 신고한 사람이 정지 횟수 넘었을 때 메일 횟수++
---
> 프로그래머스 신고 결과 받기

- sollyj/Baekjoon_11047_동전0.java
- [백준 11047번 동전0](https://www.acmicpc.net/problem/11047)
---
- 그리디
---
- 동전의 최소 개수를 구하기 위해서 가장 가격이 큰 동전부터 개수를 센다.
- value배열에 동전 가치를 넣고 역순으로 순회하며 K와 연산한다.
- K와 value를 나눠 몫을 result에 더하고, 나머지가 0일때까지 반복문을 돌린다.
---
> Baekjoon_11047_동전0

- yunhwan/프로그래머스 로또의 최고 순위와 최저 순위.py
- [프로그래머스 로또의 최고 순위와 최저 순위](https://school.programmers.co.kr/learn/courses/30/lessons/77484)
---
- dic사용
---
- 
1. 맞춘 개수에 따른 순위 저장
2. 일치하는 수는 cnt, 0인 수는 plus 설정
3. 최대로 맞쳤을 때 순위, 최소로 맞쳤을 때 순위 반환
---
> 프로그래머스 로또의 최고 순위와 최저 순위

- byeongjoo/백준 15652 N과M4.py
- [백준 15652번 N과M(4)](https://www.acmicpc.net/problem/15652)
---
- 백트래킹
---
출력을 보면, 값은 일정한 변화를 가지고 있으면서 순서가 있으므로 백트래킹으로 풀게 되었다.
문제를 보면 ``같은 수를 여러번 골라도 되며, 고른 수열은 비내림차순이어야 한다.`` 라는 조건을 주고 있다.
본인은 출력할 값을 저장할 배열과 백트래킹을 하며 값의 변화를 줄 변수를 선언해주었다.
``` python
arr = [0 for _ in range(10)] # 출력할 값을 저장할 배열
start = 1 # 백트래킹할 때 값에 변화를 주기 위한 시작 변수
```
백트래킹은 재귀처럼 콜백을 해주며, 상태 변화를 체크해주면 되는 알고리즘이라고 알고 있기에 자릿수의 값의 변화를 주기 위해
```python
if k != 0: # 현재 자릿수가 1이 아닌 경우
start = arr[k-1] # 뒷 수는 앞 수의 영향을 받으므로 시작 변수를 바꿔야함.
```
위 코드처럼 조건을 만들어서 뒷 수가 앞 수의 변화에 영향을 받아 비내림차순으로 만들 수 있도록 하였다. 
마지막으로 재귀로 자릿수를 진행하고, 콜백으로 돌아와서 다음 수를 넣을 수 있도록
```python
for i in range(start, n+1):
arr[k] = i # 배열의 k번째 자리는 i
nm(k+1) # k k+1 k+2 .. k+O(=m) 까지 자리 수 옮기기
```
위와 같이 반복문을 집어넣어 주었다. arr[k] 와 if 조건문을 통한 start 변수를 통해 같은 수를 사용할 수도 있으며, 같은 수가 …
> 백준 15652 N과M(4)

- yunhwan/백준 1189 컴백홈.py
- [백준 1189 컴백홈](https://www.acmicpc.net/problem/1189)
---
- dfs
---
-
1. 시작위치는 g[r-1][0], 종료위치는 g[0][c-1]
2. 시작위치 부터 dfs를 실행하여 4방향 중 이동할 수 있고 방문한적이 없는 경우 dfs 실행 
3. 종료위치에 도착하고 이동거리가 k와 같을 때 ans증가
4. ans 출력
---
> 백준 1189 컴백홈

- yunhwan/프로그래머스 성격 유형 검사하기.py
- [프로그래머스 성격 유형 검사하기](https://school.programmers.co.kr/learn/courses/30/lessons/118666?language=java#)
---
- 배열
---
-
1. mbti의 결과를 점수로 받아줄 result 생성
2. survey를 조사하여 어떤 유형을 검사하는지 확인 후 idx에 저장
알파벳이 앞자리에 오는지 확인 후 T,F,M,N인 경우는 mul*=-1
3.  choices결과에 -1을 곱한 후 4를 더하여 3,2,1,0,-1,-2,-3 같이 수정
4. R,C,J,A 경우에는 result값에 그대로 더하기, T,F,M,N인 경우는 mul을 곱하여 더하기
5. result값이 0이상 이면 R,C,J,A / 0보다 작으면 T,F,M,N의 결과를 나타냄
---
> 프로그래머스 성격 유형 검사하기

- byeongjoo/백준 15654 N과M5.py
- [백준 15654 N과 M (5)](https://www.acmicpc.net/problem/15654)
---
- 백트래킹
---
문제 출력 조건을 보면 ``중복되는 수열을 여러 번 출력하면 안되며, 각 수열은 공백으로 구분해서 출력해야 한다.
수열은 사전 순으로 증가하는 순서로 출력해야 한다.`` 라고 명시 되어 있다.
여러 번 출력하면 안되기에 수열 요소 상태를 잠가주고, 풀어주고 할 조건을 넣어주어야 하며, 사전 순으로 증가하는 순서로 출력하기 위해 입력 요소로 주는 수열을 내림차순 정렬 할 필요가 있다.
내림차순 정렬을 하기 위해
``` python
data = list(map(int, input().split()))
data.sort() # 데이터를 내림차순으로 정렬
```
을 해주어 입력 값을 내림차순으로 정렬을 해주었다.
수열 요소 사용 상태를 체크 하기 위해 초기값으로 ``isused= [False for _ in range(10)]`` 와 같이 수열 중 i 요소가 사용되는지 체크하는 불린 리스트를 선언을 해주었다.
백트래킹의 base condition에서 데이터 출력은 ``print(data[arr[i]], end=" ")`` 모습인데, ``data배열``의 ``arr배열의 i번째 요소`` 를 출력해주는 것이다. ``data배열`` 또한 n의 길이를 갖고 ``arr배열``은 ``증가하는 k 자릿수마다 0부터 n-1까지의 수를 갖는 배열``이기에 data배열에 arr배열의 i번째 요소를 요소로 갖는다면 원하는 데이터를 출력할 수 있다.
마지막으로 arr배열을 반복문은 이런 모습을 가지게 …
> 백준 15654 N과M(5)

- yunhwan/백준 1456 거의 소수.py
- [백준 1456 거의 소수](https://www.acmicpc.net/problem/1456)
---
- 소수
---
- 거의 소수의 최대 값은 b의 제곱근임, 
따라서 에라토스테네스의 체를 사용할 때도 b제곱근 만큼의 공간만 사용 가능
1. 에라토스테네스의 체를 사용하여 소수를 찾음
2. 소수인 경우 거듭 제곱이 a이상 이고 b이하인 경우 세주기
---
> 백준 1456 거의 소수

- sollyj/Baekjoon_3273_두수의합.java
- [백준 3273번 두수의합](https://www.acmicpc.net/problem/3273)
---
- 투포인터
---
- 리스트를 하나하나 순회하면 시간초과가 나므로 투포인터를 써야한다.
- List를 오름차순 정렬해 pointer1은 앞부터, pointer2는 뒤부터 순회한다.
- sum = pointer1 + pointer2값과 x를 비교해가며 pointer1, poiner2를 이동한다.
---
> Baekjoon_3273_두수의합

- yunhwan/백준 1016번 제곱 ㄴㄴ 수.py
- [백준 1016번 제곱 ㄴㄴ 수](https://www.acmicpc.net/problem/1016)
---
- 에라토스테네스의 체
---
- 
1. 소수는 에라토스테네스의 체 사용해서 구함
2. 소수를 구할 때 범위는 B의 제곱근까지 
3. 메소드 Square 사용하여 해당 범위의 거의 소수 개수 구함. 해당 소수의 N제곱
---
> 백준 1016번 제곱 ㄴㄴ 수

- yunhwan/백준 1038 감소 하는 수.py
- [백준 1038 감소하는 수](https://www.acmicpc.net/problem/1038)
---
- 브루드포스
---
-
감소하는 수가 되는 경우는 1~9876543210
하지만 이를 전부 하나하나 찾으면 시간 초과 발생
따라서  수 찾기 함수를 사용하여 1부터 10자리 감소하는 수를 찾아줌 
문자열을 이용해, 맨 뒤에 위치하는 수보다 작은 수를 추가 해주고
조건에 만족하지 않으면 False
배열의 길이가 원하는 자릿수만큼 커지면 감소하는 수 추가
---
> 백준 1038 감소 하는 수

- sollyj/Baekjoon_1541_잃어버린괄호.java
- [백준 1541번 잃어버린괄호](https://www.acmicpc.net/problem/1541)
---
- 그리디
---
- 가장 최솟값이 되려면 가장 큰수를 빼줘야한다.
- 즉, 더할수있는 것을 먼저 더하고(괄호를 치고), 빼기를 실행하면 된다.
---
> Baekjoon_1541_잃어버린괄호

- byeongjoo/백준 15655 N과M6.py
- [백준 15655번 N과 M (6)](https://www.acmicpc.net/problem/15655)
---
- 백트래킹
---
이번 문제의 출력 조건으로 ``한 줄에 하나씩 문제의 조건을 만족하는 수열을 출력한다. 중복되는 수열을 여러 번 출력하면 안되며, 각 수열은 공백으로 구분해서 출력해야 한다. 수열은 사전 순으로 증가하는 순서로 출력해야 한다.`` 라고 한다.
일단 사전 순으로 증가하는 순서로 출력시키기 위해 입력으로 받은 데이터를 내림차순 정렬을 해준다.
``` python
data = list(map(int, input().split()))
data.sort() # 데이터 내림차순 정렬
```
자릿 수를 n, n+1, n+2, ... , n+k 로 봤을 때, n < n+1 < n+2 .... < n+k 형태를 지키고 있어야 하며, 중복이 되선 안되므로 전역변수로 증가할 start 변수를 선언한다.
``` python
start = 0 # 자릿수마다 시작값을 바꿔줄 변수. 초기값은 0
```
값을 출력하는 모양은 전에 풀던 n과m(5) 처럼 ``print(data[arr[i]], end=" ") # 데이터의 arr[i]의 요소 꺼내기`` 나타내어 순서를 저장할 arr리스트의 i 요소의 값을 data의 요소에 삽입하여 데이터를 출력할 수 있도록 해주자.
start 변수의 변화는 다음과 같이 만들어준다.
``` python
if k != 0 : # k가 시작(0) 요소가 아니라면?
start = arr[k-1] + 1 # 스타트 포인트는 arr의 이전 값의 1을 더한 값.
```
k 가 …
> 백준 15655번 N과 M(6)

- yunhwan/백준 2293 동전1.py
- [백준 2293 동전1](https://www.acmicpc.net/problem/2293)
---
- 다이나믹 프로그래밍
---
- 
arr의 맨 처음 수를 이용하여 k까지 조합해서 만들 수 있는 수들에 +=1을 해주면서 dp설정
이 후 arr의 두번 째 수 부 터는 설정 시켜준  dp를 이용함
ex) dp[j] = dp[j] + dp[j-cur]
기존 dp에 dp[j-cur]을 더해줌
---
> 백준 2293 동전1

- yunhwan/백준 1541 잃어버린 괄호.py
- [백준 1541번- 잃어버린 괄호](https://www.acmicpc.net/problem/1541)
---
- 그리디 알고리즘
---
-
수의 부호가 음수인 경우를 찾은 후, 괄호에 들어갈 범위를 정해주고, 
원래 식의 더한 값과 괄호 식을 정해준 식의 값을 비교
---
> 백준 1541 잃어버린 괄호

- yunhwan/백준 1744 수 묶기.py
- [백준 1744 수 묶기](https://www.acmicpc.net/problem/1744)
---
- 그리디 알고리즘
---
-
양수,음수를 각각 내림차순, 오름차순으로 정렬
수를 묶는 경우
1이 있을 때는 더하고, 그 외의 수들은 곱해주기
---
> 백준 1744 수 묶기

- yunhwan/백준 14888 연산자 끼워넣기.py
- [백준 14888 연산자 끼워넣기](https://www.acmicpc.net/problem/14888)
---
- dfs
---
-
연산자의 개수의 조합을 다양하게 하여 문제를 푸는 것이 중요
따라서 DFS를 사용하여 
더하기,빼기, 곱하기, 나누기의 개수를 조합하여 값을 구하고
그 과정에서 가장 큰 값과 작은 값을 구해줌
---
> 백준 14888 연산자 끼워넣기

- yunhwan/백준 23842 성냥개비.py
- [백준 23842 성냥개비](https://www.acmicpc.net/problem/23842)
---
- dfs
---
-
DFS를 사용하여 깊이가 6이 되거나 성냥개비의 수가 음수일 때 종료,
성냥개비로 만든 공식이 조건을 만족하면, 출력
그렇지 않으면, impossible 출력
---
> 백준 23842 성냥개비

- jiWoo/프로그래머스_비밀지도.java
- [프로그래머스 [1차]비밀지도](https://school.programmers.co.kr/learn/courses/30/lessons/17681?language=java)
---
- 진수 변환
---
- solution1: 10진수-> 2진수를 반복문을 돌려 변환
- solution2: 내장함수를 사용해서 
- >  글애도 먼가 모자란듯한 컄
---
> 프로그래머스_비밀지도

- yunhwan/백준 24060 병합정렬1.py
- [백준 24060 병합정렬1](https://www.acmicpc.net/problem/24060)
---
- 병합정렬
---
- 병합 정렬은 배열 중간의 값을 기준으로 왼쪽 오른쪽으로 배열을 나눠 정렬 후 다시 합치는 정렬이다.
1. 왼쪽 오른쪽 정렬을 나누고 merge함수를 이용하여 합친다
2.왼쪽정렬 오른쪽 정렬을 합치는 과정
왼쪽 정렬과 오른쪽 정렬이 각각의 정렬의 끝에 도달하기 전까지 
왼쪽 정렬의 원소가 오른쪽 정렬의 원소 이하면  
왼쪽 정렬의 원소를 tmp에 저장하며 새로 정렬해준다
그렇지 않을 때는 오른쪽 정렬의 원소를 tmp에 저장해준다
왼쪽 부분이 남았다면 남은 원소들을 tmp에 넣어주고
오른쪽 부분이 남았다면 남은 원소들을 tmp에 넣어준다
tmp 저장된 값은 정렬되었고  a에 다시 넣어준다
---
> 백준 24060 병합정렬1

- jiWoo/프로그래머스_옹알이2.java
- [프로그래머스 옹알이(2)](https://school.programmers.co.kr/learn/courses/30/lessons/133499)
---
- 문자열....비교 정도..? 
---
- 한발자국 한 발자국 비교하며(그저 반복문과 if) 가능한 발음 비교해줬는데 더 짧게 다시 풀어보겠습니다.
---
> 프로그래머스 옹알이(2)

- yunhwan/백준 14502 연구소.py
- [백준 14502 연구소](https://www.acmicpc.net/problem/14502)
---
- bfs, 조합
---
- 벽을 3개 사용하여 최대한의 0(안전영역)을 만드는 것이 중요
1. 그래프를 순회하면서 안전영역, 벽, 바이러스 리스트를 생성
2. 안전영역에서 3개의 좌표를 조합하는 newWall리스트 생성
3. newWall리스트를 순회
- 그래프 복사 후 새롭게 벽 3개 추가
- 새로운 그래프에 바이러스 퍼뜨리기
- 바이러스가 퍼진 후 그래프의 안전영역을 세주기
- 안전영역이 가장 많은 경우를 정답으로 출력
---
> 백준 14502 연구소

- jiWoo/백준_14502번_연구소.java
- [백준 14052번 연구소](https://www.acmicpc.net/problem/14502)
---
- bfs
---
- 1) 벽 3개를 노가다로 돌려준다.
- 2) 벽이 3개일 때 bfs를 사용하여 바이러스가 감염된 구역을 찾아주고, 안전지대의 수를 받는다.
- 3) 반복하여 안전지대가 최대값일 때를 찾는다.
- -> 노가다 bfs 문제 
---
> 백준_14052번_연구소

- jiWoo/프로그래머스_전력망을둘로나누기.java
- [프로그래머스 전략망을 둘로 나누기](https://school.programmers.co.kr/learn/courses/30/lessons/86971)
---
- 연결리스트, 탐색
---
- 연결리스트에 연결된 모든 노드들을 저장하고 연결된 노드들을 하나씩(i-j) 끊으며 i노드에 연결된 노드 개수, j노드에 연결된 노드 개수의 최소 절대값을 구함. 
---
> 프로그래머스_전략망을둘로나누기

- Cobluesky/Backjoon_2751.java
- [백준 2751](https://www.acmicpc.net/problem/2751)
---
- Timsort를 사용했습니다.
---
- 주석을 참조해주세요.
---
> 백준 2751 - 수 정렬하기 2 (JAVA)

- Cobluesky/Backjoon_1546.java
- [백준 1546 ](https://www.acmicpc.net/problem/1546)
---
---
- 주석을 참조해주세요.
---
> 백준 1546 - 평균 (JAVA)

- sollyj/Baekjoon_1744_수묶기.java
- [백준 1744번 수묶기](https://www.acmicpc.net/problem/1744)
---
- 그리디
- **우선순위 큐**
---
- 시행착오
처음에 그냥 배열에 넣고 조건문과 반복문을 이용해서 풀려니 코드가 길어지고 시간초과가 날 것 같아 노선을 바꿨다.
👉 우선순위 큐!
_양수는 내림차순으로 넣어 큰 수 부터 나오게끔 하고, 음수는 오름차순으로 넣어 작은 수 부터 나오게끔 한다._
- 양수 처리
1은 곱하는 것 보다 더해야 더 최대가 되므로 따로 분류한다. ex) 1 * 3 < 1 + 3
1. 두개씩 빼면서 묶고(곱하고) 더한다.
2. 마지막 남은 수는 그냥 더해준다.
- 음수 처리
0 처리와 동시에 해준다.
1. 두개씩 빼면서 묶고(곱하고) 더한다.
2-1. 0이 있을 때: 마지막 남은 수 * 0한 것을 더해주는데 사실 이는 의미가 없으므로 result에 연산을 굳이 해주지 않는다.
2-2. 0이 없을 때: 마지막 남은 수를 result에 더해준다.
---
> Baekjoon_1744_수묶기

- yunhwan/프로그래머스 [1차]비밀지도.py
- [프로그래머스 [1차]비밀지도](https://school.programmers.co.kr/learn/courses/30/lessons/17681?language=python3)
---
- 2진법
---
- 
1. 입력받은 문자열을 각각 문자열로  2진수로 변환하여 생성
2. 변환한 2진수 문자열의 각 자리 끼리 or 연산 실행
3. 2결과에 만족하는 대로 map생성
---
> 프로그래머스 [1차]비밀지도

- Cobluesky/Backjoon_1026.java
- [백준 1026](https://www.acmicpc.net/problem/1026)
---
- 정렬과 greedy를 사용해 풀었습니다.
---
- 주석을 참조해주세요.
---
> 백준 1026 - 보물 (JAVA)

- jiWoo/프로그래머스_가장큰수.java
- [프로그래머스 가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746#)
---
- 문자열 비교
---
- ㅜㅜ답 참고했어유
- 1. int → String으로 바꿔준다.
- 2. 문자열 배열을 앞에 왔을 때 내림차순이 되도록 정렬한다.
- 3. (예외) 숫자가 다 0일때 ex {0,0,0,0}은 “0000”이 되므로 정렬된 numString[0]이 0이면 다 0이므로 answer=”0”으로 신경써준다.
---
> 프로그래머스_가장큰수

- sollyj/Baekjoon_10773_제로.java
- [백준 10773번 제로](https://www.acmicpc.net/problem/10773)
---
- 스택
---
- 최근 수를 빼는 것이므로 선입후출 구조인 `스택`을 이용한다.
- 차례대로 push하다가 0이면 pop
- 남은 수들 합 출력
---
> Baekjoon_10773_제로

- Cobluesky/Backjoon_4344.java
- [백준 4344](https://www.acmicpc.net/problem/4344)
---
---
- 주석을 참조해주세요.
---
> 2023-02-09 백준 4344 - 평균은 넘겠지 (JAVA)

- yunhwan/백준 11399번- ATM .py
- [백준 11399번- ATM ](https://www.acmicpc.net/problem/11399)
---
- 삽입정렬
---
-
앞에서 인출시간이 짧을 수록 인출 시간의 합이 최소가 됌
따라서 p를 오름차순으로 정렬한 후
w[i] = w[i-1] + p[i] 로 설정
w의 값을 모두 더한 값이 정답
---
> 백준 11399번 ATM

- sollyj/Baekjoon_2343_기타레슨.java
- [백준 2343번 기타레슨](https://www.acmicpc.net/problem/2343)
---
- 이분 탐색
---
- 블루레이 크기의 `최솟값`은 `강의의 최대길이` 이고
- 블루레이 크기의 `최댓값`은 `강의 길이를 다 더한 값` 이다.
- 블루레이 크기의 중간값부터 **_이분 탐색_** 을 시작한다.
- videos배열을 돌면서 블루레이 크기 cnt를 하고 cnt와 M을 비교해 중간값의 왼쪽 set을 탐색할지, 오른쪽 set을 탐색할지 결정한다.
- 이렇게 탐색이 끝나면 최솟값을 구하는 것 이므로 start를 출력한다.
---
> Baekjoon_2343_기타레슨

- jiWoo/프로그래머스_롤케이크자르기.java
- [프로그래머스 롤케이크 자르기](https://school.programmers.co.kr/learn/courses/30/lessons/132265)
---
- 뭘까요?
---
- 1) 왼쪽을 HashSet을 사용해서 중복없이 값을 받아주고
- 2) 오른쪽은 한 번 두번째부터 끝까지 Hashmap을 사용하여 인덱스마다 해당 값에 수를 저장해주는데 이건 오른쪽으로 가며 값을 삭제하는 것을 찾아주기 위하여
- 3) 두번째부터 끝까지 한 칸씩 이동하며 왼쪽에 값을 넣어주고(중복값은 안들어간다) 오른쪽에는 해당 값의 숫자를 빼주는데 그 값이 0일때는 right에서 삭제해준다. 그러고 둘의 사이즈를 비교하여 같으면 종류의 수가 같으므로 answer++해준다.
---
> 프로그래머스 롤케이크 자르기

- Cobluesky/hackerrank_javalist.java
- [HackerRank - JavaList](https://www.hackerrank.com/challenges/java-list/problem?isFullScreen=true)
---
---
- 주석을 참조해주세요!
---
> HackerRank - Javalist (JAVA)

- yunhwan/프로그래머스 전력망을 둘로 나누기
- [프로그래머스 전력망을 둘로 나누기](https://school.programmers.co.kr/learn/courses/30/lessons/86971)
---
- bfs
---
-
1. wires를 그래프 형태로 변환
2. 연결된 송신탑의 개수를 반환하는 bfs 함수 정의
3. wires에 연결되었던 전선을 제거한 뒤, 두 전력망의 차와 answer을 비교해 갱신
4. 전선을 다시 원상복구 시켜준 뒤, 같은 방법으로 wires 순회
5. 가장 작은 전력망 차가 정답
---
> 프로그래머스 전력망을 둘로 나누기

- sollyj/Baekjoon_1929_소수구하기.java
- [백준 1929번 소수구하기](https://www.acmicpc.net/problem/1929)
---
- 수학
- 에라토스테네스의 체
---
- 에라토스테네스의 체 원리
1. 2부터 N까지 배열에 넣는다.
2. 배열을 순회하면서 현재 선택된 숫자의 배수에 해당하는 수를 지운다. (0으로 만듦)
3. 배열에서 0이 아닌 수들이 소수
- 여기서 포인트는 N의 제곱근까지만 for문을 돌린다는 것
N이 서로 다른 수 a * b라고 했을 때 a, b는 N의 제곱근보다 클 수 없다.
---
> Baekjoon_1929_소수구하기

- yunhwan/프로그래머스 가장 큰 수.py
- [프로그래머스 가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746#)
---
- 정렬
---
-
1. num → String으로 바꿔준다.
2. 1000까지의 수이므로,  문자열 비교를 위해 3번을 곱해준 것을 기준으로 내림차순 정렬 
3. 하나의 문자열로 합침
4. 001 같은 경우를 없애기 위해서 숫자로 변환 후 다시 문자로 변환
---
> 프로그래머스 가장 큰 수

- Cobluesky/Programmers - 멀리뛰기.java
- [멀리뛰기](https://school.programmers.co.kr/learn/courses/30/lessons/12914)
---
- DP를 사용했습니다.
---
- 문제를 분석해보면 dp[n]은 항상 dp[n-1] + dp[n-2]로 이루어지는 것을 알 수 있습니다.
- 최대값이 n = 2000 이므로 배열의 길이를 2001로 생성해줍니다.
---
> 2023-02-13 Programmers - 멀리뛰기 (JAVA)

- jiWoo/백준_11053번_가장긴증가하는부분수열.java
- yunhwan/프로그래머스 전력망을 둘로 나누기
- [백준 11503번 가장 긴 증가하는 부분수열](https://www.acmicpc.net/problem/11053)
---
- 다이나믹 프로그래밍
---
- 1) D[i] =1 로 초기화( 자기 자신 하나)
- 2) i를 i+1 ~ 끝까지 비교하며 자기보다 크다면 D[i]+1 값과 D[j] 값 중 큰 값을 넣어준다.
- 3) max로 가장 큰 D 값을 찾아준다
---
> 백준_11053번_가장 긴 증가하는 부분수열

- byeongjoo/백준 5427 불.py
- [백준 1712 - 손익분기점](https://www.acmicpc.net/problem/1712)
---
-  ![image](https://user-images.githubusercontent.com/37494052/218682451-20dbaef8-4a20-4ea1-a00e-cc9892659436.png)
---
- 주석을 참조해주세요.
---
> feat : 2023-02-14 백준 1712 - 손익분기점 (JAVA)

- yunhwan/프로그래머스 롤케이크 자르기
- [프로그래머스 롤케이크 자르기](https://school.programmers.co.kr/learn/courses/30/lessons/132265)
---
- 딕셔너리
---
-
1.  a,b  딕셔너리 생성
2.  전체 토핑을 순회하면서 a에 종류별 토핑의 개수를 넣어줌
3.  전체 토핑을 순회
- b에 종류별 토핑의 개수를 넣어줌
- b에 들어간 토핑을 a에서는 빼줌
- 이 때 a,b의 토핑의 종류의 개수가 같다면 answer+1
4. anwer 반환
---
> 프로그래머스 롤케이크 자르기

- yunhwan/백준 11726 2×n 타일링.py
- [백준 11726 2×n 타일링.](https://www.acmicpc.net/problem/11726)
---
- 다이나믹 프로그래밍
---
-
2x1 일 때 타일 1장
2x2 일 때 타일 2장
2x3 일 때 타일 3장
2x4 일 때 타일 5장
2x5 일 때 타일 8장
f(n) = f(n-1)+f(n-2) 형태를 띄고 있기 때문에,
점화식을 적용하여서 dp 배열을 채워나간 후
가장 마지막 값을 정답으로 반환하였다.
---
> 백준 11726 2×n 타일링

- jiWoo/백준_7562번_나이트의이동.java
- [백준 7562번 나이트의 이동](https://www.acmicpc.net/problem/7562)
---
- 기본적인 BFS
---
- 1) dx, dy 배열에 이동할 방향을 넣어준다.
- 2) 테스트 케이스만큼 bfs를 돌려준다. ( que에는 int [3] 배열로, (x,y,움직인 칸 수) 넣어줬다)
- 주의: 방문 check 해줘서 갔던 곳 또 안가기, 체스판안에 존재하는지 확인- 예전에 병주가 예외문 알려줬던거 같은데 그거 나중에 써볼까?)
---
> 백준 7562번 나이트의 이동 - BFS

- Cobluesky/hackerrank - nested_list.py
> Cobluesky patch 1

- jiWoo/백준_1697번_숨바꼭질.java
- yunhwan/프로그래머스 가장 큰 수.py
- yunhwan/프로그래머스 롤케이크 자르기
- [백준 1697번 숨바꼭질](https://www.acmicpc.net/problem/1697)
---
- BFS
---
- BFS를 사용해서 1초씩 움직이는 위치와 시간을 큐에 집어 넣으며 확인
- -1, +1, *2하는 위치와 시간을 que에 넣어주고 동생의 위치에 왔을 때 시간을 출력해준다! 
---
> 백준 1697번 숨바꼭질

- jiWoo/프로그래머스_괄호회전하기.java
- jiWoo/프로그래머스_뒤에있는큰수찾기.java
- yunhwan/백준 11726 2×n 타일링.py
- [프로그래머스 뒤에 있는 큰 수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/154539)
---
- stack
---
- 스택에 numbers의 index를 넣어줄 용도
- 1) numbers 반복문을 돌려주는데 스택이 비어있거나 현재값이 전 값보다 작으면 스택에 넣어준다.
- 2) 현재값이 전 값보다 크다면 스택이 비거나 스택에 있던 값들이 현재값보다 작은 것들을 빼서 답에 넣어준다.
- 3) 남은 것들은 더 큰 값이 없는 것이므로 -1 저장
---
> 프로그래머스 뒤에있는큰수찾기

- jiWoo/프로그래머스_괄호회전하기.java
- yunhwan/백준 11726 2×n 타일링.py
- [프로그래머스 괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
---
- Stack
---
- s 문자열의 크기만큼 회전해준다 앞에 문자를 뒤로 붙여주며!
- ok 메서드를 사용해서 올바른 문자열인지 확인해주기
- 스택에 괄호를 열려있는 괄호는 넣고 닫는 괄호면 스택 맨 위에 있는 것이 같은 괄호면 pop해서 스택이 비어있으면 올바른 괄호
---
> 프로그래머스_괄호회전하기

- jiWoo/프로그래머스_귤고르기.java
- [프로그래머스 귤 고르기](https://school.programmers.co.kr/learn/courses/30/lessons/138476)
---
- 리스트 내림차순 정렬
---
- HashMap value 값을 내림차순 정렬으로 풀었는데 저런 정렬 자꾸 혼자 못품 구글한테 물어봄 에휴 근데 또 나중에 풀어도 볼 듯 에휴 
---
> 프로그래머스 귤 고르기 hashMap

- sollyj/Baekjoon_18352_특정거리의도시찾기.java
- [백준 18352번 특정거리의도시찾기](https://www.acmicpc.net/problem/18352)
---
- 그래프
- 탐색
---
- 도로 그래프를 인접리스트로 구현한다.
- 너비우선탐색(BFS)으로 방문횟수를 카운트한다.
- 방문횟수가 K와 같은 노드를 찾아서 answer배열에 넣는다.
- answer배열을 오름차순하여 출력한다.
---
> Baekjoon_18352_특정거리의도시찾기

- hyeonwoo/Python/프로그래머스/프로그래머스 뒤에 있는 큰 수 찾기.py
- [프로그래머스 뒤에 있는 큰 수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/154539?language=python3)
---
- 스택
---
- `numbers` 배열의 길이만큼 `answer` 배열을 `-1`로 미리 채우고, 뒷 큰 수가 있는 숫자들은 `-1`에서 뒷 큰 수로 바꾸려고 한다.
- `numbers` 배열에 담긴 현재 숫자와 뒤에 있는 숫자들을 비교하기 위해 `while`문에 조건을 걸어두었다.
- 스택이 비어있지 않거나 스택의 마지막 값에 위치한 숫자보다 현재 숫자가 더 크다면 스택의 마지막을 `pop` 해준 후, `answer` 배열에 `pop`한 인덱스에 현재 숫자를 넣어준다.
- 스택이 비어있거나 스택의 마지막(`number` 배열의 인덱스) 값에 위치한 숫자와 현재 숫자를 비교하여 현재 숫자가 더 작다면 스택에 현재 숫자의 인덱스 값을 추가한 후 `while`문 종료
---
> 프로그래머스 뒤에 있는 큰 수 찾기

- leejooh/프로그래머스 약수의 합.py
- leejooh/프로그래머스 자릿수 더하기.py
- leejooh/프로그래머스 자연수 뒤집어 배열로 만들기.py
- leejooh/프로그래머스 짝수와 홀수.py
- leejooh/프로그래머스 평균 구하기.py
- [프로그래머스 약수의 합](https://school.programmers.co.kr/learn/courses/30/lessons/12928)
- [프로그래머스 자릿수 더하기](https://school.programmers.co.kr/learn/courses/30/lessons/12931)
- [프로그래머스 자연수 뒤집어 배열로 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12932)
- [프로그래머스 짝수와 홀수](https://school.programmers.co.kr/learn/courses/30/lessons/12937)
- [프로그래머스 평균 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/12944)
---
- 구현
---
- 블로그 참고해주세요 ㅎ.ㅎ
- [프로그래머스 약수의 합](https://leejooh.tistory.com/69)
- [프로그래머스 자릿수 더하기](https://leejooh.tistory.com/68)
- [프로그래머스 자연수 뒤집어 배열로 만들기](https://leejooh.tistory.com/72)
- [프로그래머스 짝수와 홀수](https://leejooh.tistory.com/71)
- [프로그래머스 평균 구하기](https://leejooh.tistory.com/70)
---
> 프로그래머스 자연수 뒤집어 배열로 만들기 외 4문제

- taejun/baekjoon/10810.java
- [백준 2493번 탑](https://www.acmicpc.net/problem/10810)
---
- 1차원 배열을 활용하여 구현하였습니다. 
---
공 넣기문제는 정해진 배열에 값을 넣기만 하면 되는 간단한 문제이다.
N개의 바구니에 M번만큼 공을 집어 넣을 수 있고, 연속된 바구니에 같은 번호가 적힌 공을 집어넣어야 한다.
예제 테스트케이스처럼 N개의 바구니가 준비되어 있고, i부터 j번째 바구니까지 k번호가 적힌 공을 M번만큼 집어넣으면 된다.
이 솔루션을 **1차원 배열**로 풀어내면 된다.
- N개의 길이를 가지는 배열을 준비한다.
- M번 횟수만큼 배열에 값을 설정한다.
- 배열의 (i-1)번째부터 (j-1)번째 인덱스까지 순회하면서 k 값을 삽입하면 된다.
- **바구니는 1번째 부터 시작하지만 배열의 인덱스는 0부터 시작**하기 때문이다.
이제 코드를 작성해보자.
```java
StringTokenizer st = new StringTokenizer(br.readLine());
int N = Integer.parseInt(st.nextToken());
int M = Integer.parseInt(st.nextToken());
int[] arr = new int[N];
```
먼저 StringTokenizer를 통해 공백 기준으로 N과 M을 입력받고 N개의 크기를 가지는 정수 배열을 초기화하자.
```java
for(int idx=0; idx<M; idx++) {
st = new StringTokenizer(br.readLine());
int i = …
```
> 백준 10810 공 넣기

- paduck/hackerRank/permutingTwoArrays.js
- [해커랭크 permuting two arrays](https://www.hackerrank.com/challenges/three-month-preparation-kit-two-arrays)
---
- ?
---
- 여기에 작성해 주세요.
두 배열의 순열이라는 제목으로 주어지지만
예제로 주어지는 케이스는 오름차순 정렬된 배열 과 내림차순 정렬된 배열만 확인
예제 그대로 첫 번째 배열은 오름차순 정렬하고
두 번째 배열은 내림차순 정렬해서
배열의 크기만큼 반복문을 돌려, 각 배열의 동일한 인덱스 값을 더해서
문제에서 주어지는 k 값보다 작은 케이스가 있을 경우 NO를 반환하며 종료
단 하나의 케이스도 없을 경우 YES를 반환한다
---
> feat: HackerRank Permuting Two Arrays

- Cobluesky/HackerRank - Pangram.py
- [HackerRank - Pangram](https://www.hackerrank.com/challenges/one-month-preparation-kit-pangrams/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=one-month-preparation-kit&playlist_slugs%5B%5D=one-month-week-one&h_r=next-challenge&h_v=zen)
---
- Set를 사용했습니다.
---
- Pangram이란 알파벳이 A ~ Z까지 모두 들어간 문장을 뜻합니다.
- 기본적으로, Set는 중복을 허용치 않으므로 문장 전체를 순회하며 전부 추가하면 문장에 존재하는 알파벳이 하나씩 들어가게 될 것입니다.
- 최종적으로, Set의 원소 개수가 알파벳 전체 개수인 26개와 같으면 Pangram입니다.
---
> HackerRank - Pangram

- paduck/hackerRank/subarrayDivision2.js
- [해커랭크 subarray division2](https://www.hackerrank.com/challenges/three-month-preparation-kit-the-birthday-bar/)
---
- ?
---
<strong>다른 풀이 방법이 있을 것 같은데...</strong>
주어지는 s 배열에서, m 개수만큼 뽑아내 d 를 만들 수 있는지 찾는 문제
1차적으로 생각했을 때는, m 개수가 되는 모든 조합을 찾아내 몇 번 d를 만들 수 있는지 알아내는 문제인 줄 알았지만
그냥 s 배열을 끝까지 탐색해가면서, m개씩 자르는 경우만 찾아내도 정답으로 인정되는 문제였던 것이다...?
<hr />
1) 결국, s 배열을 순회하면서  <br>
2) m개만큼 배열을 잘라내어  <br>
3) 이를 reduce를 통해 누적 합계를 구하고  <br>
4) 이것이 d와 같을 경우  <br>
5) 횟수를 증가시킨다
---
> feat: 해커랭크 subarray division2

- hyeonwoo/Python/프로그래머스/프로그래머스 콜라츠 추측.py
- [프로그래머스 콜라츠 추측](https://school.programmers.co.kr/learn/courses/30/lessons/12943)
---
- 구현
---
- 제한 사항에 따라 반복문을 500번 수행
- 반복 변수 `chk`를 확인하여 500번 시도해도 1이 되지 않는다면 `-1`을 반환
- 반복문 안에서 입력 받은 수가 짝수인 경우 2로 나누고, 홀수인 경우 3을 곱한 후 1을 더하는 작업을 수행하고 작업이 수행될 때마다 `answer`에 `1`씩 더해준다.
- 반복된 작업을 통해 입력 받은 수가 `1`이 되는 경우 반복문을 종료 후 `answer`를 리턴한다.
- 처음부터 입력 받은 수가 `1`일 경우, 반복문이 바로 종료되고 `answer` 변수는 `0`으로 이미 선언돼있기 때문에 `0`을 리턴한다.
---
```python
def solution(num):
answer = 0
for chk in range(1, 500 + 1):
if chk == 500:
return -1
if num == 1:
break
elif num % 2 == 0:
num //= 2
answer += 1
elif num % 2 == 1:
num = (num * 3) + 1
answer += 1
return answer
```
> 프로그래머스 콜라츠 추측

- hyeonwoo/Python/프로그래머스/프로그래머스 [1차] 비밀지도.py
- [프로그래머스 [1차] 비밀지도](https://school.programmers.co.kr/learn/courses/30/lessons/17681#)
---
- 구현
- 비트 연산
- 문자열
---
- 지도는 `공백(" ")` 또는 `벽("#")`으로 이루어져있다.
- `지도1`과 `지도2`를 겹쳤을 때, ***어느 하나라도 벽인 부분은 전체 지도에서 벽***이고, ***모두 공백이면 전체 지도에서 공백***이다.
- 지도의 각 칸은 정수 배열로 암호화돼있고, 각 정수 배열의 원소를 2진수로 바꾸었을 때, `0`이면 `공백(" ")`, `1`이면 `벽("#")`이다.
- 해독한 지도를 겹친다고 생각했을 때(**2진수로 바꾼 각 배열의 원소를 비교**),
- "***어느 하나라도 벽인 부분은 전체 지도에서 벽***"이란 말은, 두 2진수 중 어느 하나라도 `1`일 때 `1`이다.
- "***모두 공백이면 전체 지도에서 공백***"이란 말은, 두 2진수가 모두 `0`일 때 `0`이다.
- 이는 OR 연산의 진리표와 같다.
|지도1|지도2|겹친 지도|X|Y|OUT|
|-|-|-|-|-|-|
|공백|공백|공백|0|0|0|
|공백|벽|벽|0|1|1|
|벽|공백|벽|1|0|1|
|벽|벽|벽|1|1|1|
- 이를 바탕으로 각 정수 배열의 OR 연산 결과를 2진수 형태의 문자열로 변환하여 `target` 배열에 저장한다.
- 이제 위에서 구한 2진수의 `0`과 `1`을 `공백`과 `벽`으로 바꿔주면 되는데, 각 2진수의 자릿수가 다르기 때문에 이를 맞춰주어야 한다.
- 예를 들어, `101`과 `1`과 같은 2진수를 …
> 프로그래머스 [1차] 비밀지도

- paduck/hackerRank/xorStrings3.js
- [HackerRank XOR Strings 3](https://www.hackerrank.com/challenges/three-month-preparation-kit-strings-xor/)
---
- 비트연산
---
<strong>아마 자스로 못 푸는 문제이지 않을까</strong>
조건1) 문제에서 주어진 strings_xor() 함수에서 특정 부분을 변경해
조건2) xor 연산을 수행하는 함수 만들기
- 일단 문제에서 주어진 strings_xor 함수가 없어서 만들었고
- 출력값은 동일한데 정답 인정이 되지 않는 중인거시다...
---
> feat: hackeRank xor Strings 3

- kkkwp/hackerRank/a_very_big_sum.py
- kkkwp/hackerRank/birthday_cake_candles.py
- kkkwp/hackerRank/compare_the_triplets.py
- kkkwp/hackerRank/diagonal_difference.py
- kkkwp/hackerRank/mini-max_sum.py
- kkkwp/hackerRank/plus_minus.py
- kkkwp/hackerRank/simple_array_sum.py
- kkkwp/hackerRank/solve_me_first.py
- kkkwp/hackerRank/staircase.py
- kkkwp/hackerRank/time_conversion.py
- [해커랭크 solve me first](https://www.hackerrank.com/challenges/solve-me-first/problem?isFullScreen=true)
- [해커랭크 simple array sum](https://www.hackerrank.com/challenges/simple-array-sum/problem?isFullScreen=true)
- [해커랭크 compare the triplets](https://www.hackerrank.com/challenges/compare-the-triplets/problem?isFullScreen=true)
- [해커랭크 a very big sum](https://www.hackerrank.com/challenges/a-very-big-sum/problem?isFullScreen=true)
- [해커랭크 diagonal difference](https://www.hackerrank.com/challenges/diagonal-difference/problem?isFullScreen=true)
- [해커랭크 plus minus](https://www.hackerrank.com/challenges/plus-minus/problem?isFullScreen=true)
- [해커랭크 staircase](https://www.hackerrank.com/challenges/staircase/problem?isFullScreen=true)
- [해커랭크 mini-max …
> 해커랭크 wrapup 10문제

- hyeonwoo/Python/해커랭크/해커랭크 XOR Strings 3.py
- [해커랭크 XOR Strings 3](https://www.hackerrank.com/challenges/three-month-preparation-kit-strings-xor/problem?isFullScreen=true)
---
- 구현
---
- 원본 코드의 잘못된 부분을 수정하여 주어진 케이스에 정상적으로 돌아가게끔 수정하는 문제
- 코드 라인을 추가하거나 삭제할 수 없고, 최대 3줄의 코드를 수정할 수 있다.
```python
def strings_xor(s, t):
res = ""
for i in range(len(s)):
if s[i] = t[i]:
res = '0';
else:
res = '1';
return res
s = input()
t = input()
print(strings_xor(s, t))
```
- 문제는 2진수의 XOR 연산 결과를 요구하고 있다.
- XOR 연산은 서로 다른 입력을 받은 경우, `1`을 출력한다.
- 따라서, 주어진 원본 코드에서 조건식을 `=`에서 `!=`로 바꿔 서로 다른 경우 조건으로 수정하고, 결과값에 입력값이 서로 다를 경우 `'1'`을 추가하고, 같을 경우 `'0'`을 추가하도록 수정했다.
```python
def strings_xor(s, t):
res = ""
for i in range(len(s)):
if s[i] != t[i]: # original code: if s[i] = t[i], modify: = -> !=
res += '1'; # original code: res = '0', modify: = '0' -> += '1'
else: …
```
> 해커랭크 XOR Strings 3

- taejun/programmers/가장가까운같은글자.java
- [프로그래머스 가장 가까운 같은 글자](https://school.programmers.co.kr/learn/courses/30/lessons/142086)
---
- 이번 문제는 **HashMap을 활용**한다면 간단하게 풀 수 있다.
---
이번 문제는 **HashMap을 활용**한다면 간단하게 풀 수 있다.
주어진 s의 각 문자별로 HashMap에 존재여부를 검증하도록 구현하면 된다.
- HashMap에 존재하지 않는 문자라면, HashMap에 현재 문자와 인덱스 값을 집어넣고 answer 배열에 -1을 삽입한다.
- HashMap에 존재하는 문자라면, **가장 가까운 글자의 인덱스가 HashMap에 삽입**되어 있을 테니 `[현재 문자의 인덱스 - 가장 가까운 문자의 인덱스]`의 결과를 answer 배열에 삽입한 후, HashMap의 현재 문자와 인덱스 값을 집어넣는다.
아이디어를 토대로 바로 코드를 작성해보자.
```java
int[] answer = new int[s.length()];
HashMap<String, Integer> hm = new HashMap<>();
```
가장 가까운 글자의 위치를 담을 answer 배열을 만들고 s의 길이를 가지도록 초기화한다.
그리고 s의 문자와 인덱스 값을 담을 HashMap을 생성하자.
```java
for(int i=0; i<s.length(); i++) {
String str = Character.toString(s.charAt(i));
if(hm.get(str) == null) {
hm.put(str, i);
answer[i] = -1;
} …
```
> 프로그래머스 가장 가까운 같은 글자

- Cobluesky/HackerRank - Permuting Two Arrays.py.py
- [HackerRank - Permuting Two Arrays](https://www.hackerrank.com/challenges/two-arrays/problem?)
---
- Greedy를 사용했습니다.
- Timsort를 사용했습니다.
---
- 배열 2개를 치환해서 A'[i] + B'[i] >= k를 만족하면 "Yes", 그렇지 않으면 "No"를 반환하는 문제입니다.
- 결국 최소합을 체크하는 문제이므로, 하나의 배열은 오름차순으로, 나머지는 내림차순으로 정렬한 후 더하여 체크하면 됩니다.
- 여기서는 sorted를 썼지만 sort를 쓴다면 더 빠를 것입니다.
---
> feat : HackerRank - Permuting Two Arrays

- paduck/hackerRank/stringsQuestion.js
- [hackerrank super reducing string](https://www.hackerrank.com/challenges/reduced-string?isFullScreen=true)
- [hackerrank strong password](https://www.hackerrank.com/challenges/strong-password?isFullScreen=true)
- [hackerrank two characters](https://www.hackerrank.com/challenges/two-characters?isFullScreen=true)
- [hackerrank caesar cipher](https://www.hackerrank.com/challenges/caesar-cipher-1?isFullScreen=true)
- [hackerrank mars exploration](https://www.hackerrank.com/challenges/mars-exploration?isFullScreen=true)
---
- 문자열
---
- 한 문제 이상으로 주석 참고 부탁드림
- 혹시 해커랭크 implementation 문제 어떤지 아시는 분~
---
> feat: 프로그래머스 문자열 문제 5개

- jiWoo/프로그래머스_위장.java
- [프로그래머스 위장](https://school.programmers.co.kr/learn/courses/30/lessons/42578)
---
- 조합?
---
- 의상의 종류별로 hashmap에 저장해서 개수를 구해줬다(여기서 0개일 때도 넣어주기 위해 +1을 해줌)
- 음 모든 개수를 서로 곱해줌! 이거 머더라 그리고 0개일 때도 넣어줘서 모든 의상이 0개일 때를 빼줌! 
---
> 프로그래머스 위장- 조합?

- hb/프로그래머스 같은 수는 싫어.py
- hb/프로그래머스 나머지가 1이되는 수 구하기.py
- hb/프로그래머스 내 마음대로 문자열 정렬하기.py
- hb/프로그래머스 문자열 정수로 바꾸기.py
- hb/프로그래머스 비밀지도.py
- hb/프로그래머스 삼총사.py
- hb/프로그래머스 이상한 문자 만들기.py
- hb/프로그래머스 최소공배수 최대공약수.py
- hb/프로그래머스 최소직사각형.py
- 프로그래머스 문자열 내 마음대로 정렬하기 (https://school.programmers.co.kr/learn/courses/30/lessons/12915)
- 나머지 주석 참고
---
- 구현
---
- 유효성 검사는 무시하고, key - value 값의 형태로 문제 해결을 위해서 문자열로 이뤄진 strings 배열의 각 요소의 n 번째 index 값을 key로 사용하기 위해서 key 배열 생성하고 key 의 중복허용을 위해서 tuple로 key -  value 데이터로 전환 후 key를 기준으로 정렬하고 key 가 같다면 value를 기준으로 정렬하도록 sort (이를 위해서 list로 다시 변환) 이후 value 만 answer 에 삽입해 반환
---
> 프로그래머스 문자열 내 마음대로 정렬하기 외 8 문제

- kkkwp/programmers/같은_숫자는_싫어.py
- kkkwp/programmers/기능개발.py
- kkkwp/programmers/올바른_괄호.py
- kkkwp/programmers/프린터.py
- [프로그래머스 같은 숫자는 싫어](https://school.programmers.co.kr/learn/courses/30/lessons/12906)
- [프로그래머스 기능개발](https://school.programmers.co.kr/learn/courses/30/lessons/42586)
- [프로그래머스 올바른 괄호](https://school.programmers.co.kr/learn/courses/30/lessons/12909)
- [프로그래머스 프린터](https://school.programmers.co.kr/learn/courses/30/lessons/42587)
---
- stack, queue, deque
---
- [프로그래머스 같은 숫자는 싫어](https://chxrryda.tistory.com/233)
- [프로그래머스 기능개발](https://chxrryda.tistory.com/234)
- [프로그래머스 올바른 괄호](https://chxrryda.tistory.com/235)
- [프로그래머스 프린터](https://chxrryda.tistory.com/236)
---
> 프로그래머스 스택/큐 4문제

- hb/프로그래머스 k번째 수.py
- hb/프로그래머스 두 개 뽑아서 더하기.py
- hb/프로그래머스 숫자 문자열과 영단어.py
- hb/프로그래머스 크기가 작은 부분 문자열.py
- 프로그래머스 k 번째 수 https://school.programmers.co.kr/learn/courses/30/lessons/42748
- 나머지 링크 주석 참고
---
- 구현
---
문자열 t 를 0 부터 len(p) + i 만큼 슬라이싱 -> t에 대한 인덱싱 시작을 0 부터 i 까지 길이는 len(p) 만큼 유지하기 위해서
이 길이가 len(p) 와 같을 때까지 (문자열에 끝에 다다를 수록 len(p) 보다 작아짐 len(p) + i > len(p) 인 경우 부터는 슬라이싱 반영 안되고 무시(t의 끝까지만))
이 때 t를 인덱싱한 길이가 len(p) 과 같고 p 보다 작으면 count ++
---
> 프로그래머스 k 번째 수  외 3 문제

- Gyuminn/hackerank/string/Caesar_Cipher.js
- [해커랭크 Caesar Cipher](// https://www.hackerrank.com/challenges/caesar-cipher-1/problem)
---
- charCodeAt() 메서드, String.fromCharCode() 메서드
---
- 코드 주석을 참고해 주세요.
---
> (해커랭크 Easy-String) Caesar Cipher

- jiWoo/프로그래머스_소수찾기.java
- jiWoo/프로그래머스_전화번호목록.java
- jiWoo/프로그래머스_카펫.java
- [프로그래머스 전화번호 목록](https://school.programmers.co.kr/learn/courses/30/lessons/42577)
---
- 정렬
---
- 1) 숫자로 구성된 문자열 배열을 정렬하면 사전순으로 정렬된다.
- 2) 그렇다면 해당 전화번호와 그 다음 전화번호만 비교해도 충분하다(여기서 주의할 점은 길이를 비교해준다. "1234", "2" 이런식으로 정렬될 수 있으므로)
- > 해시 문제인데 다른 사람들이 해시로 어케 풀었는지 지곰 풀리하고 보겠습니다람쥐, 아 맞다 이것도 컄.. 난 시간 초과 나와서 유난이가 정렬하고 풀라고 알려줌 컄 유난이 고마버
---
> 프로그래머스 전화번호목록

- jiWoo/프로그래머스_카펫.java
- [프로그래머스 카펫](https://school.programmers.co.kr/learn/courses/30/lessons/42842)
---
- 완전 탐색
---
- x는 세로 값 y를 가로 값으로 했을 때 2y+2x-4= brown, (x-2))y-2)=yellow로 식을 구해서 다 돌려서 탐색함!
---
> 프로그래머스 카펫- 완전탐색

- jiWoo/프로그래머스_소수찾기.java
- jiWoo/프로그래머스_카펫.java
- [프로그래머스 소수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/42839)
---
- 완전 탐색
---
- 컄 답 봄; 컄 
- numbers의 길이만큼의 숫자를 만들 수 있으므로 1자리부터 numbers의 길이만큼의 숫자를 재귀를 사용하여 하나씩 숫자를 조합해줌(여기서 체크해야할 거 사용한 숫자인지와 체크했던 중복 소수인지 확인)
---
> 프로그래머스 소수찾기

- hb/프로그래머스 콜라 문제.py
- hb/프로그래머스 푸드 파이트 대회.py
- [프로그래머스 콜라 문제](https://school.programmers.co.kr/learn/courses/30/lessons/132267)
- [프로그래머스 푸드 파이트 대회](https://school.programmers.co.kr/learn/courses/30/lessons/134240)
---
- 구현
---
- 주석 참고
---
> 프로그래머스 콜라문제  외 1 문제

- jiWoo/강사님_그룹애너그램.java
---
- 정렬, hash
---
input (초기 문자열 배열) , temp(정렬된 문자열 배열)-> 여기서 정렬을 각각 문자열을 정렬한 것
- 1) input에 문자열 각각을 char 배열에 다시 담아 정렬한 후 다시 String 배열(temp)로 받아줬다. (ex: {"eat", "tea", "tan", "ate", "nat", "bat"} -> {"aet", "aet", "ant", "ant", "abt"} )
- 2) temp 값을 hash 키로 넣고 value 리스트 값에 input 해당 값을 넣어준다.
- 3) hashmap의 value를 리스트로 변환
---
> 강사님- 그룹 애너그램/ 정렬, hash

- kkkwp/programmers/H-Index.py
- kkkwp/programmers/K번째수.py
- kkkwp/programmers/가장_큰_수.py
- [프로그래머스 K번째수](https://school.programmers.co.kr/learn/courses/30/lessons/42748)
- [프로그래머스 가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746)
- [프로그래머스 H-Index](https://school.programmers.co.kr/learn/courses/30/lessons/42747)
---
- 정렬
---
- [프로그래머스 K번째수](https://chxrryda.tistory.com/237)
- [프로그래머스 가장 큰 수](https://chxrryda.tistory.com/238)
- [프로그래머스 H-Index](https://chxrryda.tistory.com/239)
---
> 프로그래머스 정렬 3문제

- jiWoo/정렬된리스트병합.java
---
- 정렬
---
- 2차원 배열을 탐색하며 리스트에 넣고 리스트를 정렬한다.
---
> 강사님- 정렬된 리스트 병합

- kkkwp/programmers/모의고사.py
- kkkwp/programmers/소수_찾기.py
- kkkwp/programmers/최소직사각형.py
- kkkwp/programmers/카펫.py
- [프로그래머스 최소직사각형](https://school.programmers.co.kr/learn/courses/30/lessons/86491)
- [프로그래머스 모의고사](https://school.programmers.co.kr/learn/courses/30/lessons/42840)
- [프로그래머스 소수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/42839)
- [프로그래머스 카펫](https://school.programmers.co.kr/learn/courses/30/lessons/42842)
---
- 완전탐색
---
- [프로그래머스 최소직사각형](https://chxrryda.tistory.com/240)
- [프로그래머스 모의고사](https://chxrryda.tistory.com/241)
- [프로그래머스 소수 찾기](https://chxrryda.tistory.com/242)
- [프로그래머스 카펫](https://chxrryda.tistory.com/243)
---
> 프로그래머스 완전탐색 4문제

- hb/프로그래머스 가장 가까운 같은 글자.py
- hb/프로그래머스 폰켓몬.py
- [프로그래머스 폰켓몬](https://school.programmers.co.kr/learn/courses/30/lessons/1845)
- [프로그래머스 가장 가까운 글자](https://school.programmers.co.kr/learn/courses/30/lessons/142086)
---
- 1. 구현(set 사용)
- 2. 구현(dict, enumerate 사용)
---
- 주석 참고
---
> 폰켓몬   외 1 문제

- taejun/programmers/괄호회전하기.java
- [프로그래머스 괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
---
- 문자열과 Stack(스택)을 활용하는 구현 문제입니다.
---
이번 `괄호 회전하기` 문제는 **괄호를 검증**하는 것이 가장 주요하다고 볼 수 있다.
그런데, 그냥 하나의 소괄호 `()`만 검증하는 것이 아니라 중괄호 `{}`와 대괄호 `[]` 까지 올바른 괄호대로 포함되어 있는지를 확인해야 한다.
- 먼저 주어진 괄호 문자열을 왼쪽으로 한 문자씩 문자열 길이만큼 회전시킨다.
- 문자열의 길이와 반복문 인덱스를 활용하여 문자열을 회전시킨다.
- 왼쪽으로 한 문자씩 회전시킨 문자열마다 올바른 괄호 문자열인지를 검증한다.
- 주어진 문자열을 회전시켜서 만들어진 문자열마다 올바른 괄호 문자열인지를 세어서 반환하면 된다.
아이디어는 이외로 단순하다. 바로 코드를 작성해보자.
```java
for(int i=0; i<s.length(); i++) {
String rotate = s.substring(i, s.length()) + s.substring(0, i);
}
```
먼저 주어진 문자열 s를 가지고 왼쪽으로 한 문자씩 회전시키기 위해서 `substring()` 메소드를 사용한다.
s의 길이만큼 반복하며 **현재 인덱스에서 문자열 길이만큼 자른 뒤, 0번째부터 현재 인덱스까지 자른다면**, 왼쪽으로 하나씩 회전된 문자열을 만들 수 있게 된다.
> _예를 들어 `(){}[]` 라는 예제를 보면 `){}[](`로 회전하기 위해 `){}[]`와 `(`를 …
> 프로그래머스 괄호 회전하기

- jiWoo/프로그래머스_거리두기확인하기.java
- [프로그래머스 거리두기 확인하기](https://school.programmers.co.kr/learn/courses/30/lessons/81302#)
---
- BFS
---
- 대기실에서 P 전부의 좌표와 P가 움직인 거리(초깃값: 0)를 큐(p_que)에 넣어준다. 
- 시작 P를 확인하는 것을 막기 위해 boolean[][] visited로 확인해준다. 
- que는 P부터 깊이 우선 탐색하기 위한 큐
- BFS
1) p가 들어있던 p_que가 빌 때까지 반복
2) que가 비면 p 값을 넣어준다.
3) 시작 P일 때는 visited를 초기화하고 시작 P의 값을 확인해준다.
4) 4방향을 탐색하며 P이면 거리두기 실패로 BFS를 종료하고 P가 아니고 P로부터의 거리가 1이라면 que에 넣어준다.
---
> 프로그래머스 거리두기 확인하기

- yunhwan/프로그래머스 전화번호 목록.py
- [프로그래머스 전화번호 목록](https://school.programmers.co.kr/learn/courses/30/lessons/42577)
---
- 정렬
---
-
1. 문자열 정렬시키기
2. 순회를 하면서 현재 전화번호의 길이만큼 다음 문자열을 자른 후,
자른 다음 전화번호에 현재 전화번호가 있는지 확인
3. 있을 경우 False, 없을 경우 2반복
---
> 프로그래머스 전화번호 목록

- hyeonwoo/Python/프로그래머스/프로그래머스 이상한 문자 만들기.py
- [프로그래머스 이상한 문자 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12930)
---
- 문자열
---
- 한 개 이상의 단어로 구성된 문자열에서, 단어의 홀수번째 알파벳은 소문자로, 짝수번째 알파벳은 대문자로 바꿔주는 문제이다.
- 먼저, 홀수와 짝수를 확인해주기 위한 함수 `is_odd(number)`와 `is_odd(number)`를 각각 만들어주었다.
- 몇 번째 문자인지 확인해주기 위한 변수 `idx`를 `0`으로 만들어 준 뒤 문자열을 순회한다.
- 문자가 공백이라면 `idx`를 `0`으로 만들어 준 뒤 반복문을 건너뛴다.
- 문자가 단어의 홀수번째라면 소문자로 바꿔주고, 짝수번째라면 대문자로 바꿔준 뒤 `idx` 변수를 증가시켜준다.
---
```python
def is_odd(number):
return number % 2 == 1
def is_even(number):
return number % 2 == 0
def solution(s):
answer = ''
idx = 0
for character in s:
if character == " ":
answer += character
idx = 0
continue
if is_odd(idx):
answer += character.lower()
if is_even(idx):
answer += character.upper()
idx += 1
return answer
```
> 프로그래머스 이상한 문자 만들기

- hyeonwoo/Python/프로그래머스/프로그래머스 JadenCase 문자열 만들기.py
- [프로그래머스 JadenCase 문자열 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12951?language=python3)
---
- 문자열
---
- **JadenCase**는 모든 단어의 첫 문자가 대문자이고, 그 외의 알파벳은 소문자인 문자열을 말한다.
- 예를 들어, `"coding test"`를 `"Coding Test"`와 같이 바꿔주면 된다.
- 단, 단어의 첫 문자가 숫자일 경우 모두 소문자로 작성하면 된다.
- 예를 들어, `"3pepole unFollowed me"`는 `"3people Unfollowed Me"`가 된다.
- 문자열 `s`를 순회하면서 공백과 숫자로 구분하여 공백이 나온 뒤에 문자는 대문자로 작성하고, 숫자가 나온 뒤에 문자는 소문자로 작성하는 식으로 문제를 접근했다.
- 이를 위해 공백을 체크하기 위한 변수 `space_chk`를 만들었고, 여기서 공백을 체크하기 위한 변수에는 초기값을 `1`로 두어 첫 번째 문자(`"First"`)에 대해서도 대문자로 작성할 수 있게 했다.
1. 문자가 공백(`" "`)이라면 공백 체크용 변수에 `1`을 더해 체크해주고, 다음 반복문을 진행한다.
2. 공백 체크용 변수가 `0`보다 클 경우, 단어의 첫 문자이므로 대문자로 작성한다.
3. 문자가 숫자인 경우를 판별하기 위해 `ord("1")`을 이용해 문자열의 아스키 코드값을 확인하여 이 값이 `65`보다 작다면 숫자인 것을 알 수 있다.
1. 이를 이용해 문자가 숫자인 경우 다음 반복문으로 바로 건너뛴다.
4. …
> 프로그래머스 JadenCase 문자열 만들기

- sollyj/programmers/Programmers_이상한문자만들기.java
- [프로그래머스 이상한 문자 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12930)
---
- 문자열
---
1. 공백을 기준으로 나눈 단어를 리스트에 저장한다.
`split(" ")` 로 하니까 테스트케이스 몇개가 계속 통과가 안됐다.
`split(" ", -1)` 로 해야 성공
내 생각은 `split(" ")` 로 하면 문자열 맨뒤의 공백을 카운트 안해줘서 그런듯 하다.
통과 못한 테스트케이스가 맨뒤의 공백과 관련되어있지 않을까 생각..🤔
2. 리스트를 돌면서 문제 조건에 따라 mapping하여 새로운 문자열 스트림으로 반환한다.
stream의 map메서드 씀
3. answer에 저장 후 답 출력!
---
> Programmers 이상한 문자 만들기

- sollyj/programmers/Programmers_시저암호.java
- [프로그래머스 시저암호](https://school.programmers.co.kr/learn/courses/30/lessons/12926)
---
- 문자열
---
- 아스키코드표를 따르되, `z` 와 `Z` 일때는 다시 `a` 와 `A` 로 돌아줘야한다.
---
> Programmers_시저암호

- yunhwan/프로그래머스 소수찾기.py
- [프로그래머스 소수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/42839)
---
- 조합
---
-
1. numbers로 생성할 수 있는 모든 조합 생성
2. 숫자로 반환 시키기
3. 중복되는 숫자를 제거하기
4. 소수를 판별하여 개수 세주기
---
> 프로그래머스 소수 찾기

- jiWoo/프로그래머스_연속부분수열의합의개수.java
- [프로그래머스 연속 부분 수열의 합의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/131701)
---
- 해시..?  수열
---
- 3중..for문 사용해서 기분이 좀 그럼 
- 구해야할 부분 수열이 1개, 2개~ elements.length이므로 가장 바깥 for문은 자를 부분 수열의 크기
- 두번째 for문은 i개 크기의 부분 수열의 시작할 index
- 세번째 for문에서 부분수열의 합을 구해줬다. 여기서 원형을 생각해서 index가 len 이상일 때를 주의해줬다.
- 세번째 for문에서 구한 sum을 set에 넣어 중복 제거!
- answer은 set의 사이즈!
- 좀따 유난이의 풀이 참고하겠다!! 컄 
---
> 강사님- 연속 부분 수열의 합의 개수

- yunhwan/프로그래머스 연속 부분 수열 합의 개수.py
- [프로그래머스- 연속 부분 수열 합의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/131701)
---
- 투 포인터
---
-  원형수열
1.  dp 생성 및 설정
2. 부터 수열의 개수만큼 부분수열을 구해줌
3.  부분수열의 합을 dp를 이용하여 result에 추가
4.  result를 set로 만들어서 중복제거 후, 개수 구하기
---
> 프로그래머스 연속 부분 수열 합의 개수

- jiWoo/강사님_보석과돌.java
---
- 리스트
---
``` java
public static int solution(String jewels, String stones){
int result=0;
char [] jew=jewels.toCharArray();
HashMap<Character, Integer> map=new HashMap<>();
for(char c: jew){ // jewels에 포함된 문자 hash에 넣기
map.put(c,0);
}
char [] st=stones.toCharArray();
for(char c: st){ // stone에 문자가 jewels에 있다면 개수 +1
if(map.containsKey(c)){
map.put(c,map.get(c)+1);
}
}
ArrayList<Integer> count=new ArrayList<>(map.values());
for(int num: count) result+=num; // jewels의 문자가 stones에 들어있는 개수 넣어주기
return result;
}
```
-> 처음 코드는 이렇게 hashMap을 이용해서 value에 개수를 넣어줬다. 
- 1. jewels에 있는 문자(이때 문자열을 char 배열로 옮긴 다음)를 hashMap key에 넣는다. value는 초기값 0
- 2. stones를 char 배열로 옮기고 문자를 반복하며 hashMap key에 있으면  value +1 해준다.
- 3. hashMap value 값을 다 더한 값! 구한다 고것이 답
태준님 코드를 리뷰하고서 수정해보았다.
``` java
public static int …
```
> 강사님- 보석과 돌

- kkkwp/baekjoon/1026_보물.py
- kkkwp/baekjoon/11047_동전_0.py
- kkkwp/baekjoon/1931_회의실_배정.py
- kkkwp/baekjoon/2217_로프.py
- [백준 11047번 동전 0](https://www.acmicpc.net/problem/11047)
- [백준 1931번 회의실 배정](https://www.acmicpc.net/problem/1931)
- [백준 2217번 로프](https://www.acmicpc.net/problem/2217)
- [백준 1026번 보물](https://www.acmicpc.net/problem/1026)
---
- 그리디
---
- [백준 11047번 동전 0](https://chxrryda.tistory.com/246)
- [백준 1931번 회의실 배정](https://chxrryda.tistory.com/247)
- [백준 2217번 로프](https://chxrryda.tistory.com/248)
- [백준 1026번 보물](https://chxrryda.tistory.com/249)
---
> 백준 그리디 4문제

- sollyj/programmers/Programmers_소수만들기.java
- [프로그래머스 소수만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12977)
---
- 백트래킹
- 소수 구하기
---
- 조합으로 3개를 뽑고 소수 판별 후 answer++
- `combination` 함수 설명
(조합 진행할 배열, 시작 인덱스, 배열 길이, 뽑을 개수)
이미 뽑은 것은 `visited` 를 true로 바꿔준다.
뽑을 개수를 -1씩 하면서 재귀형태로 구현
뽑을 개수가 0이면 3개를 다 뽑았단 뜻이므로, 세 수를 더하고 소수 판별
다 뽑았으면 `visited` 초기화
---
> Programmers 소수만들기

- yunhwan/프로그래머스 입국심사.py
- [프로그래머스 입국심사](https://school.programmers.co.kr/learn/courses/30/lessons/43238)
---
- 이분탐색
---
1. times 정렬
2. start,end 구간 정하기
3. 이분 탐색 진행   
mid 시간동안, 심사할 수 인원을 구한 뒤 n와 비교
4.   심사한 사람의 수가 심사 받아야할 사람의 수(n)보다 적은 경우 start값 조정
심사한 사람의 수가 심사 받아야할 사람의 수(n)보다 많거나 같은 경우 end값 조정
---
> 프로그래머스 입국심사

- jiWoo/프로그래머스_오픈채팅방.java
- [프로그래머스- 오픈채팅방](https://school.programmers.co.kr/learn/courses/30/lessons/42888)
---
- Queue, HashMap
---
- 해당 아이디에 닉네임을 저장하기 위해 hashMap 사용
- 들어오고 나간 것 기록하기 위해 Queue 사용
- 1) Enter이면 닉네임 map에 넣어주고, que에 Enter와 아이디 넣는다.
- 2) Change이면 닉네임 map에 다시 넣기
- 3) Leave이면 que에 Leaved와 아이디 넣는다
- que에서 빼며 Enter와 Leave를 구별하며 해당 아이디에 닉네임을 map에서 꺼내서 넣어준다.
---
> 프로그래머스-오픈채팅방

- jiWoo/프로그래머스_올바른괄호.java
- [프로그래머스 올바른 괄호](https://school.programmers.co.kr/learn/courses/30/lessons/12909)
---
- 스택
---
스택으로 풀이
1. 문자열을 순회
2. 조건문에 따라 적용
1. 열린 괄호일 경우 스택에 추가
2. 아닌 경우, 스택이 비어있지 않고 스택의 맨위가 열린 괄호일 경우
3. 그 외의 경우 False 반환
3. 스택이 비어있지 않을 경우 False, 빈 경우 True
---
> 프로그래머스-올바른 괄호

- yunhwan/프로그래머스 오픈채팅방.py
- [프로그래머스 오픈채팅방](https://school.programmers.co.kr/learn/courses/30/lessons/42888)
---
- 딕셔너리
---
-
1.  record를 띄어쓰기 기준으로 나눠주기
2.  record_list를 순회
3. uid에 따른 닉네임을 딕셔너리에 저장 및 갱신
4. record_list를 순회하며 결과추가
> 프로그래머스 오픈채팅방

- kkkwp/baekjoon/11399_ATM.py
- kkkwp/baekjoon/11501_주식.py
- kkkwp/baekjoon/1541_잃어버린_괄호.py
- [백준 11399번 ATM](https://www.acmicpc.net/problem/11399)
- [백준 1541번 잃어버린 괄호](https://www.acmicpc.net/problem/1541)
- [백준 11501번 주식](https://www.acmicpc.net/problem/11501)
---
- 그리디
---
- [백준 11399번 ATM](https://chxrryda.tistory.com/251)
- [백준 1541번 잃어버린 괄호](https://chxrryda.tistory.com/252)
- [백준 11501번 주식](https://chxrryda.tistory.com/253)
---
> 백준 그리디 3문제

- jiWoo/프로그래머스_뉴스클러스터링.java
- [프로그래머스- 뉴스클러스터링](https://school.programmers.co.kr/learn/courses/30/lessons/17677)
---
- Hash
---
- str1, str2을 2글자씩 끊어서 각각의 hashMap(2글자의 문자열, 개수)에 넣어주었다. 교집합과 합집합을 읽을 때 편리하기 위해 hashSet에 모든 문자열의 종류를 넣어줬다.
- map에 넣어주며 공백이거나 문자가 아니라면 넣어주지 않았다.
- set에 포함된 문자를 map1과 map2와 비교하며
- min(교집합)에는 둘 다 문자를 포함할 때 더 작은 value값을 더해줬다.
- max(합집합)에는 문자를 포함하는 value 값을 더해줬다.
- max와 min이 모두 0일 때만 주의!
---
> 프로그래머스- 뉴스 클러스터링

- jiWoo/프로그래머스_점프와순간이동.java
- [프로그래머스- 점프와 순간 이동](https://school.programmers.co.kr/learn/courses/30/lessons/12980)
---
- 나누기
---
- 나는 왤케 설명을 못할까? 컄; 
1. 1, 2(1x2), 3(2+1), 4(2x2), 5(4+1), 6(3x2), 7(6+1)→ 이런식으로 자신/2가 없으면(자신이 홀수)이면 바로 전 짝수의 값에 +1해준다.
2. 곧 찾을 숫자 n을 2씩 나누어준다.(2보다 크다면) 짝수이면 나눠주고 홀수이면 n-1을 해주며 cnt의 값을 1을 늘려준다. (cnt는 +1을 몇번했는지 check)
3. answer=1+cnt;
---
> 프로그래머스- 점프와 순간 이동

- yunhwan/백준 18404 현명한 나이트.py
- [백준 18404 현명한 나이트](https://www.acmicpc.net/problem/18404)
---
- bfs
---
1. 그래프 및 방문 그래프 생성
2. 나이트 위치 1, 상대편 말 위치 2로 그래프 값 설정
3. bfs 실행하며 나이트 이동 위치를 탐색
4. 나이트 이동 위치가 범위내에 있고 방문한적이 없는 경우:
나이트 이동위치가 상대편 말 위치인 경우: cnt로 그래프값 설정
큐에 위치와 cnt+1 추가 후에 방문 처리
5. 상대편 말들의 그래프 값 출력
> 백준 18404 현명한 나이트

- yunhwan/프로그래머스  H-Index.py
- [프로그래머스  H-Index](https://school.programmers.co.kr/learn/courses/30/lessons/42747)
---
- 정렬
---
-
1. citations 정렬
2. citations 개수만큼 순회 하면서, citations[i]를 h_idx로 설정
3. h_idx번 인용된 논문이 h편 이상이면 pass
4. 그 외의 경우
1. citations이 전부 동일한 경우 논문개수 반환
2. 이전 h_idx 와 이전 h_idx번보다 많이 인용된 논문의 개수 중 큰 값을 answer로 설정 후  break
---
> 프로그래머스  H-Index

- jiWoo/프로그래머스_도둑질.java
- [프로그래머스-도둑질](https://school.programmers.co.kr/learn/courses/30/lessons/42897)
---
- DP
---
- 첫번째와 두번째를 비교해준 이유는 마지막 집에서 구별하기 위해
- D[i]는 처음에 각자 돈으로 초기화해줌
- first와 second를 -1로 구별해줌! (코드에서 확인)
- 두 배열에는 i집을 털었을 때 최댓값 넣어줌
- 인접한 곳 제외 가까운 두 집을 비교해서 최댓값을 더해줬다.( 두 집을 비교한 이유는 그 두 집도 인접해있으므로 서로 누가 최대값일지 모름)
- D+=Math.max(D[i-2], D[i-3];
- answer을 구할 땐 첫 번째는 마지막 집을 못털기 때문에 뒤에서 두번쨰 세번째 비교, 두번째는 마지막 집과 두번째 비교( 아 여기서 안 사실인데 집이 3개 이상이라고 했는데 4개부터인듯→ 오류 안남)
---
> 프로그래머스-도둑질

- jiWoo/프로그래머스_택배상자.java
- [프로그래머스 택배상자](https://school.programmers.co.kr/learn/courses/30/lessons/131704)
---
- stack
---
- main 12345로 꺼낼 수 있도록 넣어주기
- 한글자씩 확인해주는데
- 1) main 벨트 안에 있다면 i 택배상자를 만날 때(answer++)까지 꺼내서 temp 스택에 넣어주기
- 2) main에 없고 temp에 먼저 꺼내는 택배상자가 i 택배상자라면 answer++;
- 1,2에 해당 안하면 break;
---
> 프로그래머스-택배상자

- jiWoo/프로그래머스_할인행사.java
- [프로그래머스 - 할인 행사](https://school.programmers.co.kr/learn/courses/30/lessons/131127)
---
- DP
---
- 해시에 내 위시리스트의 물건과 물건의 인덱스를 넣어줌
```java
HashMap<String, Integer> wanted = new HashMap<>();
int len = want.length;
// 해시에 원하는 물건과 index 넣기
for (int i = 0; i < len; i++) {
wanted.put(want[i], i);
}
```
- 물건의 원하는 수량을 확인할 때 사용!
- 할인 기간 - 10일인 날까지 확인 가능
- 그 기간 동안 10을 확인해준다. ( 중단- check의 값을 false로 )
- 중단: 해당 물건이 위시리스트에 없을 때
```java
// 현재 할인 물건이 내 위시리스트에 포함하지 않으면 확인 끝내기
if (!wanted.containsKey(discount[j])){
check = false;
break;
} 
```
- 중단: 할인 프로모션에서 해당 물건의 개수가 위시리스트에서 원하는 수량보다 이상일 때(수량과 일치해야만함 10개의 물건을 10일을 확인하므로)
```java
// 해당 물건의 수량이 내 위시리스트에서 원하는 수량보다 크면 일치하지 않으므로 탐색 종료
if(cnt[idx] > number[idx]) {
check = false;
break;
} 
```
- 탐색을 종료하고 중단된 일이 없었을 때(check == true)일 때 위시리스트 살 수 있는 날이므로 …
> 프로그래머스 - 할인 행사

- yunhwan/프로그래머스  단속 카메라.py
- [프로그래머스 단속카메라](https://school.programmers.co.kr/learn/courses/30/lessons/42884)
---
- 그리디
---
1. routes를 오름차순으로 정렬
2. 차량의 카메라를 방문했는지 확인하는 v 배열 생성
3. 차량의 수만큼 순회하며  i에 따른 start, end 설정(방문한 경우는 continue)
4. i 이후 오는 차량 j를 순회하며(방문한 경우는 continue)
j의 진입 진출이 start,end 사이에 있는지 확인
있다면 start,end 조정 후 방문 처리
5. answer+=1 증가 후 3 반복
---
> 프로그래머스 단속카메라

- yunhwan/프로그래머스 할인행사.py
- [프로그래머스 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/131127)
---
- 해시
---
1. 10개 단위를 확인해야 하기에, 0,n-9 순회
2. want_dic 초기화
3. 10일을 순회, 
딕셔너리에 포함된다면 해당 값 감소 ,포함되지 않으면 break
4. 딕셔너리의 값이 0인지 확인
맞다면 answer+=1
아니라면 break
---
> 프로그래머스 할인행사

- yunhwan/프로그래머스 도둑질.py
- [프로그래머스 도둑질](https://school.programmers.co.kr/learn/courses/30/lessons/42897)
---
- dp
---
두 가지 경우 가정하여 dp,dp2 생성
첫 집을 털 경우 마지막 집을 없다고 가정
첫 집을 털지 않을 경우 첫번째 집을 없다고 가정
1. p[i][0] 집을 안털 때, dp[i][1] 집을 털 때로 가정
2. money의 개수만큼 순회하며 아래 점화식 적용
dp[i][0] = max(dp[i-1][0],dp[i-1][1])
dp[i][1] = dp[i-1][0] + money[i]
3. dp는 마지막 집이 존재하지 않기에 dp[-2]을 대상으로 비교
dp2는 마지막 집이 존재하기 때문에 dp[-1]을 대상으로 비교
4. dp[-2],dp2[-1] 중 가장 큰 값이 정답
---
> 프로그래머스 도둑질

- yunhwan/프로그래머스 조이스틱
- [프로그래머스 조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860)
---
- 그리디
---
-
1.  알파벳 변경 최솟값  설정 (위,아래 이동 중 작은 값으로 설정) 및 answer에 더하기
2. name의 알파벳을 순회하며,  해당 알파벳 다음부터 연속된 A 문자열 찾기
3. 기존, 연속된 A의 왼쪽시작 방식, 연속된 A의 오른쪽시작 방식 비교 하여 min_move 갱신
4. answer+min_move 반환
---
> 프로그래머스 조이스틱

- yunhwan/프로그래머스-주식가격.py
- [프로그래머스 주식가격](https://school.programmers.co.kr/learn/courses/30/lessons/42584)
---
- 탐색
---
1. len(prices)-1 전 까지 순회하는  i 설정, sec 초기화
2. i+1 부터 len(prices)-1 전 까지 순회하는 j
3. prices[i] <= prices[j]경우 sec증가
아닌 경우, break
4. answer에 sec추가 후 반복
5. 마지막 값은 0 고정이므로 answer에 0추가
---
> 프로그래머스 주식가격

- jiWoo/프로그래머스_요격시스템.java
- [프로그래머스 - 요격시스템](https://school.programmers.co.kr/learn/courses/30/lessons/181188)
---
- 그리디
---
1) targets 배열을 타겟 미사일이 끝나는 지점을 기준으로 오름차순 정렬한다.
- 끝 지점을 기준으로 격추 미사일을 쏘기 위하여
2) 요격 미사일을 반복문을 통하여 격추하는 미사일을 확인한다
- 격추를 확인하는 반복문 돌려준다.
- 기준 미사일(i)의 끝 지점을 기준으로 한 point보다 다음 타켓 미사일의 시작 지점이 작다면 격추(killed++하며 격추한 미사일의 개수를 세준다.)
- 크거나 같다면 격추 실패로 확인하는 반복문 종료(2번째 반복문)
- 반복문이 끝나고 격추한 만큼 기준 미사일 i값에 더해준다.
---
> 프로그래머스 - 요격시스템

- jiWoo/프로그래머스_두원사이의정수쌍.java
- [프로그래머스 - 두 원 사이의 정수 쌍](https://school.programmers.co.kr/learn/courses/30/lessons/181187#)
---
---
- 1사분면에 있는 정수 쌍들만 세어주기( 이때 x축과 y축위의 값은 겹치므로 제외하고 세어주기)
- 반복문을 1부터 큰 원의 반지름 r2전까지 돌린다.
- i는 x값
- start는 y값의 시작값, end는 y값의 종료값
- start는 작은원 영역에 있을 때와 (i가 1~r1) 밖에 있을 때(i가 r1~r2)를 분리해서 지정해줬다.
- start의 값이 정수가 아니거나 y축 위에 있을 때 +1을 해주었다.
```java
for (int i = 1; i < r2; i++) {
// start 예외 처리
// 작은 원 위에 해당하는 0~r1까지와 r1~r2 분리
// start가 정수가 아니거나 y축 위에 있으면 ++
double start = 0.0;
if (i > r1) start = 1.0;
else {
start = Math.sqrt(Math.pow(r1, 2) - Math.pow(i, 2));
if (start % 1 != 0.0 || start == 0.0) start++;
}
double end = Math.sqrt(Math.pow(r2, 2) - Math.pow(i, 2));
if(start > end) continue;
answer += ((long)end - (long)start + 1);
}
```
- 반복문을 종료하고 1~4사분면의 값까지 4를 곱해준다.
```java
// 현재 1사분면만 세주었기 때문에 …
```
> 프로그래머스 - 두 원 사이의 정수 쌍

- jiWoo/프로그래머스_단어변환.java
- [프로그래머스 - 단어 변환](https://school.programmers.co.kr/learn/courses/30/lessons/43163#)
---
- hash, dfs
---
- hash를 사용하여 한 글자만 다른 단어들을 각 단어에 넣어줬다.  ( 글자들을 비교할 때 index로 비교해주는 것 유의해야한다.)
``` java
// 한글자만 다른 단어들 찾아주기
// 유의할 점 index로 확인해서 한글자만 다른 거 찾아주기
public void findWords(char[] array, String[] words) {
int len = array.length;
int count = 0;
for (String w : words) {
count = 0;
if (w.equals(String.valueOf(array))) continue;
for (int i = 0; i < len; i++) {
if (w.charAt(i) == array[i]) count++;
}
if (count == (len-1)) {
ArrayList<String> list = map.get(String.valueOf(array));
list.add(w);
map.put(String.valueOf(array), list);
}
}
}
```
- dfs: 각 변환하는 글자와 한 글자 다른 리스트들을 재귀를 통하여 target에 도달하는 변환 길이를 우선순위큐에 넣어줬다.(우선순위큐는 가장 작은 변환 길이를 찾기 위하여)
``` java
// map에 있는 단어들을 방문 확인하여 dfs
public void dfs(String …
```
> 프로그래머스 - 단어 변환

- jiWoo/프로그래머스_연속된부분수열의합.java
- [프로그래머스 - 연속된 부분 수열의 합](https://school.programmers.co.kr/learn/courses/30/lessons/178870
---
- 투포인터
---
- 투 포인터 알고리즘을 사용하여 left와 right구간을 0부터 시작한다.
- 구간의 값이 작으면 right를 오른쪽으로 옮겨주고(오른쪽의 값을 더해주기 위하여) 크면 left를 오른쪽으로 옮겨준다.(왼쪽의 값을 빼기 위하여) : 오름차순으로 오른쪽에 있는 값이 크다. 
- 구간의 값이 찾는 값 k라면 현재 answer의 값의 차이보다 right - left가 작다면 answer 값을 left와 right로 갱신해준다. 뒤에 값들을 탐색해주기 위하여 right를 오른쪽으로 옮겨준다.
- 주의할 점: left와 right의 인덱스를 옮길 때 해당 인덱스가 끝이라면 더 이상 탐색할 수 없으므로 탐색을 종료해준다.
---
> 프로그래머스 - 연속된 부분 수열의 합

- jiWoo/프로그래머스_달리기경주.java
- [프로그래머스 - 달리기 경주](https://school.programmers.co.kr/learn/courses/30/lessons/178871)
---
- hash
---
- hashMap에 현재 플레이어의 등수인 index 값을 저장한다.
- callings를 읽으며 플레이어의 앞 사람과 배열의 값을 바꿔주고, map에서 index 값도 바꿔준다.
---
> 프로그래머스 - 달리기 경주

- jiWoo/프로그래머스_과제진행하기.java
- [프로그래머스 - 과제 진행하기](https://school.programmers.co.kr/learn/courses/30/lessons/176962)
---
- Hash, Stack
---
- 과제를 수행하기 전 HashMap에 key에 과제 이름을 넣고 value에 걸리는 시간을 넣는다.
``` java
// map에 과제명과 과제 수행 시간을 넣는다.
for (String[] plan : plans) {
map.put(plan[0], Integer.parseInt(plan[2]));
}
```
- 과제를 수행하기 전 과제들을 시작 시간 순으로 정렬한다.
``` java
// plans를 start(과제 시작) 순으로 정렬하기
Arrays.sort(plans, (o1, o2) -> o1[1].toString().compareTo(o2[1].toString()));
```
- 과제를 수행하며 멈춘 과제를 넣을 때 stack에 넣어주었다. 이유는 가장 최근에 멈춘 과제를 꺼내기 위하여
- 과제를 수행하는 반복문을 돌릴 때 다음 과제까지의 가능한 시간 안에 과제를 수행한다면 과제를 끝내고 멈춘 과제들을 수행한다.
- 다음 과제까지의 가능한 시간 안에 과제를 수행하지 못한다면 멈춘 과제에 현재 과제를 넣어준다. 
- 과제를 수행하는 반복문이 끝난 후 남은 멈춘 과제를 정답에 넣어준다.
---
> 프로그래머스 - 과제 진행하기

- jiWoo/프로그래머스/프로그래머스_추억점수.java
- [프로그래머스 - 추억 점수](https://school.programmers.co.kr/learn/courses/30/lessons/176963)
---
- Hash
---
1) Hash에 key에 그리운 사람의 이름 name, value에 그리움 점수 yearning를 넣는다.
-> 사진에서 사람을 읽으면서 hashMap에 있는 지 확인해주고 점수를 찾을 때 사용
2) answer은 사진의 크기만큼 초기화한다.
3) 사진의 크기만큼 반복문을 돌리고 그 사진 안에 사람들을 읽는다. 이 때 map에 해당 사람이 있다면 answer에 그리움의 점수를 map에서 찾아 더해준다.
---
> 프로그래머스 - 추억 점수

- jiWoo/프로그래머스/프로그래머스_광물캐기.java
- [프로그래머스 - 광물 캐기](https://school.programmers.co.kr/learn/courses/30/lessons/172927)
---
- DFS
---
``` java 
// 현재 광물을 3개중에 선택
for (int i = 0; i < 3; i++) {
// result에 피로도를 더해줄 것인데 광물 3개를 비교해줄것이기 때문에 임시 re
re = result;
// 현재 사용할 광물이 있더라면
if (picks[i] > 0) {
// 광물 하나당 5개를 캘 수 있으므로
for (int j = 0; j < 5; j++) {
// 현재 광물이 캘 5개가 캘 광물의 크기를 넘지 않는다면
// 피로도에 더해준다.
if (idx + j < len) {
// 피로도는 5의 제곱을 사용하여 계산식을 만들어 구함
// 곡괭이는 다이아몬드, 철, 돌 순으로 0, 1, 2 인덱스이고
// 현재 광물도 다이아몬드, 철, 돌 순인데
// 곡괭이의 인덱스가 더 크다면 5의 (곡괭이 인덱스 - 광물 인덱스)의 제곱으로
// 인덱스가 작으면 ++로 1만 더해줌
int findIdx = stress.indexOf(minerals[idx + j]);
if (i >= findIdx) re += Math.pow(5, i - findIdx);
else re++;
} else {
// 인덱스가 
answer = Math.min(answer,re); 
return;
}
}
// 사용할 광물을 빼주고 재귀로 DFS 사용
picks[i]--;
DFS(picks, minerals, idx + 5, re);
// 다시 광물 …
```
> 프로그래머스 - 광물 캐기

- jiWoo/백준/백준_요세푸스문제.java
- [백준 - 요세푸스 문제](https://www.acmicpc.net/problem/1158)
---
- queue
---
1. Queue에 1 ~ N 까지 넣는다.
2. Queue가 빌 때까지 반복문을 돌린다.
1. Queue에서 하나를 꺼낸다. 꺼낼 때마다 cnt를 +1 해준다.
2. Cnt가 K일 경우 답 리스트에 넣어주고 cnt를 0으로 초기화
3. Cnt가 K가 아닐 경우 Queue에 다시 넣어준다.
3. 정답을 양식에 맞게 출력
---
> 백준 - 요세푸스 문제
