byeongjoo/백준 17298 오큰수.py
- [백준 17298번 오큰수](https://www.acmicpc.net/problem/17298)
스택
---
설명을 읽기 전 이 문제는 본인의 힘으로만 푼 것이 아닌 몇 일 전 답지를 한 번 확인하고 오늘 풀었습니다.
크기가 N인 수열 A = A1, A2, ..., AN이 있다. 수열의 각 원소 Ai에 대해서 오큰수 NGE(i)를 구하려고 한다. Ai의 오큰수는 오른쪽에 있으면서 Ai보다 큰 수 중에서 가장 왼쪽에 있는 수를 의미한다. 그러한 수가 없는 경우에 오큰수는 -1이다.
예를 들어, A = [3, 5, 2, 7]인 경우 NGE(1) = 5, NGE(2) = 7, NGE(3) = 7, NGE(4) = -1이다. A = [9, 5, 4, 8]인 경우에는 NGE(1) = -1, NGE(2) = 8, NGE(3) = 8, NGE(4) = -1이다.
일단 문제의 시간복잡도를 생각해보자. 시간제한은 1억 번 연산이 가능하지만, n 은 100만, A는 100만 까지 데이터 크기가 가능하다. 한마디로 일단 O(n^2) 이 되는 브루트포스 방식으로는 불가능하다. 그러므로 O(n)이거나 O(logN) 이 될 수 있는 풀이로 해야한다. 트리로 풀 수 있는지는 전혀 모르겠지만, 본인은 O(n)을 고려해 스택으로 풀었다.
본인은 처음 정답을 표기할 ans 리스트를 n 크기로 -1을 깔아두었다. 그러함으로써 첫번째 인덱스가 값이 데이터배열에서 가장 높은 점과 마지막 인덱스의 값이 무조건 -1 이여야 한다는 점에서 -1로 바로 표기할 수 있다.
먼저 스택은 arr의 데이터 값와 그 데이터의 인덱스를 저장했다.
반복문 …
=> 백준 17298번 오큰수

byeongjoo/백준 7569 토마토.py
- [백준 7569번 토마토] : (https://www.acmicpc.net/problem/7569)
---
BFS
---
3차원 배열 BFS 문제.
3차원 배열이기에 dx, dy, dz 로 동서남북을 지정해주었다.
board 리스트는 입력 보드크기이며, dist 리스트는 내가 움직일 거리를 나타내기 위한 리스트이다.
BFS를 돌리기 전에 BFS를 시작할 시작점을 먼저 queue에 삽입을 했다. 익은 토마토를 시작점으로 잡아 보드에서 1인 지점들을 queue에 삽입을 하였고, 익지 않은 토마토는 거리로 잡을 수 있기에 dist에 -1로 잡아두었다. 
그 후 단순한 bfs를 하고, 거리움직임을 가산하기 위해서 다음 dist배열은 현재 dist배열보다 1을 가산하여 대입해주었다. bfs 조건문으로 들어간 첫 if문은 nx, ny, nz의 범위를 넘어서면 continue 해준 것이고,두 번째 if문은 내가 움직이려는 범위는 처음에 깔아두었던 -1이기에 만약 0보다 크다면 이미 누군가 움직였던 칸이기에 continue로 뛰어넘게 하였다.
마지막으로 dist 리스트 중 -1이 아직 남아있다면 bfs 중 남은 칸이 있다는 것이기에 -1을 출력하였고, 최대크기는 max로 계속 비교해주었다.
---
=> 백준 7569번 토마토

hyeonwoo/백준 1259 팰린드롬수.py
- [백준 1259 팰린드롬수](https://www.acmicpc.net/problem/1259)
---
- 구현
- 문자열
---
- 입력 받은 수를 앞, 뒤 절반으로 나누어 앞 절반 부분과 뒤 절반 부분이 대칭인지 비교하였다.
- `10 미만의 수`는 무조건 팰린드롬으로 간주했다.
---
=> 백준 1259 팰린드롬수

byeongjoo/백준 4179 불.py
- [백준 4179번 불] (https://www.acmicpc.net/problem/4179)
---
BFS
---
지훈이와 불 둘 다 수평, 수직 방향으로 1칸씩 이동할 수 있으므로 BFS 로 풀기로 하였다.
지훈, 불 둘 다 이동거리(dist) 리스트와 큐를 따로 만들어주어서 둘 다 BFS가 가능하도록 하였다.
지훈, 불 둘의 초기값을 각각 큐에 삽입을 하였으며, dist 리스트에다가도 초기 위치를 1로 잡아두어 bfs가 자기위치로 뒤돌아가는 것을 막아두었다.
이제 지훈이와 불을 bfs 해야한다.
본인은 불을 먼저 bfs를 돌린 후, 지훈이 bfs를 돌리기로 하였다.
불 bfs는 기본적인 bfs 처리를 해주었다.
지훈이도 기본적인 bfs 를 처리 해주었지만, 조건문에서 불 bfs와 차이가 있다는 점을 알 수 있다.
첫 번째 조건문은 bfs에서 흔히 하는 index가 out range되는 것을 건너뛰기하는 조건이다. 하지만 이 문제 설명 중 지훈이가 불을 피해 밖으로 피신한 거리값을 출력하는 것이기에 이 조건문이 바로 정상 출력을 할 수 있는 곳이다.✨ 정상 출력이 됬다면 프로그램을 종료시켜야 하기에 exit(0) 을 사용해주었다.
두 번째 조건문은 일반적인 bfs 거리 꼬임 방지 및 다음 이동방향이 벽에 부딪혔다면 건너뛰는 조건문이다.
세 번째 조건문이 개인적으로 가장 어려웠는데, 불이 이동했는데 불의 이동시간이 지훈이의 이동시간보다 작거나 같다면 지훈이는 움직일 수 없으며, 또한 불이 움직이지 않은거리는 무조건 지훈이 이동시간보다 값이 낮을테니 조건문에 잡아줘야한다는 것이다.✨
두 개의 bfs 가 …
=> 백준 4179번 불

byeongjoo/백준 1697 숨바꼭질.py
[백준 1697번 숨바꼭질] (https://www.acmicpc.net/problem/1697)
---
BFS
---
1차원 배열로 풀어보는 BFS.
솔직히 BFS 문제집이 아니였다면 BFS인지 몰랐을 것 같다.
수빈이(n) 가 동생(k) 의 위치까지 가는 순간 숨바꼭질이 끝나는 문제이다.
초기 설정으로 board 배열은 필요없고, 거리값만 계산할 dist 배열만 있으면 된다.
BFS 에서 거리 문제 같은 경우 , 몇 가지 조건이 있겠지만 기본적으로 초기지점을 잡는 곳을 0으로 둔다. (움직임이 없으면 거리량이 0 일 수 밖에 없다.) 그러하기에 본인은 dist 배열을 -1로 100002개의 요소로 채워넣었다. (2개 정도는 out range를 막기 위한 방지이다.)
이제 수빈이의 위치를 dist 배열에 삽입하자. (dist[n] = 0). 그 후 queue를 이용하여 수빈이의 초기 위치를 queue에 삽입한다.
이제 while을 돌릴건데, 본인은 bfs에서 while 조건식으로 'queue가 다 빌 때까지' 로 고정관념적으로 생각했는데, 이 문제에선 dist[k] == -1 까지다. 이유는 동생의 위치까지 이동값이 생겨 dist[k]의 값이 변했다는 것은 수빈이와 동생이 만났다는 것을 의미한다.
그 후 dx, dy 가 아닌 for i in (x-1, x+1, x*2) 로 푼다. range-based-for 형식으로 풀면 x-1, x+1, x*2 세 개 다 접근이 가능하기에 조건문을 길게 쓸 필요가 사라진다.
그 후 전형적인 범위 벗어날 때 continue, 이동거리값이 꼬일 때 continue를 해주고 …
=> 백준 1697번 숨바꼭질

hyeonwoo/백준 1966 프린터 큐.py
- [백준 1966 프린터 큐](https://www.acmicpc.net/problem/1966)
---
- 자료 구조
- 큐
---
- 문서의 중요도를 큐에 저장하고, 큐의 첫 번째 값과 큐의 최대값이 다르다면, 현재 문서보다 더 높은 중요도를 가진 문서가 있기 때문에 큐의 첫 번째 값을 빼서 큐의 마지막에 저장한다.
- 큐의 첫 번째 값과 큐의 최대값이 같다면, 첫 번째 값이 즁요도가 제일 높은 문서이기 때문에 큐에서 값을 뺀 후 `cnt` 값을 증가시킨다.
- 반복문을 통해 위 과정을 반복하고, 큐에서 뺀 값이 `m`번째 위치한 문서이면 `cnt` 값을 출력한다.
- 이 때, 중요도가 같은 문서가 존재할 수 있기 때문에 단순히 큐의 인덱스만으로 비교하면 안된다.
- 따라서 문서의 중요도를 큐에 저장할 때, 문서의 중요도의 순서를 인덱스로 가지는 또 다른 큐를 하나 더 만들어서 위 과정에서 큐를 빼거나 저장할 때, 인덱스가 저장된 큐 또한 같은 연산을 수행해서 문제가 요구하는 문서의 위치를 추적하면서 `cnt` 값을 출력한다.
---
=> 백준 1966 프린터 큐

byeongjoo/백준 1929 소수 구하기.py
- [백준 1929번 소수 구하기] (https://www.acmicpc.net/problem/1929)
---
- 에라토스테네스의 체
---
소수 구하기 중 자주 사용하는 에라토스테네스의 체를 이용해서 문제를 풀었다.
에라토스테네스의 체는 2의 배수, 3의 배수, 4의 배수 .... n제곱근의 배수까지 전체 데이터에 배수를 먼저 없애 소수만 남기는 방법이다.
문제를 풀기 위해 1은 소수가 아니므로 2부터 시작하여 n제곱근+1 까지 범위를 잡아 2*2, 2*3 ..... 2*j 가 n과 같거나 작을 때까지 while을 돌려 board 리스트를 False 시켜주었다. (board[i*j] = False)
그 이후 정답을 나타낼 때, m 부터 n까지 반복문을 통해 i가 1일 때는 continue로 건너뛰고, board[i] 가 True일 때, 즉 소수일 때만 출력하도록 만들었다.
---
=> 백준 1929 소수 구하기

hyeonwoo/백준 15829 Hashing.py
- [백준 15829 Hashing](https://www.acmicpc.net/problem/15829)
---
- 문자열
- 해싱
---
- 문자열에 고유 번호를 부여하기 위해 `ord()` 함수를 이용했고, 알파벳 소문자 `a`의 아스키 코드값이 `97`이기 때문에 문자열의 아스키 코드값에서 `96`만큼 빼주어 `1`부터 시작하는 고유 번호를 부여했다.
---
=> 백준 15829 Hashing

byeongjoo/백준 2667 단지번호붙이기.py
- [백준 2667번 단지번호붙이기] (https://www.acmicpc.net/problem/2667)
---
BFS
---
단지와 각 단지에 속한 집의 개수를 세는 문제이다.
BFS로 풀기 위해 처음 아이디어로 각 시작점이 되는 위치를 잡아야되나라고 생각을 하였지만, 그러기엔 1 집합의 위치들이 하나로 모두 합쳐져있는 게 아니라 각각 섹션 별로 나누어져 있어 불가능하다고 생각하였다.
그렇기에 예전에 풀었던 백준 1926번 그림(https://www.acmicpc.net/problem/1926) 문제처럼 일단 초기 queue에 삽입할 때 쓸 조건문과 BFS를 합쳐버리는 형식으로 풀었다.
이중 for문을 이용하여 일단 board의 값이 0이면 뛰어넘어버리고, 1이라면 큐에 i, j값을 삽입한 후, 삽입된 board[i][j] 는 0으로 처리를 하였다. (** 현 코드에서 board[?][?] = 0 으로 되어있는 부분들은 모두 방문처리를 위한 목적이다. => 이유 : 방문처리를 하지 않는다면 bfs 돌다가 다음에 잡히는 값으로도 쓰일 수 있기 때문이다.)
단지 집을 세는 카운트를 1로 만들어주고, 단지는 1씩 추가해주었다.
그 후 BFS 를 돌리며, 만약 board[nx][ny]가 1, 즉 방문하지 않았다면 방문처리를 한 후 단지의 집 카운트를 추가해주었다.
bfs가 끝날 때마다 각 단지의 집을 세는 count를 countList에 삽입해주었다.
마지막으로 출력을 위해 countList를 정렬해주었다.
---
=> 백준 2667 단지번호붙이기

byeongjoo/백준 10026 적록색약.py
[백준 10026번 적록색약] (https://www.acmicpc.net/problem/10026)
---
BFS
---
def bfs 함수는 bfs 관련 함수이다. 일반적인 bfs 구현을 사용했으며, 두번째 조건문이 이번 문제의 킥포인트 중 하나인데 이미 방문처리가 되었거나 (visit[nx][ny] == 1) 보드 상에서 색깔이 바뀌는 지점일 때 (board[nx][ny] == board[x][y]) 는 다음 이동을 건너뛰어야 한다.
def redGreen 함수는 메인이 되는 함수이며, 적록색약을 구분 하는 함수이다. 그러기에 isP라는 파라미터를 줘서 isP가 1이라면 적록색약이므로 빨강-초록을 같은 색으로 만들어주고, 0이라면 같은 색 만드는 과정을 스킵한다. 이 함수 내에서 초깃값을 잡아주는 이유는 적록색약이 아닌 사람과 적록색약인 사람은 같은 보드 내에서 각각 BFS를 사용해야 하므로 초기값을 초기화해준 것이다. 그렇기에 방문배열, 큐, 영역을 세는 count를 초기화해주었다.
출력은 redGreen(0) , redGreen(1) 순으로 출력 해주었다.
** 개인적 생각
적록색약이 아닌 사람이 먼저 값으로 들어오고, 적록색약인 사람이 다음 값으로 들어왔기에 board의 초기값은 망가지지 않고 유지되었다. 하지만 이 적록색약 사람의 순서가 바뀌었다면 board 또한 초기화해주어야 하지 않았을까 싶다.
---
=> 백준 10026번 적록색약

byeongjoo/백준 5427 불.py
[백준 5427번 불] (https://www.acmicpc.net/problem/5427)
---
BFS
---
백준 4179번 불! (https://www.acmicpc.net/problem/4179) 의 응용 버전 문제.
이번에는 테스트 개수가 주어지고, board 모양이 다 달라지므로 테스트 개수를 for문으로 하는 반복문 안에 모든 변수들을 초기화 시켜주어야 한다. 그렇기에 본인은 불 bfs 위해 q1, visit1, 상근이 bfs 위해 q2, visit2 를 초기화를 계속 시켜주었다. board 도 케이스마다 다르므로 초기화를 꼭 시켜줘야한다.
이중 for문을 사용하여 board 안에서 *(불) 과 @(상근이) 의 위치를 찾아 각각의 큐에 삽입 및 visit 배열에 방문처리를 해주었다. (visit[i][j] = 1)
이번 bfs 는 이동거리를 재는 문제이기에 bfs 를 돌릴 때 거리를 나타낼 수 있도록 둘 다 visit[nx][ny] = visit[x][y] +1 처럼 처음 위치에서 멀어질수록 1씩 늘려가는 형태로 지정하였다.
먼저 불 bfs는 일반적인 bfs 처럼 사용하여 visit1 리스트의 값을 채워 넣기 위해 사용하였다.
그 후 상근이 bfs 를 하기 전, impossible을 찍을 수 있도록 하기 위해 boolean 형태로 impossible 변수를 만들고, 상근이 bfs 내에 정답을 찍고 while까지 벗어나기 위해 doubleBreak 변수를 선언해주었다. (✨이 게 백준 4179번 불! 에서 응용된 것이라고 생각한다.)
상근이 bfs를 돌면서 nx, ny 가 board 크기 …
=> 백준 5427번 불

byeongjoo/백준 1629 곱셈.py
[백준 1629번 곱셈] (https://www.acmicpc.net/problem/1629)
---
재귀
---
재귀를 연습해보기 위해 푼 문제.
이 문제는 시간 복잡도가 약 5천 번 ~ 1억 5천 번(최대)을 넘기면 안되지만 이미 한 변수당 최대값이 1억 5천을 넘겨버렸기에 반복문을 사용해서 풀 수 없다고 보였다. 
재귀를 이용해서 공간 메모리를 많이 잡아먹더라도 재귀로 풀면 반복문을 사용하는 것보다 시간복잡도를 줄일 수 있다. (물론 때에 따라 다르다.)
재귀를 사용하기 위해 일단 base condition을 잡아주었다. base condition이란 재귀의 끝 점이라고 보면 된다. 마지막으로 찍고 쭈~욱 리턴을 시킬 곳. base condition으로 지수가 1일 경우는 a % c 만 해도 나머지값이 나오므로 base condition은 1로 잡아두었다.
일단 이 문제에서는 지수를 2로 나누는 식으로 계산을 했다. 지수가 1 아니면 0처럼 모든 각 홀수지수와 짝수지수의 나머지 값은 똑같기 때문이다.
recur 재귀를 도는 것을 식으로 나타내면 a^(b/2) % c 라고 나타낼 수 있다.
그후 result = val * val % c 를 해서 a^b % c 형태로 만들어 준다.
이제 지수가 짝수인지 홀수 인지 판별을 통해 지수인 경우는 result 상태를 return 해주면 되며, 홀수인 경우에는 지수를 2n+1 형태로 만들어주어야 하니 a를 한 번 더 곱한다.
---
=> 백준 1629 곱셈

sollyj/Baekjoon_11724_연결요소의개수.java
- [백준 11724번 연결요소의개수](https://www.acmicpc.net/problem/11724)
---
- 깊이 우선 탐색
- 그래프
---
- 깊이 우선 탐색(DFS)은 말그대로 그래프를 최대 깊이까지 우선 탐색 한 후, 다른 쪽 분기로 이동하여 또 깊이 우선 탐색하는 것을 말한다.
- 우선 인접리스트 A와 방문 기록 배열 visitied를 초기화 해준다.
- A의 인덱스가 정점 숫자가 되는 것이고, A[i]에 해당하는 리스트가 i와 인접해있는 숫자 리스트 이다.
- 1~N까지 DFS을 한다. 재귀형태로 DFS를 하여 최대 깊이 까지 탐색을 하는 것이다.
- visited[i]가 true면 방문 한 적이 있다는 뜻이므로 이미 탐색한 노드이고, false면 방문한 적이 없단 뜻이므로 새로운 연결 요소라고 판단한다.
- 이런식으로 count를 세어 count를 출력한다.
---
=> Baekjoon_11724_연결요소의개수

sollyj/Baekjoon_4949_균형잡힌세상.java
- [백준 4949번 균형잡힌세상](https://www.acmicpc.net/problem/4949)
---
- 스택
---
- 나중에 나오는 괄호를 더 먼저 닫아야하므로 스택의 후입선출 특성을 이용하였다.
- 그리고 마지막에 문자열을 다 돌고도 스택이 안 비어있다는 의미는 아직 안 닫힌 괄호가 있다는 뜻이므로 no
---
=> Baekjoon_4949_균형잡힌세상

sollyj/Baekjoon_13023_ABCDE.java
- [백준 13023번 ABCDE](https://www.acmicpc.net/problem/13023)
---
- 탐색(DFS)
---
- [백준_11724_연결요소의개수](https://github.com/Coding-Test-Study-Group/Coding-Test-Study/pull/125) 와 알고리즘은 같다.
- 좀 더 생각해봐야하는 점은
1. depth 전역 선언
처음에 depth(깊이)를 전역에 선언해서 계속 오답이 났었다.
전역에 선언하면 안되는 이유는 예제입력3 같은 경우다.
사람수 0~5까지 돌면서 0 - 1 - 0(중단), 0 - 2 - 0(중단), ... 이 된다.
depth를 전역에 선언했으므로 누적되어 계속 +되어 5이상이 돼버려 오답 발생
따라서, 한 루프때만 depth가 쓰일수 있도록 해야한다.
2. visited[now]를 다시 false해줘야 하는것
예를들어 A[0]에서 arrive 못했다면 A[1]을 순회해야하는데 A[0] 인접리스트에 1이 있어서 visited했다면 A[1]은 순회 못하게 된다.
따라서 A[i]에서 arrive 못했다면 visited[i] = false해줘서 다음 인접리스트에서 i를 순회할 수 있게 해야한다.
---
=> Baekjoon_13023_ABCDE

byeongjoo/백준 11729 하노이 탑 이동 순서.py
[백준 11729 하노이 탑 이동 순서] (https://www.acmicpc.net/problem/11729)
---
재귀
---
하노이탑은 시작 막대기에서 끝막대기로 모든 원판을 이동시키는데, 밑원판은 윗 원판 위에 놔둘 수 없고 시작과 끝 막대기 사이에 중간 막대기 n개를 이용해 푸는 게임이다.
예를 들어 3개의 막대기와 n개의 원판이 있다치면, 시작점 막대기에서 n-1개의 원판을 중간 막대기로 옮긴 후, n번 원판을 끝막대기로 이동 후 중간 막대기의 n-1개의 막대기를 끝막대기에 올려주면 되는것이다.
1. 재귀함수 만들기
- base condition 잡기
재귀를 끝낼 시점을 잡기 위해 n == 1일 때 return을 통해 재귀를 끝내기로 했다.
- 재귀 돌리기
재귀를 끝내기 위해선 n을 계속해서 깎아주어야 하고, 문제에선 원판 1개씩 옮기는 것이니 n-1을 베이스로 잡고 간다. 처음엔 시작막대기(a)에서 중간막대기(6-a-b)로 옮기고 옮긴 원판이 어디 막대기에서 어느 막대기로 옮겨졌는지 찍은 후(print a, b) 옮긴 중간막대기(6-a-b) 에서 끝막대기(b)로 옮겨주면 된다.
*여기서 왜 6-a-b를 했는지 궁금할 수가 있는데 6은 막대기 번호의 총합이다.(1+2+3)
2. 옮긴 횟수
원판 k개를 옮기기 위해 A번 이동이 필요하다. 
원판 k+1개를 옮길 때 k 개의 원판을 빈곳을 옮길 때 A번, k+1번 원판을 옮길 때 1번, k개의 원판을 다시 빈곳에서 목적지로 옮길 때 A 번 필요하므로 2A+1 번의 이동이 필요하다.
초항이 1이 되기에, 일반항은 2^k - 1 이므로 파이썬으로 …
=> 백준 11729 하노이 탑 이동 순서

hyeonwoo/백준 3053 택시 기하학.py
- [백준 3053 택시 기하학](https://www.acmicpc.net/problem/3053)
---
- 수학
---
- 유클리드 기하학에서 원의 넓이는 `반지름 * 반지름 * 원주율`로 구한다.
- 택시 기하학에서 원은 마름모 꼴의 정사각형이다.
- 따라서, 택시 기하학에서 원의 넓이는 `2 * 반지름 * 반지름`으로 구할 수 있다.
---
=> 백준 3053 택시 기하학

byeongjoo/백준 1074 Z.py
[백준 1074번 Z] (https://www.acmicpc.net/problem/1074)
---
재귀
---
재귀를 하기 위해 한 사각형을 사분면으로 나누어 구하게 했다.
사분면을 나눌 때 면 위치를 구분짓기 위해 사각형의 한 변의 절반을 기준으로 잡았다. 물론 2^n * 2^n 크기로 정사각형이 커지므로 한 변의 절반은 2**(n-1) 이 된다.
1사분면은 행과 열이 절반보다 작으면 되고, 2사분면은 행은 작고 열은 크거나 같으면 되고, 3사분면은 행은 크거나 같고 열은 작고, 4사분면은 행과 열이 크거나 같아야 한다.
2사분면부터는 사각형의 넓이를 더해주는 식으로 구해주어, 특정 행 열의 cnt 누적해줘서 return 으로 제출했다.
2사분면은 사각형 1개, 3사분면은 사각형 2개, 4사분면은 사각형 3개를 더해주면 된다고 생각했다.
---
=> 백준 1074번 Z

sollyj/Baekjoon_1167_트리의지름.java
- [백준 1167번 트리의지름](https://www.acmicpc.net/problem/1167)
---
- 탐색(BFS)
---
- **이 문제를 DFS가 아닌 BFS로 풀어야하는 이유**
예를 들어, 노드3은 노드1과 노드4와 연결되어있는거지, 노드1과 노드4가 연결돼있다고 볼 수는 없다.
만약 DFS로 탐색해서 distance를 구하면 노드3-노드1-노드4의 distance를 구하는 것이 되어버린다.
따라서 이 문제는 너비우선탐색을 써야한다.
(예제입력은 우연찮게 DFS, BFS 결과가 똑같았다.)
- distance배열에서 가장 큰 값으로 다시 시작점 설정해 BFS실행
이 부분을 안해서 계속 오답이 나서 결국 답을 보았다(...)
처음에 임의의 노드(1)로 탐색을 해서 나온 distance배열은 _임의의 노드로부터의 거리_이다.
따라서 이게 답이라고 볼 수 없으므로, 임의의 노드에서 제일 먼 노드에서 다시 탐색을 해야한다.
---
=> Baekjoon_1167_트리의지름

byeongjoo/백준 1780 종이의 개수.py
[백준 1780번 종이의 개수] (https://www.acmicpc.net/problem/1780)
---
재귀, 분할정복
---
종이는 3^n * 3^n의 형태이며, 최소 종이의 크기는 1 * 1 이다. 
종이는 계속해서 9등분 형태로 나타내지며, 각 행과 열의 크기 차이는 3^n만큼 차이가 나게 된다.
크기 차이를 offset이라고 잡고, 행과 열을 x , y 로 나타냈을 때 좌표로 나타낸다면
(x,y)           (x,y+offset)            (x,y+2*offset)
(x+offset, y)    (x+offset, y+offset)    (x+offset, y+2*offset)
(x+2*offset, y) (x+2*offset, y+offset)   (x+2*offset, y+2*offset)
이런 형태가 된다.
일단 3^n * 3^n 종이가 모두 같은 수라면 종이를 9등분하지 말고 하나의 수로 나타내어 합계에 1을 추가해야되기에, target과 flag를 잡아야 된다.
target은 한 종이가 같은 수인지 체크하기 위해 사용되는 변수이며, flag 또한 같은 수인지 체크를 하기 위한 변수 및 각 숫자의 합에 가산을 위한 조건문의 condition이 될 것이다.
윗 이중 반복문은 각 종이의 위치 및 크기만큼 반복을 돌려 같은 수로만 이루어져있는지 아니면 다른 수로 구성되어 있는지 확인을 하기 위한 반복문이다.
반복문을 통해 flag 상태가 변해 false가 됬다면 합계에 접근하면 안되고, false 가 true가 유지되었다면 3^n * 3^n 크기의 종이가 같은 수로만 …
=> 백준 1780 종이의 개수

byeongjoo/백준 1992 쿼드트리.py
[백준 1992번 쿼드트리](https://www.acmicpc.net/problem/1992)
---
재귀, 분할정복
---
분할정복을 사용해서 풀어야 되는 문제.
이 보드도 1/2 크기로 계속 잘라서
|||
|:---:|:---:|
|1|2|
|3|4|
순으로 나열 했을 때, 1->2->3->4 순으로 움직여야한다.
1/2 크기로 자르기 위해 offset 은 base condition 이 되는 1로 가까워져야 한다.
이후
|||
|:---:|:---:|
|(x,y)|(x,y+offset)|
|(x+offset,y)|(x+offset, y+offset)|
형식으로 재귀를 돌린다.
재귀를 돌리기전 '(' 을 하고, 사분면을 다 재귀를 했다면 ')'을 한다.
target 과 board가 일치한다면 분할을 할 필요 없이 정답에 나타낼 ans 리스트에 현재 값을 집어 넣는다.
마지막으로 ans리스트를 문자열로 만든 answer을 출력하면 된다.
---
=> 백준 1992 쿼드트리

sollyj/Baekjoon_2178_미로.java
- [백준 2178번 미로](https://www.acmicpc.net/problem/2178)
---
- 탐색(BFS)
_DFS보다 BFS가 적합한 이유는 목적지까지 가는 짧은 시간을 구해야하는것이기 때문에 해당 깊이(여기서는 행)에서 갈수있는 노드탐색을 마친 후 다음 깊이로 넘어가야하기 때문이다._
---
- 필요한 변수
N(행), M(열)
miro(2차원배열)
dist(2차원배열): 방문한 곳에 거리를 누적해서 +1할 배열
하, 우, 상, 좌 탐색할 x, y좌표 배열 (하, 우방향으로 가므로 하, 우를 먼저 탐색)
queue
- 일반적인 BFS알고리즘과 똑같다. (0, 0)부터 시작하므로 큐에 넣고
- 방문했다는 의미가 곧 dist++와 같기때문에 dist에 누적하여 +1해준다.
- 좌표 유효성(미로를 넘어가진 않는지, 벽에 부딪히진 않는지) 검사와 갈 수 있는칸 검사를 한 후 큐에 넣어주고 또 dist에 누적하여 +1해준다.
- 그렇게 해서 최종적으로 dist[N-1][M-1]을 출력
---
=> Baekjoon_2178_미로

kkkwp/백준 1931번 회의실 배정.kts
- [백준 1931번 회의실 배정](https://www.acmicpc.net/problem/1931)
---
- 그리디
---
- 회의가 끝났을 때(now) 지금으로부터 회의가 끝난 시간(end)이 가장 빠른 것을 선택했을 때 회의를 가장 많이 할 수 있다. 따라서 end를 기준으로 정렬 (1순위)
- 회의 시간이 (5, 6), (6, 6)일 때는 전자를 선택해야 회의를 한번 더 진행할 수 있다. 따라서 start를 기준으로 정렬하는 것도 필요(2순위)
---
=> 백준 1931번 회의실 배정

sollyj/Baekjoon_1764_듣보잡.java
- [백준 1764번 듣보잡](https://www.acmicpc.net/problem/1764)
---
- 자료구조
---
- 듣도 못한 사람 배열을 순회하면서 있는지 확인해야 하는데 배열이나 ArrayList를 쓰면 시간초과가 발생한다. -> HashSet 사용
- 그리고 듣보잡 사람들을 사전순으로 출력하기위해 sort도 해야하는데 Arrays의 sort보다 Collections의 sort가 시간복잡도면에서 우수하기때문에 ArrayList를 사용했다
- **[JAVA Collection 시간복잡도 정리](https://www.grepiu.com/post/9)**
---
=> Baekjoon_1764_듣보잡

sollyj/Baekjoon_1715_카드정렬.java
- [백준 1715번 카드정렬하기](https://www.acmicpc.net/problem/1715)
---
- 그리디
- 큐(우선순위 큐)
---
- 카드 묶음의 크기가 작은것부터 더하는 것이 비교 횟수를 최소화 할 수 있다. -> 우선순위큐
- 누적하여 더해야하므로 두가지를 뽑아 더한후 그걸 또 다시 우선순위큐에 넣는다.
- 우선순위큐의 크기가 1이되면 반복문을 종료한다.
---
=> Baekjoon_1715_카드정렬

sollyj/Baekjoon_1931_회의실배정.java
- [백준 1931번 회의실배정](https://www.acmicpc.net/problem/1931)
---
- 그리디
---
- 연속으로 회의를 배정하려면 일단 회의 끝나는 시간을 기준으로 오름차순 정렬해 배열에 저장해야한다.
- 만약, 회의 끝나는 시간이 같다면 회의 시작 시간을 기준으로 오름차순 정렬한다.
- 정렬이 완료된 배열을 가지고 겹치지 않는 회의수를 카운트한다.
---
=> Baekjoon_1931_회의실배정

taejun/programmers/크기가작은부분문자열.java
- [프로그래머스 크기가 작은 부분 문자열](https://school.programmers.co.kr/learn/courses/30/lessons/147355)
---
**부분 문자열**을 활용하는 것이 핵심이라고 느꼈습니다.
---
이번 문제는 **부분 문자열**을 잘 활용하는 것이 핵심이다.
- t에서 p의 길이만큼 잘라가며 부분 문자열(result)을 만든다.
- 위에서 만든 부분 문자열(result)가 p를 정수로 변환한 값보다 작거나 같은지를 확인하여 카운트를 세면 된다.
바로 코드를 작성해보자.
```java
int answer = 0;
int len = p.length();
int result = 0;
int target = Integer.parseInt(p);
```
먼저 t에서 만든 부분문자열이 p보다 작거나 같은지를 검증하여 카운트를 증가시킬 변수 answer를 초기화한다.
또한, p의 길이를 len이라는 변수에 저장하여 사용한다.
t에서 len만큼 잘라 만들 부분 문자열을 담을 result 변수를 만든다.
마지막으로 p를 정수로 담아 result와 비교하기 위한 target 변수를 만들면 된다.
```java
for(int i=0; i<t.length(); i++) {
if(i+len <= t.length()) {
result = Integer.parseInt(t.substring(i, i+len));
if(result <= target) answer++;
}
}
```
이제 t를 순회하면서 **p의 길이만큼 부분 문자열로 잘라서 정수로 변환한 값인 result과 p를 정수로 변환한 …
=> 프로그래머스 크기가 작은 부분 문자열

taejun/baekjoon/10811.java
- [백준 10811번 바구니 뒤집기](https://www.acmicpc.net/problem/10811)
---
- 배열을 활용한 일반적인 구현 문제입니다.
---
이번 `바구니 뒤집기` 문제는 배열의 일정 인덱스의 범위만큼을 담아둘 **임시 배열**을 활용하여 풀 수 있었다.
N만큼의 길이를 가지는 원본 배열에서 주어지는 **i와 j만큼의 범위만큼을 잘라서 역순으로 담은 임시배열을 원본 배열에 덮어씌우는 방식**을 적용하였다.
- N과 M을 입력받고 N만큼의 길이를 가지는 배열을 생성한 뒤 1부터 N까지의 값으로 초기화한다.
- M만큼 반복하면서 i와 j를 입력받고, i와 j의 인덱스의 범위를 가지는 임시배열을 초기화 한다.
- 여기서 임시배열의 크기는 `j-i+1`만큼을 가져야 한다.
- 원본 배열을 역순으로 임시배열에 담기 위해 j부터 i까지 역순으로 순회하면서 j-i의 인덱스 범위만큼 역순으로 임시배열에 담는다.
- 특정 범위만큼 역순으로 담긴 임시배열이 만들어졌다면 원본배열에 해당되는 범위에 임시배열의 값을 덮어씌운다.
아이디어를 말로 설명하자니 조금 복잡할 수 있다.
바로 코드를 작성해보자.
```java
int N = Integer.parseInt(st.nextToken());
int M = Integer.parseInt(st.nextToken());
int[] arr = new int[N];
for(int i=1; i<=N; i++) {
arr[i-1] = i;
}
```
N과 M을 공백 기준으로 입력받은 후, N의 크기를 가지는 arr 배열을 선언하고 1부터 N까지의 값으로 초기화한다. …
=> 백준 10811 바구니 뒤집기

taejun/programmers/기사단원의무기.java
- [프로그래머스 기사단원의 무기](https://school.programmers.co.kr/learn/courses/30/lessons/136798)
---
- 일반적인 구현 문제이나, 약수를 구하는 알고리즘을 잘 고려해야 합니다.
---
이번 `기사단원의 무기` 문제는 전반적인 구현까지의 과정은 단순하나 중간에 필요한 **약수 개수를 구하는 알고리즘**을 잘 구성해야 한다.
- 주어진 number 만큼 1부터 number까지 배열로 만든다.
- 위에서 만든 배열을 순회하면서 각 요소마다 **약수의 개수**를 구하고 이를 공격력으로 칭한 변수에 담는다.
- 약수의 개수를 구하는 로직을 **별도의 함수에서 수행**한다.
- 구한 공격력(약수의 개수)가 limit보다 크다면, power로 대체한다.
- 마지막으로 모든 공격력의 누적합을 구하면 요구하는 철의 무게가 된다. 
아이디어 자체는 간단하니 바로 코드를 작성해보자.
```java
int answer = 0;
int[] knights = new int[number];
for(int i=0; i<number; i++) {
knights[i] = i+1;
}
```
먼저 모든 기사단원의 공격력을 합해 철의무게를 반환할 answer 변수와 주어진 number 만큼의 크기를 가질 knights 배열을 선언한다.
그리고 1부터 number까지의 수로 knights 배열을 초기화한다.
```java
for(int i=0; i<knights.length; i++) {
int atk = divisor(knights[i]);
if(atk > limit) atk = …
```
=> 프로그래머스 기사단원의 무기

sollyj/programmers/Programmers_콜라츠추측.java
- [프로그래머스 콜라츠추측](https://school.programmers.co.kr/learn/courses/30/lessons/12943)
---
- 구현
---
- 매개변수로 받은 num을 long형으로 바꿔주는 이유는
- `1 <= num < 8,000,000` 이기 때문에 num이 커지면 연산을 하다가 값이 커져 int `오버플로우` 현상이 나타난다.
- 그래서 임의로 long형으로 바꿔주였다.
---
=> Programmers_콜라츠추측

hyeonwoo/Python/프로그래머스/프로그래머스 연속 부분 수열 합의 개수.py
- [프로그래머스 연속 부분 수열 합의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/131701)
---
- 구현
---
- 문제는 `1`부터 `elements` 원소 개수만큼의 길이를 가진 연속 부분 수열의 합의 총 가짓수를 구하는 것이다.
- 길이가 `1`인 연속 부분 수열을 구하기 위해서는 `[7, 9, 1, 1, 4]`의 배열에서 한 개씩 묶어서 더해주면 된다.
- `[7] -> 합: 7`
- `[9] -> 합: 9`
- `[1] -> 합: 1`
- `[1] -> 합: 1`
- `[4] -> 합: 4`
- 따라서, `[1, 4, 7, 9]` 총 `4`가지의 합을 구할 수 있다.
- 길이가 `2`인 연속 부분 수열을 구하기 위해서는 `[7, 9, 1, 1, 4, 7]`의 배열에서 두 개씩 묶어서 더해주면 된다.
- `[7, 9] -> 합: 16`
- `[9, 1] -> 합: 10`
- `[1, 1] -> 합: 2`
- `[1, 4] -> 합: 5`
- `[4, 7] -> 합: 11`
- 따라서, `[2, 5, 10, 11, 16]` 총 `5`가지의 합을 구할 수 있다.
- 길이가 `3`인 연속 부분 수열을 구하기 위해서는 `[7, 9, 1, 1, 4, 7, 9]`의 배열에서 세 개씩 묶어서 더해주면 된다.
- `[7, 9, 1] -> 합: 17`
- `[9, 1, 1] -> 합: 11`
- `[1, 1, 4] -> 합: 6`
- `[1, 4, 7] -> 합: 12`
- `[4, 7, 9] -> 합: 20`
- 따라서, `[6, 11, …
=> 프로그래머스 연속 부분 수열 합의 개수

hyeonwoo/Python/백준/백준 25556 포스택.py
- [백준 25556번 포스택](https://www.acmicpc.net/problem/25556)
---
- 스택
---
- 길이가 `N`인 순열의 첫 번째 원소부터 순서대로 4개의 스택 중 임의의 스택에 원소를 삽입하고, 순열의 모든 원소를 삽입했다면 4개의 스택 중 하나의 스택에서 수를 꺼내 새로운 순열(*오른쪽에서 왼쪽으로 나열*)을 만들어냈을 때, 새로운 순열이 오름차순이면 `YES`를 출력하고, 그렇지 않다면 `NO`를 출력하는 문제이다.
- 문제의 핵심은 스택을 이용해 문제 설명을 그대로 구현하는 것이 아닌 순열이 오름차순이 될 수 있게끔 스택에 원소를 넣고 뺄수 있는가를 판별하면 된다.
- 위 그림과 같이 스택에 넣으려는 원소가 스택에 담겨져 있는 숫자보다 크다면 스택에 삽입하고, 스택에 담겨져 있는 숫자보다 작다면 다른 스택에 삽입한다.
- 위 그림은 스택에 넣으려는 원소가 스택에 담겨져 있는 숫자보다 작아 4개의 스택을 전부 사용했고, 넣으려는 원소가 4번째 스택의 마지막 원소보다 작아 추가적으로 담을 스택이 없다.
- 즉, 최종적으로 네 개의 스택에서 원소를 꺼내 새로운 순열을 만들 때 오름차순으로 만들 수 없다는 뜻이 된다.
- 이를 통해 입력받은 순열에서 네 개의 스택에 원소를 삽입할 때, 스택의 마지막 숫자를 비교해 원소가 크다면 스택에 삽입하고, 원소가 작다면 다른 스택에 삽입하고, 다른 스택에 삽입할 때 첫 번째, 두 번째, 세 번째, 네 번째 스택까지 확인했는데도 원소가 스택의 숫자보다 작다면 이 순열은 오름차순으로 만들 수 없는 순열이므로 `NO`를 출력한다.
--- …
=> 백준 25556 포스택
